### ISSUE TITLE
ubuntu ships with none executable tmp dir

### ISSUE THREAD

**Issue by houqp** [Homebrew/linuxbrew#128]
This makes configure script not executable during build process. Should we detect this and warn user or move the temporary build directory to $HOME?

**Comment by cesarjorgemartinez** [comment]
Hi,
It would be nice update installation instructions linuxbrew, with HOMEBREW_TEMP?

ln -s `which gcc` $HOME/.linuxbrew/bin/gcc-`gcc -dumpversion |cut -d. -f1,2`
ln -s `which g++` $HOME/.linuxbrew/bin/g++-`g++ -dumpversion |cut -d. -f1,2`
RHEL7:
ln -s `which gfortran` $HOME/.linuxbrew/bin/gfortran-`gfortran -dumpversion |cut -d. -f1,2`
RHEL6:
ln -s `which gfortran` $HOME/.linuxbrew/bin/gfortran-4.4

Create brewenv.sh
export PATH="$HOME/.linuxbrew/bin:$PATH"
export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
export HOMEBREW_TEMP="$HOME/.linuxbrew/tmp"

Load brew environment:
. $HOME/brewenv.sh

**Comment by cesarjorgemartinez** [comment]
brew update 
brew tap homebrew/dupes

**Comment by sjackman** [comment]
I'd prefer to add the compiler symlink creation magic to the code itself than to the documentation. The `HOMEBREW_TEMP` issue should be documented for Ubuntu, or even better, the code code check whether `/tmp` is executable. In the mean time, feel free to create a [Wiki page](https://github.com/Homebrew/linuxbrew/wiki) to add documentation, which you can do yourself.
