### ISSUE TITLE
Unable to bootstrap gcc

### ISSUE THREAD

**Issue by oneillkza** [Homebrew/linuxbrew#137]
I'm trying to install linuxbrew on a machine running CentOS 6.5, which means that it has extremely outdated packages, such that linuxbrew does not want to use the system-installed gcc. I have no systems rights on the machine, so cannot upgrade these myself.

The suggested solution by linuxbrew is:

```
To install this formula, you may need to:
  brew install gcc
```

However, when I run `brew install gcc`, the following happens:

```
==> Installing dependencies for gcc: gmp, mpfr, libmpc, pkg-config, isl, 
==> Installing gcc dependency: gmp
Error: gmp cannot be built with any available compilers.
 To install this formula, you may need to:
  brew install gcc
```

**Comment by tseemann** [comment]
I just got burnt with this exact same issue when I decided to start from scratch after screwing up my existing Linuxbrew install. However I did *not* have to do this bootstrap the first time around? Has something changed since Feb 2015?

**Comment by sjackman** [comment]
It changed at some point, but I'm not sure when. Sorry I couldn't be more helpful.

**Comment by wenerme** [comment]
After ls, I can install hello, but test not good

```
# brew -v test hello
Homebrew 0.9.5
Error: cannot load such file -- minitest/unit
Please report this bug:
    https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/share/ruby/test/unit/assertions.rb:1:in `<top (required)>'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/wener/.linuxbrew/Library/Homebrew/formula_assertions.rb:7:in `rescue in <module:Assertions>'
/home/wener/.linuxbrew/Library/Homebrew/formula_assertions.rb:4:in `<module:Assertions>'
/home/wener/.linuxbrew/Library/Homebrew/formula_assertions.rb:2:in `<module:Homebrew>'
/home/wener/.linuxbrew/Library/Homebrew/formula_assertions.rb:1:in `<top (required)>'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/wener/.linuxbrew/Library/Homebrew/cmd/test.rb:2:in `<top (required)>'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/wener/.linuxbrew/Library/brew.rb:58:in `require?'
/home/wener/.linuxbrew/Library/brew.rb:122:in `<main>'
```

**Comment by sjackman** [comment]
Please report `ruby --version`. This minitest issue has come up before. See #314

**Comment by wenerme** [comment]
```
ruby --version
ruby 2.0.0p598 (2014-11-13) [x86_64-linux]
```

**Comment by tseemann** [comment]
@wenerme I got the same problem. As #314 says, just use the Brew version of ruby: ```brew install ruby```.

**Comment by wenerme** [comment]
Thanks @tseemann , the test pass now

**Comment by tomekwi** [comment]
This fails for me with `gcc 5.1` – `brew` doesn’t seem to recognize the `gcc-5.1` symlink as `gcc`:

```
$ brew install gcc
==> Installing dependencies for gcc: gmp, mpfr, libmpc, isl
==> Installing gcc dependency: gmp
Error: gmp cannot be built with any available compilers.
To install this formula, you may need to:
  brew install gcc
```

Here’s what seems to do the job – but I can’t help feeling it’s a hack:

```
$ ln -s $(which gcc) ~/.linuxbrew/bin/gcc-4.4
$ ln -s $(which g++) ~/.linuxbrew/bin/g++-4.4
$ brew install gcc g++
```

It needs time to compile – I’ll let you know as soon as I know the results.

**Comment by tomekwi** [comment]
Hmm, that’s a nope:

```sh
==> Installing gcc
# …
==> make bootstrap
Makefile:20663: recipe for target 'stage3-bubble' failed
make[1]: *** [stage3-bubble] Error 2
make[1]: Leaving directory '/tmp/gcc20150620-26406-gm4c73/gcc-5.1.0/build'
Makefile:20726: recipe for target 'bootstrap' failed
make: *** [bootstrap] Error 2

READ THIS:
# …
```

**Comment by DoomHammer** [comment]
Try perhaps `ln -s $(which gcc) ~/.linuxbrew/bin/gcc-5` and `ln -s $(which g++) ~/.linuxbrew/bin/g++-5`

**Comment by paulhybryant** [comment]
My gcc installation also failed at Make bootstrap but for different reason.

gist logs here https://gist.github.com/anonymous/c7ac66274508a6525b8d

In short the error seems to be that it cannot find the shared library libisl.so.13
However, I can see isl installed with brew and it is available at
~/.linuxbrew/lib/

**Comment by paulhybryant** [comment]
OK I think my case is different from the above. The problem with my issue is ldconfig

ldconfig would report the following error:
ldconfig: Warning: ignoring configuration file that cannot be opened: $HOME/.linuxbrew/Cellar/glibc/2.19/etc/ld.so.conf: No such file or directory

I see that ld.so.cache symlinked to ld.so.cache in the same folder, but there is no ld.so.conf file.
Is this a bug?

**Comment by sjackman** [comment]
Linuxbrew does not use `ld.so.conf`. It uses `rpath` instead. Using `ld.so.conf` makes a lot of sense though, I think. In any case, it's not necessary, and you can ignore the `ldconfig` warning.

**Comment by sjackman** [comment]
https://gist.githubusercontent.com/anonymous/c7ac66274508a6525b8d/raw/02.make
```
make[3]: Leaving directory `/tmp/gcc20150622-5108-1qwsx8g/gcc-5.1.0/build/gcc'
mkdir -p -- x86_64-unknown-linux-gnu/libgcc
Checking multilib configuration for libgcc...
Configuring stage 2 in x86_64-unknown-linux-gnu/libgcc
…
checking for suffix of object files... configure: error: in `/tmp/gcc20150622-5108-1qwsx8g/gcc-5.1.0/build/x86_64-unknown-linux-gnu/libgcc':
configure: error: cannot compute suffix of object files: cannot compile
See `config.log' for more details.
make[2]: *** [configure-stage2-target-libgcc] Error 1
```

Can you gist the appropriate `config.log`? There's more than one. The one with the most recent time stamp.

**Comment by diegocaro** [comment]
+1, I cant compile gcc (5.1). It seems to be related with a zlib dependency (not installed by default in most linux distros, but already installed in os x).
I tried installing zlib, but it fails after the bootstrap stage.

**Comment by sjackman** [comment]
@diegocaro Try `brew install homebrew/dupes/zlib gcc`

**Comment by kim612** [comment]
In my case (CentOS 5.11 with gcc44),

prefix=~/.linuxbrew
ln -s /usr/bin/gcc44 $prefix/bin/gcc-4.4
ln -s /usr/bin/g++44 $prefix/bin/g++-4.4
ln -s /usr/bin/gfortran44 $prefix/bin/gfortran-4.4
export HOMEBREW_CC=gcc-4.4
brew install hello

Error: Homebrew GCC requested, but formula gcc44 not found!

unset HOMEBREW_CC
brew install hello 
(no error)

**Comment by sjackman** [comment]
Can you try `brew tap homebrew/versions && brew install hello`.

**Comment by jorgebg** [comment]
This worked for me (CentOS):
```bash
brew install gcc --cc=gcc 
```

**Comment by dakl** [comment]
To get symlinking to work I've had to 
```
prefix=~/.linuxbrew
ln -s /usr/bin/gcc $prefix/bin/gcc-4.4
ln -s /usr/bin/g++ $prefix/bin/g++-4.4
ln -s /usr/bin/gfortran $prefix/bin/gfortran-4.4
export HOMEBREW_CC=gcc-4.4
brew tap homebrew/versions
brew install hello && brew test -v hello; brew remove hello
```

`brew tap homebrew/versions` seems to be needed in there. The I don't have to use `--cc=gcc` at all it seems like.

**Comment by Scapadiver** [comment]
joergbg's solution worked for me also - centos

**Comment by sjackman** [comment]
> `brew install gcc --cc=gcc`

And it doesn't work without `--cc=gcc`? That's odd. Thanks for the feedback.

**Comment by prologic** [comment]
@sjackman When I try ``--cc=gcc`` to bootstrap gcc I get an error at the end I don't understand (*and my search results don't specifically mention/relate to this*):

```#!bash
$ brew install gcc --cc=gcc
==> Installing dependencies for gcc: zlib, gmp, mpfr, libmpc, isl
==> Installing gcc dependency: zlib
==> Downloading http://zlib.net/zlib-1.2.8.tar.gz
Already downloaded: /home/prologic/.cache/Homebrew/zlib-1.2.8.tar.gz
==> Patching
patching file configure
==> ./configure --prefix=/home/prologic/.linuxbrew/Cellar/zlib/1.2.8
==> make install
Error: No such file or directory - (unreachable)/
```

**Comment by prologic** [comment]
Disregard last comment (*deleted*) -- If you have modified changes in the git tree you'll cause problems with bew :)

**Comment by prologic** [comment]
Actually I'm having a lot of trouble getting Homebrewed linux gcc bootstrapped.

1. ``sudo yum groupinstall 'Development Tools'``
2. brew install gcc --cc=gcc

```#!bash
$ brew install gcc --cc=gcc
==> Installing dependencies for gcc: mpfr, libmpc, isl
==> Installing gcc dependency: mpfr
Error: /home/prologic/.linuxbrew/opt/xz not present or broken
Please reinstall xz. Sorry :(
```

Okay so let's install ``xz`` first:

```#!bash
$ brew install xz --cc=gcc
==> Downloading https://fossies.org/linux/misc/xz-5.2.2.tar.gz
Already downloaded: /home/prologic/.cache/Homebrew/xz-5.2.2.tar.gz
==> ./configure --disable-silent-rules --prefix=/home/prologic/.linuxbrew/Cellar/xz/5.2.2
==> make install
Error: No such file or directory - (unreachable)/
```

I've also tried and have in place @dakl's [snippet](https://github.com/Homebrew/linuxbrew/issues/137#issuecomment-136639584) which doesn't seem to help because tapping ``homebrew/versions`` yields:

```#!bash
$ brew tap homebrew/versions
==> Tapping homebrew/versions
fatal: Could not change back to '(unreachable)/': No such file or directory
Error: Failure while executing: git clone https://github.com/Homebrew/homebrew-versions /home/prologic/.linuxbrew/Library/Taps/homebrew/homebrew-versions --depth=1
```

**Comment by sjackman** [comment]
That's a strange error message `Error: No such file or directory - (unreachable)/`. I've not seen that before. Does `brew install hello` work?

**Comment by prologic** [comment]
Nope :/

**Comment by sjackman** [comment]
Moved this discussion to #608.

**Comment by r41d** [comment]
I tried to use linuxbrew on a Gentoo server and my error looked like this:
```
==> Installing dependencies for ncdu: pkg-config, gpatch, ncurses
==> Installing ncdu dependency: pkg-config
gcc-config: error: could not run/locate 'gcc-5'
Error: pkg-config cannot be built with any available compilers.
Install Clang or brew install gcc
```
For me the command `brew link --overwrite gcc` did the trick and created all necessary symlinks so everything would work.
