### ISSUE TITLE
Glibc fails to install due to LD_LIBRARY_PATH containing working directory

### ISSUE THREAD

**Issue by oneillkza** [Homebrew/linuxbrew#141]
I'm on CentOS 6.5 with no root access.

To get LinuxBrew working, I added the linuxbrew bin dir to `$PATH`,  and the linuxbrew lib dir to `$LD_LIBRARY_PATH`:

```
export PATH="$HOME/.linuxbrew/bin:$PATH"
export LD_LIBRARY_PATH="$HOME/.linuxbrew/lib:$LD_LIBRARY_PATH"
```

Unfortunately, glibc won't compile, giving the error:

```
$ brew install glibc
==> Downloading http://ftpmirror.gnu.org/glibc/glibc-2.19.tar.bz2
Already downloaded: /home/koneill/.cache/Homebrew/glibc-2.19.tar.bz2
==> ../configure --disable-debug --disable-dependency-tracking --disable-silent-
checking LD_LIBRARY_PATH variable... contains current directory
configure: error:
*** LD_LIBRARY_PATH shouldn't contain the current directory when
*** building glibc. Please change the environment variable
*** and run configure again.
```

If I remove linuxbrew from `$LD_LIBRARY_PATH`, then glibc fails since it can't find its dependencies. 

What is weird, is that, looking in glibc.rb, it seems like linuxbrew should be making a separate build directory for compiling glibc, so it shouldn't be in the same directory as specified in `$LD_LIBRARY_PATH`. But my knowledge of Ruby and understanding of the inner workings of linuxbrew is not quite up to puzzling out exactly what's going on.

**Comment by hkcqr** [comment]
@sjackman Hi, I met a similar problem. I tried your mentioned method. Actually, linux doesn't interpret ":" as ".". I solved my problem by checking the system profile and removed the ":." symbol which could be added by the inexperience server engineer. 
Hope it'll be some help for you.

**Comment by dragonxlwang** [comment]
I am compiling llvm-libclang from source and it needs a new version of glibc which I happen can use from the linuxbrew version... @sjackman said that user should not touch $LD_LIBRARY_PATH. I know that install form brew will work without problem but how about those installed from scratch that needs to link against glibc from the homebrew? I have this problem because there is no formula for libclang yet...

**Comment by sjackman** [comment]
The easiest way is to use `brew sh` to get a shell with the appropriate environment variables set, and build within there. Does `brew install llvm --with-clang` install `libclang` for you?

**Comment by dragonxlwang** [comment]
thanks! Let me try for real quick

**Comment by dragonxlwang** [comment]
I am actually trying to install you complete me on Scientific Linux release 6.7 (Carbon), and it requires a new libclang also glibc which I hope to get from homebrew. Let me try the shell method

**Comment by dragonxlwang** [comment]
@sjackman I looked into man page and it seems not clear to me what exactly env did brew change after ``brew sh``. neither PATH nor LD_LIBRARY_PATH changed. Am I missing anything here?

**Comment by dragonxlwang** [comment]
it seems by using ``brew sh``, it doesn't work correctly. 

For example, when compiling you-complete-me with brew sh enabled:

I got following output from ycm:

```
$ ./install.py --clang-completer --system-libclang
Re-run cmake no build system arguments
-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
```
The GCC is 4.4.7

however, if I don't use ``brew sh``, I could have:

```
$ ./install.py
-- The C compiler identification is GNU 5.3.0
-- The CXX compiler identification is GNU 5.3.0
-- Check for working C compiler: /home/xwang95/.linuxbrew/bin/cc
-- Check for working C compiler: /home/xwang95/.linuxbrew/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/xwang95/.linuxbrew/bin/c++
-- Check for working CXX compiler: /home/xwang95/.linuxbrew/bin/c++ -- works
```

which means that gcc is the linuxbrew version of gcc... i'm a little bit confused now...

**Comment by sjackman** [comment]
Ah, that's definitely a bug. Can you submit an issue? The workaround is
```sh
brew sh --cc=gcc-5
```
