### ISSUE TITLE
ghc: Haskell is broken in Linuxbrew (due to MacOS-specific formula)

### ISSUE THREAD

**Issue by oneillkza** [Homebrew/linuxbrew#143]
I was trying to install pandoc, which depends on ghc, but ghc failed to install. Looking at the ghc.rb formula file, it seems that there are a whole ton of rules specifically related to MacOSX, and the result is that the formula tries to download and run a Mac binary!

**Comment by tinyheero** [comment]
Hi,

Has there been any updates on this issue? I am also trying to install pandoc through linuxbrew and running into issues. I've followed the instructions found at https://github.com/Homebrew/linuxbrew/wiki/Standalone-Installation to do a stand-alone installation of linuxbrew. 

When doing the pandoc installation, it tries to build the ghc. The brew gist-logs ghc can be found here: https://gist.github.com/anonymous/2dc0f3866d308936e210

Thanks,

**Comment by sjackman** [comment]
> checking for path to top of build tree... utils/ghc-pwd/dist-install/build/tmp/ghc-pwd: error while loading shared libraries: libgmp.so.3: cannot open shared object file: No such file or directory

It looks as though gmp is not installed. Please report the output of `brew install gmp`.

**Comment by tinyheero** [comment]
When running `brew install gmp`, I get the message `Warning: gmp-6.0.0a already installed` Seems that it may not see it?

**Comment by saketkc** [comment]
I  can reproduce this error. 
```
> ls -1 ~/.linuxbrew/lib/libgmp*
lib/libgmp.a
lib/libgmp.so
lib/libgmp.so.10
lib/libgmp.so.10.2.0
lib/libgmpxx.a
lib/libgmpxx.so
lib/libgmpxx.so.4
lib/libgmpxx.so.4.4.0
```

**Comment by sjackman** [comment]
Try `ln -s libgmp.so.10 ~/.linuxbrew/lib/libgmp.so.3`

**Comment by tinyheero** [comment]
Got a little further with that symlink set. But ran into an another set of errors.

```
make[1]: *** Waiting for unfinished jobs....
utils/haddock/doc/ghc.mk:15: recipe for target 'utils/haddock/doc/haddock.pdf' failed
make[1]: *** [utils/haddock/doc/haddock.pdf] Error 1
Makefile:71: recipe for target 'all' failed
make: *** [all] Error 2
```

Gist log can be found here: https://gist.github.com/anonymous/6968396933730f9e275c

**Comment by tinyheero** [comment]
Issue seems to be related the step where it calls `/usr/bin/dblatex` which tries to import dbtexmf.dblatex. Seems like someone else has run into this [issue](https://blog.lnx.cx/2009/12/04/installing-dblatex-from-the-latest-macports/). 

Seems like we need to install python and get this python library installed.

**Comment by tinyheero** [comment]
I finally got the ghc installation completed. I did a `brew install python && pip install dblatex && brew install ghc`

**Comment by sjackman** [comment]
Which host package provides `dblatex`? Please report `dblatex --version`. You might try `brew install texlive`.

**Comment by sjackman** [comment]
Great! Glad to hear it. Please disregard my previous comment.

**Comment by gitfoxi** [comment]
Do you really think this issue is closed?

**Comment by gitfoxi** [comment]
This is what I get:

```
checking for path to top of build tree... utils/ghc-pwd/dist-install/build/tmp/ghc-pwd: error while loading shared libraries: libgmp.so.10: cannot open shared object file: No such file or directory
configure: error: cannot determine current directory
```

It maddeningly rebuilds gmp for 15 minutes then loses track of it (and also the gmp that I have installed) and gives this message on running `./configure` for ghc.

**Comment by gitfoxi** [comment]
ghc depends on newer glibc:

```
[m@vm ghc-7.10.1]$ export LD_LIBRARY_PATH=/home/m/.linuxbrew/lib
[m@vm ghc-7.10.1]$ ./configure
checking for path to top of build tree... utils/ghc-pwd/dist-install/build/tmp/ghc-pwd: /lib64/libc.so.6: version `GLIBC_2.6' not found (required by libraries/unix/dist-install/build/libHSunix-2.7.1.0-G4Yo1pNtYrk8nCq1cx8P9d-ghc7.10.1.so)
utils/ghc-pwd/dist-install/build/tmp/ghc-pwd: /lib64/libc.so.6: version `GLIBC_2.11' not found (required by libraries/unix/dist-install/build/libHSunix-2.7.1.0-G4Yo1pNtYrk8nCq1cx8P9d-ghc7.10.1.so)
utils/ghc-pwd/dist-install/build/tmp/ghc-pwd: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by libraries/base/dist-install/build/libHSbase-4.8.0.0-I5BErHzyOm07EBNpKBEeUv-ghc7.10.1.so)
configure: error: cannot determine current directory
```

**Comment by sjackman** [comment]
You can use the [Standalone Installation](https://github.com/Homebrew/linuxbrew/wiki/Standalone-Installation) instructions to install recent version of glibc.

**Comment by gitfoxi** [comment]
I've been working through Standalone Installation. It's really tricky to get it right, fraught with restarts but hopefully getting close ...

**Comment by sjackman** [comment]
The standalone installation is now much simpler and totally automatic!
