### ISSUE TITLE
fontconfig: errors when compiling documentation

### ISSUE THREAD

**Issue by cbeck88** [Homebrew/linuxbrew#164]
I'm running Linux Mint 17 (Qiana), I installed linuxbrew by following the instructions here: https://www.digitalocean.com/community/tutorials/how-to-install-and-use-linuxbrew-on-a-linux-vps

Then to bypass the X11 issue I applied a simplified version of this PR:

https://github.com/Homebrew/linuxbrew/pull/64

(my version: https://gist.github.com/cbeck88/1730313897b1562f3488)

I was able to build many targets successfully, however I failed at fontconfig.
On running `brew install fontconfig`, I halt with link errors.

The issue seems to be that it's not finding lib png:
/usr/bin/ld: warning: libpng16.so.16, needed by /home/chris/.linuxbrew/opt/freetype/lib/libfreetype.so, not found (try using -rpath or -rpath-link)

I then get a bunch of unresolved symbols.

Full error log here:
https://gist.github.com/cbeck88/884f7f6d20415a8d7a1e

Any support would be appreciated, thanks.

**Comment by dlukes** [comment]
Concerning the pango issue -- I found [this](https://bugs.freedesktop.org/show_bug.cgi?id=75652):

> Freetype requires Harfbuzz's freetype backend, but Harfbuzz needs Freetype to build the Harfbuzz backend.

The solution being (it worked for me):

> Yes, the chicken-and-egg problem is unfortunate.  Behdad told me he is going to split HarfBuzz into two libraries (or something like that) to avoid this issue.

> For the moment, please do

>    ./configure --without-harfbuzz

> then build and install FreeType.  Then build and install HarfBuzz, then for FreeType do

>    make distclean
>    ./configure

> and build and install FreeType again.

Whew, after spending half a day tracking Emacs dependencies for a custom install on a server where I don't have root privileges, I might take a look at linuxbrew myself :)

**Comment by sjackman** [comment]
Thanks for the info, David. That's helpful.
