### ISSUE TITLE
Unable to bootstrap gcc

### ISSUE THREAD

**Issue by scmccoy** [Homebrew/linuxbrew#171]
I followed the help on #137 but didn't have the same luck. 
From brew doctor:
Warning: An outdated version of Git was detected in your PATH.
Git 1.7.10 or newer is required to perform checkouts over HTTPS from GitHub.
Please upgrade: brew upgrade git

-bash-4.1$ brew upgrade git
Error: git not installed

Then:
-bash-4.1$ brew install git
Error: The Homebrew GCC was not installed.
You must:
  brew install gcc

Then:
-bash-4.1$ brew install gcc
==> Installing dependencies for gcc: gmp, mpfr, libmpc, isl, cloog
==> Installing gcc dependency: gmp
Error: The Homebrew GCC was not installed.
You must:
  brew install gcc

I did try these from #137:

-bash-4.1$ prefix=~/.linuxbrew
-bash-4.1$ ln -s /usr/bin/gcc $prefix/bin/gcc-4.4
-bash-4.1$ ln -s /usr/bin/g++44 $prefix/bin/g++-4.4
-bash-4.1$ ln -s /usr/bin/gfortran44 $prefix/bin/gfortran-4.4
-bash-4.1$ export HOMEBREW_CC=gcc-4.4
-bash-4.1$ brew install hello && brew test -v hello; brew remove hello
==> Downloading http://ftpmirror.gnu.org/hello/hello-2.9.tar.gz
###### ################################################################## 100.0%

==> ./configure --disable-silent-rules --prefix=/var/www/vhosts/new-scmccoy.com/
--disable-dependency-tracking
--disable-silent-rules
--prefix=/var/www/vhosts/new-scmccoy.com/.linuxbrew/Cellar/hello/2.9

Failed to execute: ./configure

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Error: No such keg: /var/www/vhosts/new-scmccoy.com/.linuxbrew/Cellar/hello

Any thoughts were to go from here?
many thanks! 
shane

**Comment by dpc** [comment]
@sjackman : I don't want to report another issue for this, but my Fedora 22 sudenly broke linuxbrew.

I was following the instructions here, and they were not working. Finally I've discovered that this:

https://github.com/Homebrew/linuxbrew/wiki/Standalone-Installation#create-symlinks-for-gcc

does not work correctly if the ccache is installed. `ccache` package on F22 seem to quietly overtake `gcc` binary in the PATH, and then it will report version 4.9, but won't be able to find gcc-4.9 when launched under that name (via symlink created here https://github.com/Homebrew/linuxbrew/wiki/Standalone-Installation#create-symlinks-for-gcc ).

**Comment by sjackman** [comment]
Thanks for the heads up.
