### ISSUE TITLE
To install this formula, you may need to: brew install gcc

### ISSUE THREAD

**Issue by rampatra** [Homebrew/linuxbrew#191]
When i run `brew install gcc`, i get the following error:

``` shell
==> Installing dependencies for gcc: gmp, mpfr, libmpc, isl, cloog
==> Installing gcc dependency: gmp
Error: gmp cannot be built with any available compilers.
To install this formula, you may need to:
  brew install gcc
```

Please state where I am going wrong or is there an issue with **linuxbrew**?

**Comment by bluemix** [comment]
for me, running Fedora 22, I solved this problem after doing the installation steps in http://brew.sh/linuxbrew/#installation, them I did:
`````export HOMEBREW_CC=gcc```

**Comment by lovexiaov** [comment]
Thanks a lot for help me, it is worked~~

**Comment by sjackman** [comment]
Glad to hear it!

**Comment by guylifestyle3** [comment]
I am getting this and I think I tried most of the suggestions: $ brew install gcc
==> Installing dependencies for gcc: glibc, xz, gmp, mpfr, libmpc, isl
==> Installing gcc dependency: glibc
Error: The following formula:
  glibc
cannot be installed as a binary package and must be built from source.
Install Clang or brew install gcc

**Comment by sjackman** [comment]
Try these instructions to create a symlink for your compiler:
https://github.com/Linuxbrew/brew/wiki/Standalone-Installation#create-symlinks-for-gcc

**Comment by sjackman** [comment]
See https://github.com/Linuxbrew/brew/wiki/Symlink-GCC
