### ISSUE TITLE
brew install svn failed

### ISSUE THREAD

**Issue by huahang** [Homebrew/linuxbrew#21]
---

Libraries have been installed in:
   /home/huahang/.linuxbrew/Cellar/subversion/1.8.1/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
- add LIBDIR to the `LD_LIBRARY_PATH' environment variable
   during execution
- add LIBDIR to the `LD_RUN_PATH' environment variable
   during linking
- use the `-Wl,-rpath -Wl,LIBDIR' linker flag
- have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
## more information, such as the ld(1) and ld.so(8) manual pages.

==> Configuration
HOMEBREW_VERSION: 0.9.4
HEAD: f4e84917b419f4b5f16409d6d801357d5243625f
HOMEBREW_PREFIX: /home/huahang/.linuxbrew
CPU: quad-core 64-bit dunno
OS X: 0-x86_64
X11: N/A
==> ENV
CC: /usr/bin/gcc => /usr/bin/gcc-4.6
CXX: /usr/bin/g++ => /usr/bin/g++-4.6
CFLAGS: -Os -w -pipe -march=core2 -msse4
CXXFLAGS: -Os -w -pipe -march=core2 -msse4
CPPFLAGS: -I/home/huahang/.linuxbrew/opt/sqlite/include -I/home/huahang/.linuxbrew/opt/readline/include -isystem /home/huahang/.linuxbrew/include
LDFLAGS: -L/home/huahang/.linuxbrew/opt/sqlite/lib -L/home/huahang/.linuxbrew/opt/readline/lib -L/home/huahang/.linuxbrew/lib
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /home/huahang/.linuxbrew/opt/sqlite:/home/huahang/.linuxbrew/opt/readline:/home/huahang/.linuxbrew
PKG_CONFIG_PATH: /home/huahang/.linuxbrew/opt/sqlite/lib/pkgconfig
PKG_CONFIG_LIBDIR: /home/huahang/.linuxbrew/lib/pkgconfig:/usr/lib/pkgconfig
ACLOCAL_PATH: /home/huahang/.linuxbrew/share/aclocal
OBJC: /usr/bin/gcc
PATH: /home/huahang/.linuxbrew/opt/sqlite/bin:/home/huahang/.jenv/bin:/home/huahang/.linuxbrew/bin:/home/huahang/Applications/pidcat:/home/huahang/Applications/android-ndk-r8e:/home/huahang/Applications/android-sdk/platform-tools:/home/huahang/Applications/android-sdk/tools:/home/huahang/Applications/phabricator/arcanist/bin:/home/huahang/Applications/hadoop-2.0.0-mdh1.2.0-SNAPSHOT/bin:/zfs/Applications/jdk1.6.0_45/bin:/home/huahang/bin:/home/huahang/.jenv/bin:/home/huahang/.jenv/candidates/scala/current/bin:/home/huahang/.jenv/candidates/sbt/current/bin:/home/huahang/.jenv/candidates/maven/current/bin:/home/huahang/.jenv/candidates/java/current/bin:/home/huahang/.jenv/candidates/gradle/current/bin:/home/huahang/Applications/pidcat:/home/huahang/Applications/android-ndk-r8e:/home/huahang/Applications/android-sdk/platform-tools:/home/huahang/Applications/android-sdk/tools:/home/huahang/Applications/phabricator/arcanist/bin:/home/huahang/Applications/hadoop-2.0.0-mdh1.2.0-SNAPSHOT/bin:/zfs/Applications/jdk1.6.0_45/bin:/home/huahang/bin:/home/huahang/bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/home/huahang/.linuxbrew/Library/Contributions/cmd

**Comment by paulhybryant** [comment]
Hi,

I ran into exactly the same issue originally reported.
I didn't see anything related to keg-only in the formular.
And the library and binary do not existing in Cellar directory.

The gist log is here https://gist.github.com/anonymous/dff6ff729d44d1a85534

Thanks,

**Comment by sjackman** [comment]
https://gist.github.com/anonymous/dff6ff729d44d1a85534#file-05-make-L128-L133
```
libtool: warning: relinking 'libsvn_delta-1.la'
libtool: install: (cd /tmp/subversion-JCJW8L/subversion-1.8.11/subversion/libsvn_delta; /bin/bash "/tmp/subversion-JCJW8L/subversion-1.8.11/libtool"  --tag CC --silent --mode=relink /home/yu/.linuxbrew/bin/gcc-4.9 -Os -w -pipe -march=core2 -pthread -DNDEBUG -L/home/yu/.linuxbrew/lib -Wl,-rpath,/home/yu/.linuxbrew/lib -L/home/yu/.linuxbrew/Cellar/subversion/1.8.11/libexec/serf/lib -rpath /home/yu/.linuxbrew/Cellar/subversion/1.8.11/lib -version-info 0 -Wl,--no-undefined -o libsvn_delta-1.la cancel.lo compat.lo compose_delta.lo debug_editor.lo default_editor.lo deprecated.lo depth_filter_editor.lo editor.lo path_driver.lo svndiff.lo text_delta.lo version.lo xdelta.lo ../../subversion/libsvn_subr/libsvn_subr-1.la -L/home/yu/.linuxbrew/Cellar/apr-util/1.5.4/libexec/lib -laprutil-1 -L/home/yu/.linuxbrew/Cellar/apr/1.5.1/libexec/lib -lapr-1 -lz )
/usr/bin/ld: cannot find -lsvn_delta-1
collect2: error: ld returned 1 exit status
libtool:   error: error: relink 'libsvn_ra_serf-1.la' with the above command before installing it
make: *** [install-serf-lib] Error 1
```
