### ISSUE TITLE
libffi: glib does not find libffi

### ISSUE THREAD

**Issue by btjones16** [Homebrew/linuxbrew#212]
I ran `brew install glib`, and received the linker error "cannot find -lffi." It appears that the libraries are installed to "$(HOMEBREW_HOME)/Cellar/libffi/3.0.13/lib64", but the pkg-config file points to "$(HOMEBREW_HOME)/Cellar/libffi/3.0.13/lib". I updated line 9  of "$(HOMEBREW_HOME)/Cellar/libffi/3.0.13/lib/pkgconfig/libffi.pc" to read "Libs: -L${libdir}64 -lffi", and the problem disappeared. 

For details on the error, please see https://gist.github.com/anonymous/0d1e4ba8cbd79867a9ad.

My only concern with submitting a pull request is that I am not sure if that change to the pkg-config file will break the formulas for packages that link against libffi on other systems. The original formula worked fine on my mac. Please let me know if there are any further steps that I can take for fixing the formula.

**Comment by paulhybryant** [comment]
I run into the same issue.

Shouldn't a symlink libffi.so be created in .linuxbrew/lib for libffi.so.x.x.x?
