### ISSUE TITLE
gdal: unrecognized command line option ‘-arch’

### ISSUE THREAD

**Issue by brownbl1** [Homebrew/linuxbrew#218]
It does not seem like gdal has been effectively or fully ported to build with linuxbrew yet. There are still Mac specific flags being set that cause the build to error out. 

Starting on line 275 of the formula seems to be the beginning of the problem for those seeking to build on linux. What should these flags be set to in order to get this build working on linux? It appears that "-arch" is not a valid option for non-apple gcc.

In my tests, I've been doing a simple brew install gdal

**Comment by sureleo** [comment]
Hey, I tried install gdal yesterday but still the same issue. I modified line 275 and 293 it works fine. Can I make a pull request?

**Comment by sjackman** [comment]
@sureleo Yes, I'd merge a pull request to fix gdal.
