### ISSUE TITLE
cabal-install: failed to build

### ISSUE THREAD

**Issue by tinyheero** [Homebrew/linuxbrew#237]
Hi,

Trying to `brew install cabal-install` failed with the error `/usr/bin/ld: unrecognized option '-plugin'`

Gist log can be found here: https://gist.github.com/bda7650ba8f5916b81e8.

Should it be using the ~/.linuxbrew/bin/ld instead of /usr/bin/ld?

**Comment by tinyheero** [comment]
Issues seems to be that the linuxbrew gcc is not using the linuxbrew ld. Based on this [thread](http://ubuntuforums.org/showthread.php?t=711835), I did the following:

```
export COMPILER_PATH=~/.linuxbrew/bin
```

Following this, `brew install cabal-install` was successful

**Comment by sjackman** [comment]
Are you using a [Standalone Installation](https://github.com/Homebrew/linuxbrew/wiki/Standalone-Installation) of Linuxbrew? It builds GCC using [--with-build-time-tools](https://github.com/Homebrew/linuxbrew/blob/master/Library/Formula/gcc.rb#L108), but maybe that doesn't affect run time? In any case, thanks for the work around. Nice find.

**Comment by tinyheero** [comment]
Yes. I am using the standalone installation of linuxbrew which is why I was surprised it couldn't find the proper linker.

**Comment by sjackman** [comment]
That is odd. I haven't run into that issue. It may be an issue specific to `cabal-install`.

**Comment by sjackman** [comment]
Thanks for the bug report, Fong. I'm going to close this issue as wontfix, because I don't have the time to troubleshoot it. I'm glad that you found a workaround.
