### ISSUE TITLE
gcc: Standalone Installation of Linuxbrew fails

### ISSUE THREAD

**Issue by tinyheero** [Homebrew/linuxbrew#239]
Hi,

I was able to get this working yesterday using the same instructions found at https://github.com/Homebrew/linuxbrew/wiki/Standalone-Installation. But for whatever reason today, the step `brew install gcc --with-glibc -v` doesn't seem to want to complete even on the same machine now...

The gist log can be found here: https://gist.github.com/anonymous/af1d8f05a268c19f1cc0

Based on another (issue)[https://github.com/Homebrew/linuxbrew/issues/173], I thought maybe the solution was to re-build patchelf from source using `brew uninstall patchelf && brew install patchelf --build-from-source`. But it didn't work.

**Comment by tinyheero** [comment]
I was able to solve this issue with doing a `export HOMEBREW_BUILD_FROM_SOURCE=1` right from the beginning of the standalone installation. Looking back, it must be one of the bottles as mentioned https://github.com/Homebrew/linuxbrew/issues/173. I am also not sure which bottle it is.

**Comment by sjackman** [comment]
Thanks for the feedback. I'd be interested to know which bottle is causing the trouble, if you figure it out.

**Comment by sjackman** [comment]
`<built-in>: internal compiler error: Illegal instruction`

Ah, apparently I'm compiling for an instruction set that your machine does not support. I believe the default target machine is Intel Core2 `-march=core2`.
