### ISSUE TITLE
r: fails to install complaining about lack of X11

### ISSUE THREAD

**Issue by tinyheero** [Homebrew/linuxbrew#242]
Hi,

Trying to get R installed using linuxbrew by going:

```
brew tap homebrew/science
brew install r
```

But I end up getting an error `configure: error: --with-x=yes (default) and X11 headers/libs are not available`. Gist logs can be found here: https://gist.github.com/anonymous/88e66834c5d72c3fb4f2

Looking around on existing issues https://github.com/Homebrew/linuxbrew/issues/39, it seems that a solution may be to remove the dependency on X11? I would like to have R with X11. I know that the linux distribution that I am working with has X11 installed. For example:

```
find /usr -name 'libX11*'
/usr/lib64/libX11.so
/usr/lib64/libX11.so.6.2.0
find: `/usr/lib64/audit': Permission denied
/usr/lib64/libX11.so.6
/usr/lib/libX11.so
/usr/lib/libX11.so.6.2.0
/usr/lib/libX11.so.6
/usr/share/doc/libX11-1.0.3 
```

I am not sure how to proceed in getting linuxbrew to use these libraries? Any help would be appreciated. Thanks

**Comment by sjackman** [comment]
The workaround is to install R without X11: `brew install r --without-x11`

Try installing the X11 developer package using your host's package manager:
`sudo apt-get install xorg-dev`
