### ISSUE TITLE
git compilation fails

### ISSUE THREAD

**Issue by yawara** [Homebrew/linuxbrew#243]
I try to install Git using Linuxbrew because my brewdoctor says
```
Warning: An outdated version of Git was detected in your PATH.
Git 1.7.10 or newer is required to perform checkouts over HTTPS from GitHub.
Please upgrade: brew upgrade git
```

The compilation fails...build logs here
https://gist.github.com/anonymous/74e36821aed14f7da757

**Comment by sjackman** [comment]
`error: openssl/ssl.h: No such file or directory`

Try `brew install git --with-brewed-openssl`.
