### ISSUE TITLE
Separate, explicit mention of gcc symlinking needed?

### ISSUE THREAD

**Issue by dctrud** [Homebrew/linuxbrew#244]
Use case is linuxbrew for users to install software in homedirs on a shared HPC system running RHEL6/CentOS6. Lack of gcc-version symlink in OS gcc packages means brew won't install things until such a symlink is made. The symlink instructions are currently buried in the standalone installation page, leading to some people trying to follow the whole stand-alone procedure, which causes more confusion.

Should there be an explicit mention of just the symlinking for CentOS/RHEL on http://brew.sh/linuxbrew/ and README.md?

No pull request as I saw mention in some existing ssues of possible attempts to fix the gcc symlink problem in the installer / ruby... don't want to waste anyone's (or my) time if this is imminent.

**Comment by sjackman** [comment]
Yes, good idea. Linking was only necessary before if you wanted to override the default `/usr/bin/gcc` provided by your system, but I believe it's mandatory now on systems that don't provide a `/usr/bin/gcc-4.?` compiler. Debian does. I think Fedora and CentOS does not.

**Comment by dctrud** [comment]
Yes, mandatory on at least CentOS6/7 and Fedora20/21 that I've tried
recently. I can create a PR if wanted?

On Wednesday, January 14, 2015, Shaun Jackman <notifications@github.com>
wrote:

> Yes, good idea. Linking was only necessary before if you wanted to
> override the default /usr/bin/gcc provided by your system, but I believe
> it's mandatory now on systems that don't provide a /usr/bin/gcc-4.?
> compiler. Debian does. I think Fedora and CentOS does not.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Homebrew/linuxbrew/issues/244#issuecomment-70013218>.
>


-- 
Sent from Gmail Mobile

**Comment by sjackman** [comment]
Sure. The installer should handle this eventually, but updating docs is quicker.

**Comment by sjackman** [comment]
Fixed by 63b1cd37d84e6d1ce57d8a118edfa77e05d66162.
