### ISSUE TITLE
Create more man dirs 

### ISSUE THREAD

**Issue by miheerdew** [Homebrew/linuxbrew#247]
Hi,

I am not entirely sure of the issue here. I started with `ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/linuxbrew/go/install)"` and then a `brew install npm`. Everything was fine.

Then I did a `brew install ocaml`, however it failed in a link error  `File exists - ~/.linuxbrew/share/man/man3`

Unlinking `npm`, creating the directories ```~/.linuxbrew/share/man/man{2..8}``` and linking `npm` and `ocaml` again fixed the issue. Is this a correct way to do it?

**Comment by sjackman** [comment]
I really don't know what went wrong here, but based on your description, I'm going to guess that it's a bug in the `node` formula. I also think it's likely not specific to Linuxbrew, but affects Homebrew as well. I'm going to close this issue as wontfix. I'm glad that you found a workaround.

Note that `npm` is an alias for `node`. See https://github.com/Homebrew/homebrew/blob/master/Library/Formula/node.rb#L99-L102
