### ISSUE TITLE
Please disable Linuxbrew's Travis from emailing Homebrew committers

### ISSUE THREAD

**Issue by mikemcquaid** [Homebrew/linuxbrew#248]
Thanks!

**Comment by mikemcquaid** [comment]
Thanks @sjackman!

**Comment by mikemcquaid** [comment]
Still getting these.

**Comment by sjackman** [comment]
Sorry, Mike. I'm not receiving the emails any more. The `travis.yml` includes [`notifications: email: false`](https://github.com/Homebrew/linuxbrew/blob/master/.travis.yml#L13-L14). Can you post a snippet of the email that may help track down why you're still getting them?

**Comment by mikemcquaid** [comment]
Gist of the source: https://gist.github.com/mikemcquaid/01e7e009a3446deda275

**Comment by sjackman** [comment]
Okay. I sorted it out. I have a `homebrew` branch that tracks `homebrew/master`, and it doesn't have a `.travis.yml` file, hence also no `notifications: email: false` setting. I enabled `Build only if .travis.yml is present` at https://travis-ci.org/Homebrew/linuxbrew/settings.

**Comment by mikemcquaid** [comment]
Thanks!
