### ISSUE TITLE
python: get undefined symbol: PyUnicodeUCS2_FromUnicode

### ISSUE THREAD

**Issue by paulhybryant** [Homebrew/linuxbrew#257]
Adding `--enable-unicode=ucs4` in configure argument solved this (line 3 in the following)

```
    --prefix=#{prefix}
    --enable-ipv6
    --enable-unicode=ucs4
    --datarootdir=#{share}
    --datadir=#{share}
```

**Comment by sjackman** [comment]
Is the default `ucs2` then? Which Linux distribution are you using? I haven't run into this issue myself, so I won't merge this patch. If you like, you could submit a PR upstream to Homebrew that adds an option to switch between `ucs2` and `ucs4`.

**Comment by paulhybryant** [comment]
I am not sure what the default is. My OS is ubuntu trusty.

**Comment by sjackman** [comment]
I've used Linuxbrew on Trusty and haven't run into this issue myself.

**Comment by sjackman** [comment]
Are you using the Ubuntu Python package, or did you compile Python yourself?

**Comment by paulhybryant** [comment]
I think it is because of the python I have. Tried in another ubuntu and it installs fine. Thanks!
