### ISSUE TITLE
armv7l (Sailfish) support

### ISSUE THREAD

**Issue by Mikaela** [Homebrew/linuxbrew#260]
*I think I am on wrong issue tracker, but I am not fully sure and if I am please tell me and I will go to another one (homebrew?).*

I tried to install linuxbrew on Sailfish so I could install tmux more easily, but it gave me error message.

```
Sorry, Homebrew does not support your computer's CPU architecture.
For PPC support, see: https://github.com/mistydemeo/tigerbrew
```

However Sailfish doesn't differ so much from other Linux distributions and I was able to install tmux by myself with `pkcon install libcurses-devel libevent gcc` (and was there some other package?) and running `./configure && make && make install` and tmux seems to be running without issues.

Linuxbrew would also be nicer way to install some things I want, nothing more than tmux comes to mind currently though, but I am sure that there are more linuxbrew formulas than there are packages in pkcon or Warehouse.

**Comment by sjackman** [comment]
I have no plans to support ARM processors for now. Sorry. Feel free to submit a pull request if you do the porting work yourself.

**Comment by Mikaela** [comment]
What does it take if e.g. tmux compiles without linuxbrew without issues? Isn't everything compiled from source?

**Comment by sjackman** [comment]
Yes, everything is built fro source. Porting Linuxbrew to ARM is a manageable task. I just don't have the time to do it.

**Comment by Mikaela** [comment]
I thought that Ruby is platform-indepent or at least I haven't compiled anything or done anything else than git clone.

**Comment by sjackman** [comment]
Ruby is portable, but Homebrew is not. Homebrew and LInuxbrew currently only support Intel CPU.

**Comment by Mikaela** [comment]
Ah, I  see.

**Comment by sjackman** [comment]
I've added ARM support to Linuxbrew for the Raspberry Pi. I have a Raspberry Pi myself now. Happy hacking!
See 2077229dfdcc32559c80349080d8baf345ef42b9
