### ISSUE TITLE
Can't exec mosh-client Permission denied

### ISSUE THREAD

**Issue by usharf** [Homebrew/linuxbrew#265]
Getting this when trying to run `mosh`, which installed successfully.

```sh
Can't exec "/home/uri/.linuxbrew/Cellar/mobile-shell/1.2.4_2/bin/mosh-client": Permission denied at /home/uri/.linuxbrew/bin/mosh line 204.
Can't count colors: Permission denied
```

See maybe https://github.com/keithw/mosh/issues/281

**Comment by sjackman** [comment]
I believe that `mosh` is installed correctly and that this is a configuration issue.

**Comment by HorayNarea** [comment]
this problem is back with the update to mosh 1.2.5 (at least for me)
it's fixable by making mosh-client executable

**Comment by sjackman** [comment]
I can confirm that I see this issue as well. The files `mosh-client` and `mosh-server` are not executable. The workaround is
```sh
chmod +x `brew --prefix mosh`/bin/*
```
