### ISSUE TITLE
Scrollkeeper looks for only docbook 4.2 and 4.1.2 but docbook install only registered 5.0

### ISSUE THREAD

**Issue by paulhybryant** [Homebrew/linuxbrew#268]
In $HOME/.linuxbrew/etl/xml/catalog,
The following line exists after installing docbook
  <nextCatalog catalog="file:///usr/local/google/home/yuhuang/.linuxbrew/Cellar/docbook/5.0/docbook/xml/5.0/catalog.xml"/>

But scrollkeeper's configure is looking for only 4.2 and 4.1.2

**Comment by paulhybryant** [comment]
Forget it. This seems to be fixed. Reinstalling docbook and it works fine. Sorry...

**Comment by sjackman** [comment]
Thanks for the follow up.
