### ISSUE TITLE
nginx: Launchctl

### ISSUE THREAD

**Issue by compoundpaths** [Homebrew/linuxbrew#271]
To have launchd start nginx at login:
```
    mkdir -p ~/Library/LaunchAgents
    ln -sfv /home/ethan/.linuxbrew/opt/nginx/*.plist ~/Library/LaunchAgents
Then to load nginx now:
    launchctl load ~/Library/LaunchAgents/homebrew.mxcl.nginx.plist
Or, if you don't want/need launchctl, you can just run:
    nginx
```

all is well & good with the non-sudo nginx command, however, I am finding the LaunchAgent to be failing when rebooting the machine.  relatively new to linux, so I am not sure whether or not I am missing something obvious... should i even bother with nginx through linuxbrew?

**Comment by sjackman** [comment]
That message regarding launchctl is intended only for Mac OS. I've disabled this message for Linuxbrew now. You can definitely install nginx using Linuxbrew, but you'll have to read your distro's documentation to configure it to launch on startup.
