### ISSUE TITLE
/usr/local Installation with `brew` group permission?

### ISSUE THREAD

**Issue by ylluminate** [Homebrew/linuxbrew#276]
I run a few servers and would like to provide more *up-to-date* utilities server wide on this pain in the butt CentOS server.  The real solution, in my mind, is to operate similar to RVM wherein we would provide a `brew` user group and just add users to that who can / should be able to interact with brew itself, otherwise, if not in the `brew` group, they'd just install their own home based linuxbrew packages.  

Is there a method to do that presently or has it been considered in this regard previously?

**Comment by ylluminate** [comment]
I wonder if a temporary workaround would be to to install this as one of my admin accounts (not root) as per the normal process and then symlink it over to /opt/linuxbrew and subsequently add this path to user accounts via `/etc/profile.d/extrapaths.sh` and `/etc/zshenv`.  Going to fiddle a little here and see what works.

**Comment by saketkc** [comment]
I am not aware of any existing way to do this, but won't just sourcing the `~/.bashrc ` of the user who installed `linuxbrew` work?

**Comment by ylluminate** [comment]
So far so good:
```
sudo ln -s ~/.linuxbrew /opt/linuxbrew
sudo nano /etc/profile.d/path.sh
```
Add:
```
export PATH="/opt/linuxbrew/bin:$PATH"
export MANPATH="/opt/linuxbrew/share/man:$MANPATH"
export INFOPATH="/opt/linuxbrew/share/info:$INFOPATH"
```

Then `nano /etc/zshenv` and append:
```
export PATH="/opt/linuxbrew/bin:$PATH"
export MANPATH="/opt/linuxbrew/share/man:$MANPATH"
export INFOPATH="/opt/linuxbrew/share/info:$INFOPATH"
```

**Comment by sjackman** [comment]
Your solution looks good to me. The alternative would have been to give that one user permissions to write to `/opt/linuxbrew` and install Linuxbrew there.
