### ISSUE TITLE
Log location on Linux should be moved to be related to the linuxbrew folder

### ISSUE THREAD

**Issue by ylluminate** [Homebrew/linuxbrew#278]
While I understand the `~/Library/Logs` location for OS X, on Linux I believe that the location should be set differently.  To me it would more sense for it to be located within the linuxbrew folder under `log` or `var/log`.  

It doesn't appear that there is a documented setting for this `HOMEBREW_LOGS` variable as found in the `global.rb`.  I would have thought that that should be noted in the man page.

**Comment by sjackman** [comment]
Perhaps default `HOMEBREW_LOGS` to `$HOMEBREW_PREFIX/Library/Logs` on Linuxbrew?

**Comment by sjackman** [comment]
I've change the defalt log directory to ~/.cache/Homebrew/Logs
