### ISSUE TITLE
ossp-uuid conflicts with libuuid

### ISSUE THREAD

**Issue by paulhybryant** [Homebrew/linuxbrew#281]
The package is installed fine but the symlink to the binary "uuid" is not created.
Is this intended?

Thanks,

**Comment by sjackman** [comment]
Do you also have `libuuid` installed? Can you report the output of
```sh
brew install ossp-uuid
brew link ossp-uuid
which uuid
uuid
```

**Comment by paulhybryant** [comment]
Yes, I also have libuuid installed.

brew link uuid says

"Could not symlink lib/libuuid.a"

brew link --overwrite ossp-uuid works.

Is there any concern for overwriting the symlink? or they are the same thing?

Thanks,

**Comment by sjackman** [comment]
I'd suggest
```sh
brew unlink libuuid ossp-uuid
brew link ossp-uuid
brew link --force libuuid
```

Cheers,
Shaun
