### ISSUE TITLE
pkg-config issues

### ISSUE THREAD

**Issue by ylluminate** [Homebrew/linuxbrew#283]
I just experienced an interesting issue wherein `pkg-conf` did not pick up the system libcurl libraries and was hopeful that someone could enlighten me as to how we might properly address this behavior perhaps better than the way that I resolved the problem:
https://github.com/phusion/passenger/issues/1355#issuecomment-73828653

My main goal is to not have this happen again and so it would be good to understand what is happening and how to get `pkg-config` working properly in relation to the *system* `pkg-config` and what it is detecting, vs what the *linuxbrew* `pkg-config` is and is not detecting, etc.

**Comment by sjackman** [comment]
The solution, I believe, is to set the `PKG_CONFIG_PATH` environment variable to include both the system paths and the Linuxbrew paths. The default, I believe, is to include just the Linuxbrew paths.
