### ISSUE TITLE
cmake: depends on curl and libedit

### ISSUE THREAD

**Issue by captain-awesome** [Homebrew/linuxbrew#288]
I am a newbie at this and am trying to follow the Lynda.com Ruby on Rails Essential DVD but it only covers how to install Rails on Mac and Windows.

I'm attempting to install Rails on Ubuntu 14.04.

The tutorial uses Homebrew, I've installed Linuxbrew.

https://gist.github.com/anonymous/3c792139aac3f26e3d08

Any help will be appreciated.

Thanks

**Comment by sjackman** [comment]
I don't actually see any errors in that gist. What error are you seeing?

**Comment by captain-awesome** [comment]
Thanks for your reply sjackman.

I am a newbie at this and am trying to follow the Lynda.com Ruby on Rails Essential DVD but they only cover how to install Rails on Mac and Windows.

I'm attempting to install Rails on Ubuntu 14.04.
The tutorial uses Homebrew, I've install Linuxbrew.

Whenever I execute "brew install mysql" it returns the following:

--------------------------------------------------------------------------------------------------------
lucius@localhost:~$ brew install mysql
==> Installing mysql dependency: cmake

==> Downloading http://www.cmake.org/files/v3.1/cmake-3.1.2.tar.gz
Already downloaded: /home/lucius/.cache/Homebrew/cmake-3.1.2.tar.gz

==> Downloading https://pypi.python.org/packages/source/S/Sphinx/Sphinx-1.2.3.ta
Already downloaded: /home/lucius/.cache/Homebrew/cmake--sphinx-1.2.3.tar.gz

==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/cmake-OFC

==> Downloading https://pypi.python.org/packages/source/d/docutils/docutils-0.12
Already downloaded: /home/lucius/.cache/Homebrew/cmake--docutils-0.12.tar.gz

==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/cmake-OFC

==> Downloading https://pypi.python.org/packages/source/P/Pygments/Pygments-2.0.
Already downloaded: /home/lucius/.cache/Homebrew/cmake--pygments-2.0.2.tar.gz

==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/cmake-OFC

==> Downloading https://pypi.python.org/packages/source/J/Jinja2/Jinja2-2.7.3.ta
Already downloaded: /home/lucius/.cache/Homebrew/cmake--jinja2-2.7.3.tar.gz

==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/cmake-OFC

==> Downloading https://pypi.python.org/packages/source/M/MarkupSafe/MarkupSafe-
Already downloaded: /home/lucius/.cache/Homebrew/cmake--markupsafe-0.23.tar.gz

==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/cmake-OFC

==> ./bootstrap --prefix=/home/lucius/.linuxbrew/Cellar/cmake/3.1.2 --system-lib

==> make
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libcurl.so: undefined reference to `SSL_get_peer_certificate@OPENSSL_1.0.0'

collect2: error: ld returned 1 exit status

make[2]: *** [bin/ccmake] Error 1

make[1]: *** [Source/CMakeFiles/ccmake.dir/all] Error 2

make: *** [all] Error 2

--------------------------------------------------------------------------------------------------------

My apologies for not including this.

Thanks

**Comment by sjackman** [comment]
`brew install curl mysql` may resolve your issue.

**Comment by captain-awesome** [comment]
sjackman, I ran your command.
Please see my pastebin post here: http://pastebin.com/y5nFvtCr (I didn't want to clutter this thread)

**Comment by sjackman** [comment]
Try `brew install curl readline cmake mysql`

**Comment by captain-awesome** [comment]
Hi sjackman,

I received the following:

lucius@localhost:~$ brew install curl readline cmake mysql
Warning: curl-7.40.0 already installed
Warning: readline-6.3.8 already installed
Warning: cmake-3.1.2 already installed
==> Downloading http://cdn.mysql.com/Downloads/MySQL-5.6/mysql-5.6.22.tar.gz
Already downloaded: /home/lucius/.cache/Homebrew/mysql-5.6.22.tar.gz
==> Downloading https://github.com/mysql/mysql-server/pull/3.diff
Already downloaded: /home/lucius/.cache/Homebrew/mysql--patch-6b17a31ee32e373dca                                                      0f257f7c7884ac6dcf8e1f.diff
==> Patching
patching file cmake/ssl.cmake
==> cmake . -DCMAKE_INSTALL_PREFIX=/home/lucius/.linuxbrew/Cellar/mysql/5.6.22 -


-- Configuring incomplete, errors occurred!
See also "/tmp/mysql-YrTRQW/mysql-5.6.22/CMakeFiles/CMakeOutput.log".
See also "/tmp/mysql-YrTRQW/mysql-5.6.22/CMakeFiles/CMakeError.log".

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

These open issues may also help:
mysql-connector-c++ cannot build with mariadb  (https://github.com/Homebrew/homebrew/issues/34578)
mysql failed to build on 10.10 (https://github.com/Homebrew/homebrew/issues/33448)
Packages with --with-mysql option not satisfied by mariadb (https://github.com/Homebrew/homebrew/issues/32973)

**Comment by sjackman** [comment]
Run `brew gist-logs mysql`

See the [troubleshooting guide](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#read-this-first).

**Comment by captain-awesome** [comment]
https://gist.github.com/6b279259cceaad4940a2

**Comment by sjackman** [comment]
https://gist.github.com/anonymous/6b279259cceaad4940a2#file-01-cmake-L754-L759
```
-- EDITLINE_INCLUDE_DIR 
-- EDITLINE_LIBRARY EDITLINE_LIBRARY-NOTFOUND
CMake Error at cmake/readline.cmake:206 (MESSAGE):
  Cannot find system editline libraries.
Call Stack (most recent call first):
  CMakeLists.txt:406 (MYSQL_CHECK_EDITLINE)
```

**Comment by sjackman** [comment]
Oh, my mistake. I thought `libedit` was provided by `readline`. It's not. It's provided by `libedit`.

Try `brew install curl libedit cmake mysql`

**Comment by captain-awesome** [comment]
after running that command:

lucius@localhost:~$ brew install curl libedit cmake mysql
Error: No available formula for libedit
Searching formulae...
Searching taps...
homebrew/dupes/libedit

**Comment by sjackman** [comment]
Try `brew install curl homebrew/dupes/libedit cmake mysql`

**Comment by sjackman** [comment]
Please surround copy-and-pasted text with triple backticks like so:

    ```
    text
    here
    ```

**Comment by sjackman** [comment]
See [Markdown Basics](https://help.github.com/articles/markdown-basics/) on GitHub Help for more info.

**Comment by captain-awesome** [comment]
I received the following:
```
lucius@localhost:~$ brew install curl homebrew/dupes/libedit cmake mysql
Warning: curl-7.40.0 already installed
Warning: libedit-3.1 already installed
Warning: cmake-3.1.2 already installed
==> Downloading http://cdn.mysql.com/Downloads/MySQL-5.6/mysql-5.6.22.tar.gz
Already downloaded: /home/lucius/.cache/Homebrew/mysql-5.6.22.tar.gz
==> Downloading https://github.com/mysql/mysql-server/pull/3.diff
Already downloaded: /home/lucius/.cache/Homebrew/mysql--patch-6b17a31ee32e373dca0f257f7c7884ac6dcf8e1f.diff
==> Patching
patching file cmake/ssl.cmake
==> cmake . -DCMAKE_INSTALL_PREFIX=/home/lucius/.linuxbrew/Cellar/mysql/5.6.22 -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -DMYSQ
==> make
==> make install
==> Caveats
A "/etc/my.cnf" from another install may interfere with a Homebrew-built
server starting up correctly.

To connect:
    mysql -uroot

==> /home/lucius/.linuxbrew/Cellar/mysql/5.6.22/bin/mysql_install_db --verbose --user=lucius --basedir=/home/lucius/.linuxbrew/Cellar/mysql/5
Installing MySQL system tables...2015-03-06 16:11:45 0 [Warning] Using unique option prefix key_buffer instead of key_buffer_size is deprecated and will be removed in a future release. Please use the full name instead.
2015-03-06 16:11:45 0 [Warning] Ignoring user change to 'lucius' because the user was set to 'mysql' earlier on the command line

2015-03-06 16:11:45 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2015-03-06 16:11:45 7643 [ERROR] Can't find messagefile '/usr/share/mysql/errmsg.sys'
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall mysql`
==> Summary
/home/lucius/.linuxbrew/Cellar/mysql/5.6.22: 9667 files, 350M, built in 17.3 minutes
lucius@localhost:~$ mysql -uroot
mysql: error while loading shared libraries: libedit.so.0: cannot open shared object file: No such file or directory
```

The warning states"
```
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall mysql`
```

I received the following:
```

lucius@localhost:~$ brew postinstall mysql
==> /home/lucius/.linuxbrew/Cellar/mysql/5.6.22/bin/mysql_install_db --verbose --user=lucius --basedir=/home/lucius/.linuxbrew/Cellar/mysql/5
Installing MySQL system tables...2015-03-06 16:16:46 0 [Warning] Using unique option prefix key_buffer instead of key_buffer_size is deprecated and will be removed in a future release. Please use the full name instead.
2015-03-06 16:16:46 0 [Warning] Ignoring user change to 'lucius' because the user was set to 'mysql' earlier on the command line

2015-03-06 16:16:46 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2015-03-06 16:16:46 7868 [ERROR] Can't find messagefile '/usr/share/mysql/errmsg.sys'

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

These open issues may also help:
mysql-connector-c++ cannot build with mariadb  (https://github.com/Homebrew/homebrew/issues/34578)
mysql failed to build on 10.10 (https://github.com/Homebrew/homebrew/issues/33448)
Packages with --with-mysql option not satisfied by mariadb (https://github.com/Homebrew/homebrew/issues/32973)

```

**Comment by sjackman** [comment]
I'm glad you have MySQL installed. You've reached the end of my knowledge here. To configure MySQL you're on your own. Good luck!

**Comment by captain-awesome** [comment]
Thank you for your assistance

**Comment by shnode** [comment]
@sjackman Nice solution for `brew install curl homebrew/dupes/libedit cmake mysql`，this also worked for mariadb installation error which reproduced in #36126.

in my enviroment, after installed the `curl`, `libedit`, `cmake`, terminal should be restart for the next step.
