### ISSUE TITLE
Doxygen missing dependencies

### ISSUE THREAD

**Issue by WestFlame** [Homebrew/linuxbrew#289]
To brew doxygen I had to install "flex" and "bizon" through system package manager. Otherwise the configure script complained that these are not found (Ubuntu 14.04, 64bit).

**Comment by sjackman** [comment]
Linuxbrew assumes that all software provided by Mac OS is already installed on your system. You may install that software using the native package manager or using Linuxbrew from the Homebrew/dupes tap.
