### ISSUE TITLE
pxz: undefined reference to `lzma_code'

### ISSUE THREAD

**Issue by bukzor** [Homebrew/linuxbrew#293]
I'd think this means it's either including the wrong header or linking the wrong library, but I can't see any reason that might be.

https://gist.github.com/bukzor/ca7d5a5710c94f3822d8

**Comment by sjackman** [comment]
The error is in the link command line. The linked libraries `-l` must come *after* the source files. `-llzma pxz.c -o pxz` should be `pxz.c -o pxz -llzma`. 
```
/usr/bin/gcc-4.8 -Wall -Wshadow -Wcast-align -Wunreachable-code -Winline -Wextra -Wmissing-noreturn  -Os -w -pipe -march=core2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DPXZ_BUILD_DATE=\"`date +%Y%m%d`\" -DPXZ_VERSION=\"4.999.9beta\" -O2 -fopenmp -L/home/buck/prefices/brew/lib -Wl,-rpath,/home/buck/prefices/brew/lib -llzma pxz.c -o pxz
```

**Comment by sjackman** [comment]
Please report this bug to the upstream author of the software.

**Comment by bukzor** [comment]
Shouldn't we find just the same bug on osx?
Is this different between clang/gcc?

**Comment by sjackman** [comment]
On OS X the linker allows the `-l` command line options to precede the source files. On Linux it does not.
