### ISSUE TITLE
GCC Fails to Build on Chromebook

### ISSUE THREAD

**Issue by bnied** [Homebrew/linuxbrew#296]
Following https://github.com/Homebrew/linuxbrew/wiki/Chromebook-Install-Instructions, I get to the GCC step before building fails:

    /usr/local/linuxbrew/Cellar/binutils/2.25/x86_64-unknown-linux-gnu/bin/ld: cannot find crti.o: No such file or directory
    /usr/local/linuxbrew/Cellar/binutils/2.25/x86_64-unknown-linux-gnu/bin/ld: cannot find /usr/lib64/libc_nonshared.a
    collect2: error: ld returned 1 exit status
    make[3]: *** [libgcc_s.so] Error 1
    make[3]: Leaving directory `/usr/local/linuxbrew/tmp/gcc-IaGjEg/gcc-4.9.2/build/x86_64-unknown-linux-gnu/libgcc'
    make[2]: *** [all-stage1-target-libgcc] Error 2
    make[2]: Leaving directory `/usr/local/linuxbrew/tmp/gcc-IaGjEg/gcc-4.9.2/build'
    make[1]: *** [stage1-bubble] Error 2
    make[1]: Leaving directory `/usr/local/linuxbrew/tmp/gcc-IaGjEg/gcc-4.9.2/build'
    make: *** [bootstrap] Error 2
    ==> Configuration
    HOMEBREW_VERSION: 0.9.5
    ORIGIN: https://github.com/Homebrew/linuxbrew.git
    HEAD: b2d76c5a442ff6490ca8390e88d1d07f05fd4813
    Last commit: 5 days ago
    HOMEBREW_PREFIX: /usr/local/linuxbrew
    HOMEBREW_CELLAR: /usr/local/linuxbrew/Cellar
    CPU: dual-core 64-bit 6
    OS X: 0-x86_64
    Xcode: N/A
    CLT: N/A
    Clang: N/A
    X11: N/A
    System Ruby: 2.0.0-p247 => /usr/local/bin/ruby
    Perl: /usr/local/bin/perl
    Python: /usr/local/bin/python => /usr/local/bin/python3.3
    Ruby: /usr/local/bin/ruby
    Java: N/A
    ==> ENV
    CC: /usr/local/linuxbrew/bin/gcc-4.8 => /usr/local/bin/gcc
    CXX: /usr/local/linuxbrew/bin/g++-4.8 => /usr/local/bin/g++
    OBJC: /usr/local/linuxbrew/bin/gcc-4.8
    OBJCXX: /usr/local/linuxbrew/bin/g++-4.8
    CFLAGS: -Os -w -pipe -march=core2
    CXXFLAGS: -Os -w -pipe -march=core2
    CPPFLAGS: -isystem/usr/local/linuxbrew/include
    LDFLAGS: -L/usr/local/linuxbrew/lib -Wl,--dynamic-linker=/usr/local/linuxbrew/opt/glibc/lib/ld-linux-x86-64.so.2 -Wl,-rpath,/usr/local/linuxbrew/lib
    MAKEFLAGS: -j2
    CMAKE_PREFIX_PATH: /usr/local/linuxbrew
    PKG_CONFIG_LIBDIR: /usr/local/linuxbrew/lib/pkgconfig
    PATH: /usr/local/linuxbrew/bin:/usr/local/linuxbrew/sbin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/local/linuxbrew/Library/Taps/homebrew/homebrew-boneyard/cmd:/usr/local/linuxbrew/Library/ENV/scm

    Error: gcc 4.9.2 did not build
    Logs:
         /home/chronos/user/Library/Logs/Homebrew/gcc/02.make
         /home/chronos/user/Library/Logs/Homebrew/gcc/01.configure

    These open issues may also help:
    gcc -v fails with gcc: warning: couldn't understand kern.osversion '14.1.0 Using built-in specs. (https://github.com/Homebrew/homebrew/issues/36944)
    Object files deleted during build of gcc needed by gdb (https://github.com/Homebrew/homebrew/issues/35734)
    gcc 4.9.2 fails to produce debugging information (https://github.com/Homebrew/homebrew/issues/34976)
    --cc=gcc-4.9 gets me in an infinite loop (https://github.com/Homebrew/homebrew/issues/33731)
    MacOS.(gcc|clang|llvm)_version can return nil (https://github.com/Homebrew/homebrew/issues/18781)

Chromebook is Toshiba Chromebook 2.

**Comment by bnied** [comment]
Apologies; I didn't read the instructions clearly enough to see the note about the pull request.

**Comment by sjackman** [comment]
No worries. Did you find a resolution to your issue?

**Comment by bnied** [comment]
I did. I merged the changes from the pull request into the latest linuxbrew package manifests and everything installed successfully.

Thank you for the followup!
