### ISSUE TITLE
vim depends on ncurses

### ISSUE THREAD

**Issue by martinwolf** [Homebrew/linuxbrew#302]
Hey,

I've tried to install vim with linux brew but it didn't work. Here is the log:
https://gist.github.com/anonymous/2211356fab25828d7175

```
which ruby
~/.linuxbrew/bin/ruby
```

```
ruby --version
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
```

Hope someone can help.

Cheers!

**Comment by sjackman** [comment]
https://gist.github.com/anonymous/2211356fab25828d7175#file-02-make-L154-L155
```
objects/term.o: In function `out_str':
term.c:(.text+0x14b8): undefined reference to `tputs'
```

**Comment by sjackman** [comment]
Run
```sh
brew install ncurses
ln -s ncursesw/curses.h ncursesw/ncurses.h ncursesw/term.h ncursesw/termcap.h ~/.linuxbrew/include/
ln -s libncurses.a ~/.linuxbrew/lib/libcurses.a
ln -s libncurses.so ~/.linuxbrew/lib/libcurses.so
```

See https://github.com/Homebrew/homebrew-dupes/pull/422 and [Standalone installation instructions](https://github.com/Homebrew/linuxbrew/wiki/Standalone-Installation)

**Comment by martinwolf** [comment]
Hey! Thanks, but not sure what that means:

```
> brew install ncurses
Error: No available formula for ncurses
```

**Comment by sjackman** [comment]
`brew tap homebrew/dupes`

**Comment by sjackman** [comment]
Did you see this message?
```
~ ❯❯❯ brew install ncurses
Error: No available formula for ncurses 
Searching formulae...
Searching taps...
homebrew/dupes/ncurses
```

**Comment by martinwolf** [comment]
```
brew tap homebrew/dupes
```

That helped. Awesome, everything's working now, thanks! :)

**Comment by sjackman** [comment]
Great. Glad that you got it working.
