### ISSUE TITLE
expect: error while loading shared libraries: libexpect5.45.so

### ISSUE THREAD

**Issue by paulhybryant** [Homebrew/linuxbrew#306]
One output from `brew link --verbose expect`

`ln -s ../Cellar/expect/5.45/lib/expect5.45 expect5.45`

libexpect5.4.5.so is not linked to lib and thus expect failed complaining the so file is not found.

**Comment by sjackman** [comment]
The executable `expect` is linked against `libexpect5.45.so`, which is installed in `lib/expect5.45/libexpect5.45.so` and not symlinked into `lib`.

**Comment by sjackman** [comment]
```
$ expect --version
expect: error while loading shared libraries: libexpect5.45.so: cannot open shared object file: No such file or directory
```

**Comment by sjackman** [comment]
This issue would be fixed by https://github.com/Homebrew/homebrew-dupes/pull/438
