### ISSUE TITLE
Warning: You have a non-Homebrew 'pkg-config' in your PATH

### ISSUE THREAD

**Issue by umbrar** [Homebrew/linuxbrew#308]
Hi,

I have Linux Mint 17.1, had to install Linuxbrew, everything seemed fine until I ran Brew Doctor.

I have the following error every time:

```
Warning: You have a non-Homebrew 'pkg-config' in your PATH:
  /usr/bin/pkg-config

`./configure` may have problems finding brew-installed packages using
this other pkg-config.
```

I've google searched for answers, everything I find is Mac-specific and when I try to use a version for Linux, the error is still there. I'm new to Linux and maybe I just don't know the correct vocabulary to be using in the searches, but I looked through the titles of all the Linuxbrew issues here, as well as searching the repository and google, and none addressed this.

I've run brew update, and here's my brew config: https://gist.github.com/umbrar/849bdc3cdbfc11021188

Thanks in advance!

**Comment by sjackman** [comment]
Run `brew install pkg-config`. You may still see this warning, but you can safely ignore it.
