### ISSUE TITLE
Java Dependency Error

### ISSUE THREAD

**Issue by requnix** [Homebrew/linuxbrew#309]
I've encountered a problem with the Java dependency for a Formula that depends on Java.

The formula is `datomic.rb` and the problem seems to be trying to access `@java_home` at https://github.com/Homebrew/linuxbrew/blob/master/Library/Homebrew/requirements/java_dependency.rb#L11 which seems to be `nil`. Setting `ENV["JAVA_HOME"]` has no effect since it errors on that first line.

This code seems to be unchanged from Mac Homebrew as it checks for Apple's JVM (which can be ignored on Linux).

I managed to get the formula to run by setting `JAVA_HOME` and changing the `env` block to:

```ruby
env do
  java_home = Pathname.new(ENV["JAVA_HOME"])
  ENV.prepend_path "PATH", java_home/"bin"
  ENV.append_to_cflags "-I#{java_home}/include"
end
```

Although, I'm sure this is not the proper way to fix the issue it shows that the problem is simply one of `@java_home` not being set.

A recent issue (#305) addressed a similar problem with Java environment variables and may offer additional insight.

**Comment by sjackman** [comment]
Thanks for the helpful bug report.
