### ISSUE TITLE
Missing gvim

### ISSUE THREAD

**Issue by kiryph** [Homebrew/linuxbrew#311]
Installing vim with `$ brew install vim` does not build a gui version of vim (gvim).

Is it possible to add this? The macvim formula does not apply to Linux.

**Comment by sjackman** [comment]
Try `brew install vim --with-client-server`

The option to enable the GUI is named somewhat cryptically. See @dpo https://github.com/Homebrew/homebrew/commit/cf715c0e6611e7692c6e9df9bd0e12af5551b1eb#commitcomment-10226176

**Comment by dpo** [comment]
The `client-server` functionality in Vim has nothing to do with the GUI; it enables other programs to communicate with Vim (e.g., a PDF viewer). For some reason, I was never able to compile Vim with the client-server functionality enabled without also depending on GTK+.

**Comment by sjackman** [comment]
The only effect of `--with-client-server` that I can see is to enable the GUI.
```
❯❯❯ grep -A5 client-server vim.rb
  option "with-client-server", "Enable client/server mode"
…
  depends_on "gtk+" if build.with? "client-server"
…
    if build.with? "client-server"
      opts << "--enable-gui=gtk2"
    else
      opts << "--enable-gui=no"
      opts << "--without-x"
    end
```

**Comment by sjackman** [comment]
Does the client-server functionality get automatically built without a special configure option if the gtk+ dependency is satisfied?

**Comment by dpo** [comment]
Yes, that's exactly what's going on. Vim tries to enable the client-server functionality by default. Technically, it doesn't have anything to do with the gui, but back when I submitted the patch, I couldn't get it to be enabled in the final compiled executable unless vim also found gtk+.

**Comment by sjackman** [comment]
Thanks for clearing that up for me.

**Comment by kiryph** [comment]
Thanks for sharing all the details. The gtk+ version works. One minor glitch is that the scroll bar does visually not fit to the theme of the XFCE desktop I am on.

**Comment by sjackman** [comment]
Great! I'm glad you got it working. As for the scroll bar, you'll have to follow up on that issue with one of GTK+, XFCE, or VIM. I'm not sure which.

**Comment by 5hubh4m** [comment]
I built vim with `--with-client-server` on a remote server, however I'm still lost as to how do I launch the GUI. I `ssh`'ed with the `-X` option.

**Comment by sjackman** [comment]
Run the executable named `gvim`

**Comment by 5hubh4m** [comment]
There is no `gvim` in `~/.linuxbrew/bin`.

**Comment by sjackman** [comment]
Did you run `brew install vim --with-client-server` ?

**Comment by 5hubh4m** [comment]
Yes, to be exact, I did `brew reinstall vim --with-lua --with-override-system-vi --with-client-server`.

**Comment by sjackman** [comment]
Ah, it looks like support for GUI was dropped from the formula for some reason. You can check `git log vim` to find out why. I'd accept a PR to add support back. If you're adventurous, try `brew edit vim` and change `"--enable-gui=no"` to `"--enable-gui=gtk"` and add `depends_on "gtk+"` then run
```sh
brew install vim --with-lua --with-override-system-vi --with-client-server
```

**Comment by 5hubh4m** [comment]
I've been trying to install `gtk+3`, but the `systemd` build fails. I'll be trying this again soon though.

**Comment by sjackman** [comment]
We've just enabled `brew install --env=super` by default for users. If some packages fail to build with `--env=super` try `brew install --env=std systemd`. Please do open an issue if a formula fails to build with `--env=super` but builds fine with `--env=std`.
