### ISSUE TITLE
Reason why the prefix of Linuxbrew is not /usr/local

### ISSUE THREAD

**Issue by dalguji** [Homebrew/linuxbrew#312]
I am a fan of Homebrew and use it often on my mac. I am planning to use Linuxbrew also on my Ubuntu server so I can manage some packages that are not managed by apt-get well.

When I first installed Linuxbrew on my server, I was wondering why the default prefix is a user's own $HOME/.linuxbrew instead of /usr/local which makes all users can access the installed packages. I understand the prefix can be changed if I want but I guess there must be some reason why Linuxbrew is designed to have a different default prefix from what Homebrew has. Please advise.

(Apologies if this is not the right place to ask a question.  I couldn't find an answer from FAQ or elsewhere.)

**Comment by tseemann** [comment]
My guess would be that Brew is designed for Mac OS X, which is nearly always a single user machine where the owner has root/sudo access.

However, LinuxBrew is more likely to be on a shared server or cluster where any given user will not have root/sudo access, and therefore can not write to /usr/local

You can git clone linuxbrew into whichever folder you want.

**Comment by Mikaela** [comment]
> My guess would be that Brew is designed for Mac OS X, which is nearly always a single user machine where the owner has root/sudo access.

We have four users on OS X and I cannot understand brew, so I am using it like I use other package managers, as root.

```bash
# This might be a little dangerous command...
cd /usr;git clone https://github.com/Homebrew/homebrew.git;mkdir -p local;rsync -aP homebrew/* local;rsync -aP homebrew/.* local/;chmod -R 755 local;chown -R root:wheel local;rm -rf homebrew
```

> However, LinuxBrew is more likely to be on a shared server or cluster where any given user will not have root/sudo access, and therefore can not write to /usr/local

This is my guess too, but I could understand `/usr/local/` too as many distributions have quite outdated packages. Linuxbrew doesn't appear to be as reliable as Homebrew (yet) though.

Oh and I usually put linuxbrew to `$HOME/.local` and I have alias for that too.

```bash
# if ~/.local is empty this might be less dangerous
cd ~;git clone https://github.com/Homebrew/linuxbrew.git;mkdir -p .local;rsync -aP linuxbrew/* .local;rsync -aP linuxbrew/.* .local;rm -rf linuxbrew
```

I also have root installation alias, but I don't think it's any more safe than that OS X one earlier, `;` should probably be replaced with `&&` so it would at least stop if there is some kind of issue.

```bash
# also dangerous!
cd /usr;git clone https://github.com/Homebrew/linuxbrew.git;mkdir -p local;rsync -aP linuxbrew/* local;rsync -aP linuxbrew/.* local/;chmod -R 755 local;chown -R root:wheel local;rm -rf linuxbrew
```

**YOU RUN THE MENTIONED COMMANDS WITH YOUR OWN RESPONSIBILITY!**

**Comment by andreabedini** [comment]
my 2c, I totally support using `$HOME/.linuxbrew`. My use case is scientific HPC clusters that often run outdated versions of CentOS. With linuxbrew I am only a `brew install` away from a usable environment.

**Comment by sjackman** [comment]
`~/.linuxbrew` is the default to support users of servers that do not have write access to `/usr/local`. It's easier to support a single default value that works for everyone. If you do have write access to `/usr/local`, there's no reason why `git clone https://github.com/Homebrew/linuxbrew.git /usr/local` shouldn't work—given that you first delete the existing `/usr/local`. I haven't tested installing Linuxbrew to `/usr/local`, but it sure gets a lot of testing with Homebrew for Mac.

**Comment by tseemann** [comment]
The main thing is that ```/usr/local``` is "nearly" guaranteed to not be touched by Apple or apps.

However on Linux it's a free for all.
