### ISSUE TITLE
gettext: permission denied 

### ISSUE THREAD

**Issue by alfablac** [Homebrew/linuxbrew#313]
Trying to install using brew on a non-root server and I keep getting Permission denied errors. There's no way to use chown because I don't have root access. Is there any way to fix that?

```
==> Installing glib-networking dependency: gettext
==> Downloading http://ftpmirror.gnu.org/gettext/gettext-0.19.4.tar.xz
Already downloaded: /home/<username>/.cache/Homebrew/gettext-0.19.4.tar.xz
Error: Permission denied - /mnt/sdn1/<username>/.linuxbrew/opt/xz/bin/xz
```

**Comment by sjackman** [comment]
Please report the output of `ls -l /home/sjackman/.linuxbrew/opt/xz/bin/xz`.

I don't see the `chown` error in this log. Can you please post a more complete log? You can use `brew gist-logs gettext`
