### ISSUE TITLE
pcre: depends on bzip2

### ISSUE THREAD

**Issue by andyli** [Homebrew/linuxbrew#319]
```
==> Installing neko dependency: pcre
==> Downloading https://downloads.sourceforge.net/project/pcre/pcre/8.36/pcre-8.
Already downloaded: /home/andy/.cache/Homebrew/pcre-8.36.tar.bz2
==> ./configure --prefix=/home/andy/.linuxbrew/Cellar/pcre/8.36 --enable-utf8 --
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... no
** Cannot --enable-pcregrep-libbz2 because bzlib.h was not found

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
```

It built after I removed `"--enable-pcregrep-libbz2",` ([line 33 of pcre.rb](https://github.com/Homebrew/linuxbrew/blob/5ed317032f23ebd7556e0c889d60110fe34107ec/Library/Formula/pcre.rb#L33)).

**Comment by iggyvolz** [comment]
It may require a bz library to be installed - everything's directly ported from mac where a lot of these libraries are pre-installed, so adding dependencies is needed for some formulae.

For this one in particular, it looks like it may be lbzip2, but I'll play around with it and see what I can do.

**Comment by sjackman** [comment]
Try `brew install homebrew/dupes/bzip2`

**Comment by sjackman** [comment]
Thanks for the bug report, Andy.
