### ISSUE TITLE
Annoying libssl warning

### ISSUE THREAD

**Issue by jamesscholeyweb** [Homebrew/linuxbrew#321]
Hi, I'm running linuxbrew on elementary Freya beta 2 based on Ubuntu. I have installed git 2.3.3 via linuxbrew and get the following warning when running git commands:-

.linuxbrew/lib/libcrypto.so.1.0.0: no version information available (required by git)

The command still completes and I am aware that this is a warning. After a bit of research I find that this is either due to the shared version of openSSL/libssl differing between system and homebrew although I am fairly certain both are using openSSL 1.0.2a 16th March build.

The other information I have read is that Ubuntu purposely build the source with version information built in and the homebrew source doesn't so even if the shared system version is the same the warning would persist and this is Ubuntu specific?

Is there any way to get rid of this warning? Before I just go back to apt-get?

Any help would be much appreciated.

**Comment by sjackman** [comment]
I'm just guessing here, but please try
```sh
brew reinstall git --with-brewed-curl --with-brewed-openssl
```

**Comment by sjackman** [comment]
You may also want to try the [Standalone Installation instructions](https://github.com/Homebrew/linuxbrew/wiki/Standalone-Installation) for Linuxbrew, but that's a more heavyweight solution.

**Comment by jamesscholeyweb** [comment]
@sjackman Shaun, thank you for the quick response. Fix (A) did the trick :) I assume this compiles source using brews curl and openssl instead of system shared version? or am I misunderstanding. Anyway it did the trick. Will I need to do this again after a "brew upgrade git" or will brew remember these build options?

Thanks again Shaun, Good man!

**Comment by sjackman** [comment]
Hi, James. Glad to hear it. Yes, you understand correctly. Brew will remember these build options for `brew upgrade`. See `brew info git` where it shows the options used.

**Comment by nhumrich** [comment]
I am getting this same warning but for ssh (not git), which is weird because I never installed ssh through brew.
linuxbrew/lib/libcrypto.so.1.0.0: no version information available (required by ssh)

$ brew list
autoconf  bison  cmake  curl  git  go  gradle  jq  makedepend  openssl  pkg-config  xz

**Comment by jamesscholeyweb** [comment]
Neither did I. I think OpenSSL (libssl) is a dependency of git or homebrew.
Either way it gets installed as a dependency. I assume the same fix should
work for you too.

**Comment by nhumrich** [comment]
I already tried the fix with no success.

**Comment by sjackman** [comment]
@nhumrich Do you have the `LD_LIBRARY_PATH` environment variable set? If so, try unsetting it using

```sh
unset LD_LIBRARY_PATH
which -a ssh
ssh --version
```

**Comment by nhumrich** [comment]
ssh --version returns "unknown option", but unsetting LD_LIBRARY_PATH seams to work. What is the purpose of that envvar?

**Comment by sjackman** [comment]
It tells the dynamic linker where to search for shared libraries. Linuxbrew does not require it, and it can cause problems. You may want to find where it's being set in your startup scripts and remove it.

**Comment by nhumrich** [comment]
Thanks. Already did that, it was just in my bashrc.
