### ISSUE TITLE
brew install vm?

### ISSUE THREAD

**Issue by DiagonalArg** [Homebrew/linuxbrew#327]
Forgive the untutored question, but since there is no homebrew package for vm ("view mail", used under emacs), and since I don't know ruby, how do I go about requesting one (if that's possible):

http://www.nongnu.org/viewmail/

and:
https://launchpad.net/vm
http://download.savannah.gnu.org/releases/viewmail/

**Comment by Mikaela** [comment]
I am not sure if formula requests are took, but I believe that new formulas and updates should be submitted to https://github.com/homebrew/homebrew where Linuxbrew will be pulled once a week (unless there is security issue which can cause faster pull) from what I have understood.

**Comment by iggyvolz** [comment]
Yes - you should run brew create <URL of download> then work on it from there.  A good workflow for submitting changes to homebrew from linuxbrew is:
```bash
cd $(brew --prefix)
git remote add homebrew git@github.com:Homebrew/homebrew.git # Or use https if you prefer, or skip this step if you've already done this
git remote add fork git@github.com:DiagonalArg/homebrew.git # Or use https if you prefer, or skip this step if you've already done this
git fetch --all
git checkout homebrew/master
git checkout -b add-vm # or whatever your formula may be
# Now make your changes
git add .
git commit -m "Add vm"
git push -u fork add-vm
brew update # to go back to normal linuxbrew
```
