### ISSUE TITLE
tar xf failed for every package 

### ISSUE THREAD

**Issue by yeluolei** [Homebrew/linuxbrew#342]
I want to install linux brew package, but it failed with tar decompress failure.
this command should work with tar xzf ...
but failed with tar xf ...

==> Downloading http://ftpmirror.gnu.org/tar/tar-1.28.tar.gz
Already downloaded: /home/users/a/.cache/Homebrew/gnu-tar-1.28.tar.gz
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Archive contains obsolescent base-64 headers
tar: Read 6323 bytes from /home/users/a/.cache/Homebrew/gnu-tar-1.28.tar.gz
tar: Error exit delayed from previous errors
Error: Failure while executing: tar xf /home/users/a/.cache/Homebrew/gnu-tar-1.28.tar.gz

anyone can help ? thanks~

**Comment by yeluolei** [comment]
ps. this is the error log for brew install -vd gnu-tar : 

**And I have no rights to write any folder except my home directory.**


/home/users/a/.linuxbrew/Library/brew.rb (Formulary::FormulaLoader): loading /home/users/a/.linuxbrew/Library/Formula/gnu-tar.rb
/home/users/a/.linuxbrew/Library/brew.rb (Formulary::FormulaLoader): loading /home/users/a/.linuxbrew/Library/Formula/glibc.rb
/home/users/a/.linuxbrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /home/users/a/.linuxbrew/Library/Formula/gnu-tar.rb
/home/users/a/.linuxbrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/users/a/.linuxbrew/Library/Formula/glibc.rb
==> Downloading http://ftpmirror.gnu.org/tar/tar-1.28.tar.gz
Already downloaded: /home/users/a/.cache/Homebrew/gnu-tar-1.28.tar.gz
==> Verifying gnu-tar-1.28.tar.gz checksum
tar xf /home/users/a/.cache/Homebrew/gnu-tar-1.28.tar.gz
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Archive contains obsolescent base-64 headers
tar: Read 6323 bytes from /home/users/yerurui/.cache/Homebrew/gnu-tar-1.28.tar.gz
tar: Error exit delayed from previous errors
Error: Failure while executing: tar xf /home/users/a/.cache/Homebrew/gnu-tar-1.28.tar.gz
/home/users/a/.linuxbrew/Library/Homebrew/utils.rb:151:in `safe_system'
/home/users/a/.linuxbrew/Library/Homebrew/download_strategy.rb:187:in `block in stage'
/home/users/a/.linuxbrew/Library/Homebrew/utils.rb:144:in `with_system_path'
/home/users/a/.linuxbrew/Library/Homebrew/download_strategy.rb:187:in `stage'
/home/users/a/.linuxbrew/Library/Homebrew/resource.rb:89:in `block in unpack'
/home/users/a/.linuxbrew/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/home/users/a/.linuxbrew/Library/Homebrew/resource.rb:88:in `unpack'
/home/users/a/.linuxbrew/Library/Homebrew/resource.rb:81:in `stage'
/home/users/a/.linuxbrew/Library/Homebrew/formula.rb:764:in `stage'
/home/users/a/.linuxbrew/Library/Homebrew/formula.rb:406:in `brew'
/home/users/a/.linuxbrew/Library/Homebrew/build.rb:114:in `install'
/home/users/a/.linuxbrew/Library/Homebrew/build.rb:186:in `<main>'

**Comment by yeluolei** [comment]
my brew config result

HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/linuxbrew.git
HEAD: d9e68a81edcc3717826b4ca6a2a4bffc71b01632
Last commit: 3 days ago
HOMEBREW_PREFIX: /home/users/a/.linuxbrew
HOMEBREW_CELLAR: /home/users/a/.linuxbrew/Cellar
CPU: 12-core 64-bit 6
OS X: 0-x86_64
Xcode: N/A
CLT: N/A
Clang: N/A
X11: N/A
System Ruby: 1.9.3-p385 => /home/users/a/.jumbo/bin/ruby
Perl: /home/users/a/.jumbo/bin/perl
Python: /home/users/a/.jumbo/bin/python => /home/users/a/.jumbo/bin/python2.7
Ruby: /home/users/a/.jumbo/bin/ruby
Java: 1.6.0_45

**Comment by yeluolei** [comment]
finally fix this by myself, I didn't tar in my /usr/bin fold and I disabled the ENV['path'] replace in the utils.rb file.

**Comment by sjackman** [comment]
You can also use `brew install homebrew/dupes/gnu-tar`.
