### ISSUE TITLE
how to set the gcc location?

### ISSUE THREAD

**Issue by yeluolei** [Homebrew/linuxbrew#343]
I have only gcc 3.5 in my system and can't compile anything. but I have another gcc installed in my home folder ~/opt/gcc48 .how can I change the script to work with this version of gcc ?

**Comment by yeluolei** [comment]
fix this problem by myself with the information in standalone install document. Thanks!

ln -s $(which gcc) $prefix/bin/gcc-$(gcc -dumpversion |cut -d. -f1,2)
ln -s $(which g++) $prefix/bin/g++-$(g++ -dumpversion |cut -d. -f1,2)
ln -s $(which gfortran) $prefix/bin/gfortran-$(gfortran -dumpversion |cut -d. -f1,2)

**Comment by sjackman** [comment]
Glad to hear that you sorted it out.
