### ISSUE TITLE
Linuxbrew does not install the software into /usr/local, behaviours not equals the document

### ISSUE THREAD

**Issue by netroby** [Homebrew/linuxbrew#344]
Linuxbrew does not install the software into /usr/local, behaviours not equals the document

The real path it will installed software was $HOME/.linuxbrew/bin

And the document said: 

```
The standard script installs Homebrew to /usr/local so that you don’t need sudo when you brew install. It is a careful script, it can be run even if you have stuff installed to /usr/local already. It tells you exactly what it will do before it does it too. And you have to confirm everything it will do before it starts.
```

**Comment by Mikaela** [comment]
You are confusing Homebrew and Linuxbrew. Which document gave you that?

**Comment by netroby** [comment]
https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Installation.md

**Comment by dunn** [comment]
Looks like that part of the manpage hasn't been updated to be Linuxbrew-specific.  Feel free to open a PR!

**Comment by Mikaela** [comment]
I am not sure if it can even be updated as it seems to be Homebrew directly and if I understood correctly, Linuxbrew is supposed to be merged to Homebrew sometimes.

**Comment by dunn** [comment]
I think at this point the merges are mostly one-way, with Shaun pulling in changes from main Homebrew.

**Comment by sjackman** [comment]
Yes, that document is inaccurate for Linuxbrew. It could be patched. The Linuxbrew installation instructions are at
http://brew.sh/linuxbrew/
