### ISSUE TITLE
Standalone is little too standalone

### ISSUE THREAD

**Issue by gitfoxi** [Homebrew/linuxbrew#346]
I got through most of the standalone instructions on Centos5. I can't build Ruby because I'm missing a header file `sys/sdt.h`. I can't build tcl-tk because I'm missing `X11/Xlib.h`.

These headers are in fact installed in my system's base directory tree.

I guess the standalone installation doesn't see my system headers and only looks at the ones that it installed itself during the bootstrap process. But there doesn't seem to be a way to get it to install everything that you would need to build most software.

**Comment by sjackman** [comment]
Yes, the standalone installation intentionally does not use any system libraries or headers.

For `tcl-tk` you can build without X11 support: `brew install tcl-tk --without-x11`

I have not run into the `sys/sdt.h` issue when building Ruby. Can you post the log?

`brew gist-logs ruby`

**Comment by gitfoxi** [comment]
Tk wouldn't be much good `--without-x11`?

`brew gist-logs` is another thing that isn't working. Maybe it uses Ruby? I'll paste them by hand:

https://gist.github.com/gitfoxi/0d8c7fcf0f4a655f5751

**Comment by sjackman** [comment]
> Tk wouldn't be much good --without-x11?

Correct. Do you need Tk?

> brew gist-logs is another thing that isn't working. Maybe it uses Ruby?

What's the error message? All of Homebrew/Linuxbrew is written in Ruby.

**Comment by sjackman** [comment]
Looks like a bug in the Ruby autoconf checks. It says that dtrace USDT is available, but then can't find the header. I believe `sys/sdt.h` is a single portable header. You can download it and install that single header file yourself to work around this issue.

```
checking whether dtrace USDT is available... yes
checking whether dtrace USDT is available... (cached) yes
checking whether dtrace needs post processing... In file included from conftest.c:1:0:
conftest_provider.h:9:21: fatal error: sys/sdt.h: No such file or directory
 #include <sys/sdt.h>
                     ^
compilation terminated.
no
```

**Comment by gitfoxi** [comment]
Tk is what you need to do simple GUIs in Python. I use it sometimes. Anyway, you could use something else like qt, gtk or wx -- they all still need x11.

There was no error message from `brew gist-logs` it seems to hang.

**Comment by sjackman** [comment]
`brew gist-logs` is recompiling the package. It may take a while.

**Comment by gitfoxi** [comment]
I've been able to build xlib and tcl/tk. I could make a formula for xlib (maybe calling it x11-xlib). But there needs to be some logic that understands that x11-xlib is only necessary for things that depend on x11 under standalone-linuxbrew. Do you think that's doable?

**Comment by sjackman** [comment]
I'd be happy to accept a PR improving the `:x11` dependency and adding the `xorg-xlib` formula, if you're up for it. Take a look at [x11_dependency.rb](https://github.com/Homebrew/linuxbrew/blob/master/Library/Homebrew/requirements/x11_dependency.rb). If the package `glibc` is installed, you can assume it's a standalone installation, and a standard installation otherwise.

I'm away on vacation for the next week.

**Comment by razvanc87** [comment]
:+1: for this! I'm trying to build it on a work machine that has these stupid modules which makes a mess out of everything... and when I saw standalone `linuxbrew` I thought this is my way out... well not so much since it depends on `X11` for which... there is no formula yet...

**Comment by sjackman** [comment]
For X11, I've installed it using the native package manager and then symlinked it into the Linuxbrew hierarchy. It's not ideal, but it's a usable workaround. I would eventually like to package X11 for Linuxbrew, perhaps in a month's time.

**Comment by razvanc87** [comment]
Right... except when you don't have administrator permissions things get a little bit crazy... (which is my case)

**Comment by sjackman** [comment]
Yep, I'm familiar with that situation. You should be able to ask your sysadmins though to `apt-get` or `yum` install X11. That's a reasonable request in my opinion.

**Comment by razvanc87** [comment]
The machine has `X11` on it already, the problem was that I wanted a newer version of `glibc` (they don't do major upgrades too often because it breaks things). And with a new version of `glibc`... it was a mess specifying where things are so that system libraries don't collide with `linuxbrew` libraries. Anyway it was way too much work figuring things out so I sopped trying...
