### ISSUE TITLE
gcc build failed with mpfr failure

### ISSUE THREAD

**Issue by yeluolei** [Homebrew/linuxbrew#349]
I use an self installed version of gcc 4.8.3 to build a brew version , but failed when build mpfr, the error log as the gist shows.

brew install gcc 

https://gist.github.com/anonymous/1ab044b91871628c0cc5

**Comment by yeluolei** [comment]
by the way, I can't install glic with standalone installation with the gist below.

https://gist.github.com/23bf728fe2b3a19a935f

**Comment by sjackman** [comment]
You have multiple versions of MPFR installed, and you're mixing the header files of one version with the libraries of a different version. Be sure that you only have one version of MPFR installed.

https://gist.github.com/anonymous/1ab044b91871628c0cc5#file-03-make-L2229-L2244
```
Incorrect MPFR version! (3.1.2-p11 header vs 3.1.2 library)
Nothing else has been tested since for this reason,
any other test may fail. Please fix this one first.
 
You can try to avoid this problem by changing the value of
shlibpath_overrides_runpath in the libtool file and rebuild
MPFR (make clean && make && make check).
Otherwise this error may be due to a corrupted mpfr.h, an
incomplete build (try to rebuild MPFR from scratch and/or
use 'make clean'), or something wrong in the system.
FAIL: tversion
=======================
155 of 160 tests failed
(1 test was not run)
=======================
make64[2]: *** [check-TESTS] Error 1
```

**Comment by yeluolei** [comment]
thanks for your answer, I have an version of mpfr in my system and I can't modify it. how can I override the include lib when I install this one?

another question, what about the glibc install issue?

**Comment by sjackman** [comment]
The [Standalone Installation](https://github.com/Homebrew/linuxbrew/wiki/Standalone-Installation) instructions may solve both of these issues. Be sure to follow the instructions carefully and precisely.
