### ISSUE TITLE
EMacs 24.5 released

### ISSUE THREAD

**Issue by netroby** [Homebrew/linuxbrew#350]
May be emacs can update to Emacs 24.5?

https://github.com/Homebrew/linuxbrew/blob/master/Library/Formula/emacs.rb

https://www.gnu.org/software/emacs/

**Comment by iggyvolz** [comment]
homebrew/homebrew#38527

Already done.  Will be merged weekly.

**Comment by sjackman** [comment]
I'm on vacation until April 22. The regular merging schedule will resume once I return.
