### ISSUE TITLE
c=gzgetc(image->blob->file); 

### ISSUE THREAD

**Issue by OhCoder** [Homebrew/linuxbrew#351]
![screen shot 2015-04-15 at 9 10 56 am](https://cloud.githubusercontent.com/assets/890676/7151391/e2f21bb2-e35b-11e4-984b-28d68a26423d.png)
Hey, I got an issue when I install imagemagick-ruby186
My system is ubuntu 14.04 and I use linux-brew tool to install. 
I don't know why, can some body help me?

**Comment by sjackman** [comment]
Does `brew install homebrew/dupes/zlib` resolve this issue?
