### ISSUE TITLE
xz failed to run in standard alone installation under CentOS 5

### ISSUE THREAD

**Issue by feng-ye** [Homebrew/linuxbrew#353]
I am running standalone linuxbrew in CentOS 5. After upgrade xz to 5.2.1, it failed to run with message:

    xz: Error creating a pipe: Function not implemented

And I can not upgrade other formula with tar.xz files. (e.g. git)

The error is from pipe2 call. It is not supported in the kernel of CentOS 5 (2.6.18).

So I made a patch to remove the pipe2 check from configure script for old kernel versions. Is there any better way to solve this problem?

```diff
diff --git a/Library/Formula/xz.rb b/Library/Formula/xz.rb
index f4fdf49..8c5c842 100644
--- a/Library/Formula/xz.rb
+++ b/Library/Formula/xz.rb
@@ -16,6 +16,15 @@ class Xz < Formula
   option :universal

   def install
+    if OS.linux?
+      kernel_version = `uname -r`.chomp
+      if Gem::Version.new(kernel_version) < Gem::Version.new("2.6.27")
+        inreplace "configure" do |s|
+          s.gsub! /posix_fadvise pipe2/, "posix_fadvise"
+        end
+      end
+    end
+
     ENV.universal_binary if build.universal?
     system "./configure", "--disable-debug",
                           "--disable-dependency-tracking",
```

**Comment by sjackman** [comment]
At run time, xz needs to check whether the `pipe2` system call is available. This is an upstream bug.

**Comment by sjackman** [comment]
This is a decent work around, though. Thanks.
