### ISSUE TITLE
JDK need upgrade to 1.8.0 b45

### ISSUE THREAD

**Issue by netroby** [Homebrew/linuxbrew#355]
https://github.com/homebrew/linuxbrew/blob/master/Library/Formula/jdk.rb

http://www.oracle.com/technetwork/java/javase/downloads/index.html

**Comment by iggyvolz** [comment]
You can submit a pull request - just click "Edit" on the file in question and edit the version and hash.  If you need assistance please ask and I (or someone who is on the Home/Linuxbrew team) will be happy to help!
