### ISSUE TITLE
error: option --no-user-cfg not recognized

### ISSUE THREAD

**Issue by xu-cheng** [Homebrew/linuxbrew#358]
_From @Rochvellon on April 20, 2015 12:19_

Hi,

I wanna install cmake but I get "error: option --no-user-cfg not recognized"

Gist:
https://gist.github.com/anonymous/873f3977037298f4d0fb

Any ideas?

_Copied from original issue: Homebrew/homebrew#38852_

**Comment by xu-cheng** [comment]
_From @DomT4 on April 20, 2015 12:33_

Needs to be filed at [Homebrew/linuxbrew](https://github.com/Homebrew/linuxbrew) :).

**Comment by Rochvellon** [comment]
Error found.

export PATH=/package/host/localhost/python-2.7/bin:$PATH will help

**Comment by sjackman** [comment]
Your version of Python is too old. Try `brew install python cmake`.
See https://trac.macports.org/ticket/18196 and https://github.com/Homebrew/homebrew/issues/36295
