### ISSUE TITLE
Vte installs fine on mac but not ubuntu

### ISSUE THREAD

**Issue by paulhybryant** [Homebrew/linuxbrew#362]
gist logs are here
https://gist.github.com/22ebd67a1320dcc53af1

From the error it seems it requires glib 2.26.0 and above,
but brew info glib shows the newest one is 2.24.0.

However I am able to install vte successfully on mac os.

**Comment by aiyuchen** [comment]
you can 
```
brew install vet3
```

**Comment by saketkc** [comment]
@paulhybryant `brew update`
Latest one on Homebrew/Linuxbrew is `2.44`

**Comment by paulhybryant** [comment]
Thanks for the reply. After further looking into the gist-log, the problem seems to be the follows:

checking for VTE... configure: error: Package requirements (glib-2.0 >= 2.26.0 gobject-2.0 pango >= 1.22.0 gtk+-2.0 >= 2.20.0 gobject-2.0 gio-2.0 gio-unix-2.0 x11 cairo-xlib) were not met:
 
No package 'x11' found

There is no such package x11. I didn't see the dependency on x11 in vte.rb though.

**Comment by paulhybryant** [comment]
I am trying to install terminator, and it depends on vte, not vte3.

On Mon, Apr 20, 2015 at 7:24 PM, 李惟 <notifications@github.com> wrote:

> you can
>
> brew install vet3
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Homebrew/linuxbrew/issues/362#issuecomment-94616752>.
>



-- 
With Regards,

Yu Huang

Software Engineer,
Google Inc.

**Comment by sjackman** [comment]
> No package 'x11' found

You'll need to install X11 using your native package manager (yum or apt-get).
