### ISSUE TITLE
libxslt: Depends on python

### ISSUE THREAD

**Issue by davydden** [Homebrew/linuxbrew#364]
i was following the standalone instructions and i had a linking error while building `libxslt` 
```
/bla/bla/.linuxbrew/bin/ld: cannot find -lpython2.6
```

it seems one either needs to keep `LD_LIBRARY_PATH` or install homebrew's `python` before actually trying to install `libxslt`. Installing `python` solved the issue for me.

p.s. I am on SuSE Linux Enterprise Desktop

**Comment by sjackman** [comment]
Thanks for the info. I don't want to add a dependency on Python, because I don't want to force the user to install Python if they already have it installed. This is an issue though, and similar issues have come up related to Python dependencies.

**Comment by davydden** [comment]
i just though that perhaps this could be mentioned in the instructions so that users are aware of that dependency.

**Comment by sjackman** [comment]
These issues and Google are the documentation, so far. The Wiki is publicly editable. You could, if you like, start a page title "Dependencies"
