### ISSUE TITLE
openmpi: Depends on Java: No such file or directory - vtsetup.jar

### ISSUE THREAD

**Issue by davydden** [Homebrew/linuxbrew#365]
on my standalone linuxbrew, java is not picked up. 
As a result there is no `vtsetup.jar` and build fails 
```
Error: No such file or directory - ~/.linuxbrew/Cellar/open-mpi/1.8.4/bin/vtsetup.jar
```
at the last lines of formula.
```
libexec.install bin/'vtsetup.jar'
```

I wonder whether one should add some dependency to install java, or keep this part in the `if` block?

**Comment by saketkc** [comment]
See: https://github.com/Homebrew/homebrew/pull/33177/

It installs to `libexec`:
```
$ ls ~/.linuxbrew/Cellar/open-mpi/1.8.4/libexec/
vtsetup.jar
```

**Comment by davydden** [comment]
i think it's a different issue, in stand-alone I have
```
Java: N/A
```
so I guess this file is simply not there, thus the error during installation.

**Comment by sjackman** [comment]
Does `brew install jdk` fix this issue?

**Comment by davydden** [comment]
yes, it does. Shall one then add `jdk` as a dependency?

**Comment by sjackman** [comment]
@dpo Should `open-mpi` need `depends_on :java` for [`vtsetup.jar`](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/open-mpi.rb#L50)?

I wonder why this issues does not affect Mac.

**Comment by dpo** [comment]
Yes there should probably be a dependency on `:java`. I've never tried installing `open-mpi` on a fresh Mac, but it could be that our users already have Java installed, including the bot.

**Comment by sjackman** [comment]
My understanding was that the BrewTestBot does not have Java installed unless the formula `depends_on :java`. @mikemcquaid ?

**Comment by mikemcquaid** [comment]
Java is installed regardless.

**Comment by sjackman** [comment]
Thanks for clearing that up, Mike.

**Comment by sjackman** [comment]
@davydden `open-mpi` should `depends_on :java`. You can send this PR upstream to Homebrew/homebrew.
