### ISSUE TITLE
glibc install failed and brew install hello failed

### ISSUE THREAD

**Issue by yeluolei** [Homebrew/linuxbrew#370]
I have installed my glibc and failed with the following log, this should be an bug fixed before as #126 

```
Inconsistency detected by ld.so: get-dynamic-info.h: 134: elf_get_dynamic_info: Assertion `info[15] == ((void *)0)' failed!
```

https://gist.github.com/e592e5867d63880039fa

and I tried to brew install hello, it failed with 

```
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/tmp/hello20150422-63131-1qepcf5/hello-2.10':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
```

https://gist.github.com/1cf36ee9738da1394eec

**Comment by sjackman** [comment]
Have you installed glibc using the [Standalone Installation](https://github.com/Homebrew/linuxbrew/wiki/Standalone-Installation) instructions?

**Comment by sjackman** [comment]
Do you have the `LD_RUN_PATH` environment variable set? `echo $LD_RUN_PATH`

**Comment by yeluolei** [comment]
I didn't set the `LD_RUN_PATH` and I am follow the Standalone Installation instructions and have tried three times.

**Comment by sjackman** [comment]
Which distribution of Linux are you using?

**Comment by yeluolei** [comment]
centos 4.3， sorry for such an old distribution, but I have to work with it. :(

**Comment by sjackman** [comment]
Ah, I see. Due to the super old kernel, I haven't had much luck with CentOS 4.3. It does work with CentOS 5.10. I'm afraid that I don't have the time to troubleshoot this issue on CentOS 4. If you find a work around or fix, please report back. Sorry I couldn't be more helpful.
