### ISSUE TITLE
setting CFLAGS FFLAGS etc to have -O3 optimisation

### ISSUE THREAD

**Issue by davydden** [Homebrew/linuxbrew#375]
What is the current consensus on tweaking compiler flags used to build formulae within linuxbrew?
I did not see this issue discussed.

Is there something like `HOMEBREW_CC` to set/override the default flags? How are those default flags set anyway?

**Comment by sjackman** [comment]
The default flags are set in `Library/Homebrew/extend/ENV/std.rb` and `Library/Homebrew/os/linux/hardware.rb`. Linuxbrew uses the same defaults as Homebrew. There's no way to tweak compiler flags that I know of. You may want to try asking at Homebrew/homebrew.
