### ISSUE TITLE
git: Build error 2.4.0 after e3147f2

### ISSUE THREAD

**Issue by RobertThz** [Homebrew/linuxbrew#392]
I suspect that the fix in commit e3147f2 broke the build for those of us that don't have perl installed via linuxbrew.

The build fails on line 139 in Library/Formula/git.rb:
```ruby
pod = Pathname.new Dir[lib/"*/*/perllocal.pod"][0]
```
with the error 
```
Error: no implicit conversion of nil into String
```

Please see https://gist.github.com/RobertThz/54cb2c78e879c02b9dd5 for the full error message.

If I install the brew version of perl first, git builds just fine.

**Comment by sjackman** [comment]
Woops. Thanks for the bug report, Robert.
