### ISSUE TITLE
Define custom install directory in environment variable

### ISSUE THREAD

**Issue by parisk** [Homebrew/linuxbrew#396]
Is there any way to define a custom install directory for linuxbrew packages in an environment variable (e.g. `LINUXBREW_HOME`)?

This could be really helpful in cases such as a multitenant system, in which Linuxbrew will be installed globally and users using it would get each package installed in their home directory.

This is a feature that is already supported by most package managers:

- pip utilizes the combination of `PYTHONUSERBASE` and `PIP_USER` environment variables
- npm utilizes the `NPM_CONFIG_PREFIX` environment variable
- composer utilizes `COMPOSER_HOME`
- gem works as such by default

If this feature is not available are there any plans to implement it?

**Comment by sjackman** [comment]
Yes, this feature is supported. I'm curious though. What's the advantage of centralizing the Homebrew source code, and why wouldn't each user install their own in their home directory?

Here's how a user would set up their own cellar of software:

```sh
~ ❯❯❯ which brew
/usr/local/bin/brew
~ ❯❯❯ brew --cellar
/usr/local/Cellar
~ ❯❯❯ mkdir ~/bin ~/Cellar
~ ❯❯❯ ln -s /usr/local/bin/brew ~/bin/
~ ❯❯❯ PATH=$HOME/bin:$PATH
~ ❯❯❯ which brew
/Users/sjackman/bin/brew
~ ❯❯❯ brew --cellar
/Users/sjackman/Cellar
```

**Comment by sjackman** [comment]
See the Homebrew source code here: https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/config.rb#L44-L48

**Comment by parisk** [comment]
In general sounds okay, but wouldn't it be better if we could handle this easily with an environment variable like `LINUXBREW_CELAR`? Would you be open to review a pull request for this?

**Comment by sjackman** [comment]
You could try sending a pull request for that feature upstream to https://github.com/Homebrew/homebrew

**Comment by sjackman** [comment]
I try not to make significant changes to Linuxbrew that aren't also found in Homebrew.
