### ISSUE TITLE
Error: No available formula for <tapped formula>

### ISSUE THREAD

**Issue by eugenk** [Homebrew/linuxbrew#398]
Hi,

after tapping, a formula can't be found:

```
❯ brew tap eugenk/hets
==> Tapping eugenk/hets
Cloning into '/home/eugen/.linuxbrew/Library/Taps/eugenk/homebrew-hets'...
remote: Counting objects: 216, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 216 (delta 0), reused 0 (delta 0), pack-reused 213
Receiving objects: 100% (216/216), 36.10 KiB | 0 bytes/s, done.
Resolving deltas: 100% (121/121), done.
Checking connectivity... done.
Tapped 8 formulae (31 files, 240K)

❯ brew doctor
Your system is ready to brew.

❯ brew install hets
==> Installing hets from eugenk/homebrew-hets
Error: No available formula for uDrawGraph (dependency of hets)
Searching formulae...
uDrawGraph
Searching taps...

❯ brew doctor
Error: Failed to import: uDrawGraph
No available formula for uDrawGraph 
Your system is ready to brew.

❯ brew search udrawgraph
uDrawGraph

❯ brew info udrawgraph
Error: No available formula for udrawgraph 
```
interestingly, `brew search` finds the formula, but `brew info` and `brew install` don't.

System information (Ubuntu 14.04):
```
❯ uname -a
Linux ubuntu 3.13.0-34-generic #60-Ubuntu SMP Wed Aug 13 15:45:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

❯ gcc --version
gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2

❯ ruby --version
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
```

The same happens on an up-to-date archlinux box. It seems like linuxbrew has only a problem with the formula of udrawgraph, but I have no idea why.

**Comment by iggyvolz** [comment]
Try ```brew install uDrawGraph```.  Most formula are all lowercase due to capitalization quirks

**Comment by eugenk** [comment]
Oh yes, I forgot to give the output if `brew install`:
```
❯ brew install uDrawGraph
Error: No available formula for udrawgraph 
Searching formulae...
uDrawGraph
Searching taps...
```

**Comment by eugenk** [comment]
I just found out: If I rename the formula from `uDrawGraph.rb` to `udrawgraph.rb`, linuxbrew finds it. Note that homebrew on OSX has no problems finding it without the renaming.

**Comment by eugenk** [comment]
Maybe the filesystem plays a role in this. As far as I know, HFS+ is case insensitive by default, while btrfs (on my arch machine) and ext4 (on ubuntu) are case sensitive, but I'm not 100% sure if this is correct.

**Comment by iggyvolz** [comment]
@eugenk You might want to send a PR to the offending tap... capitals in formula names are really discouraged.

**Comment by eugenk** [comment]
Alright, will do. Just out of curiosity: Does linuxbrew/homebrew plan to support capitals some day? I can definitely understand if not, but it's always nice to know.

**Comment by sjackman** [comment]
No, Homebrew/Linuxbrew has no plans to support capital letters in formula names.
