### ISSUE TITLE
linuxbrew created `~/Library`. Can I delete it?

### ISSUE THREAD

**Issue by dpc** [Homebrew/linuxbrew#406]
Hi,

I've installed linuxbrew in `~/.linuxbrew` as a git clone, and I'd like it to sit there, not pollute my home directory.

```
Library
└── Logs
    └── Homebrew
        ├── bzip2
        │   ├── 01.make
        │   ├── 02.make
        │   └── 03.make
        ├── curl
        │   ├── 01.configure
        │   ├── 02.make
        │   └── config.log
        ├── glib
(...)
```

Is there a configuration option to fix this?

**Comment by sjackman** [comment]
Yes, you can delete it. Set
`export HOMEBREW_LOGS=~/.local/log`

**Comment by sjackman** [comment]
@dpc @mikaela I'm thinking of changing the default log directory from `~/Library/Logs/Homebrew` to something else for Linuxbrew. I'd like to use an existing standard of where log files should go in a Linux user's home directory. Any thoughts? cc @Homebrew/science Your input? Please unsubscribe from this issue if you don't use Linuxbrew.

See this Stackoverflow question: http://stackoverflow.com/questions/25897836/where-should-i-write-a-user-specific-log-file-to-and-be-xdg-base-directory-comp

I'm thinking `~/.cache/Homebrew/Logs`
Sound good?

http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
> $XDG_CACHE_HOME defines the base directory relative to which user specific non-essential data files should be stored.

**Comment by dpc** [comment]
:+1:

**Comment by Mikaela** [comment]
`$HOME/.cache/Homebrew/Logs` sounds good to me.

**Comment by sjackman** [comment]
See #278 "Log location on Linux should be moved to be related to the linuxbrew folder"
