### ISSUE TITLE
Error: no such file to load -- irb on RHEL 6.6 / Ruby 1.8.7

### ISSUE THREAD

**Issue by josePhoenix** [Homebrew/linuxbrew#411]
I'm trying to use linuxbrew to get more modern versions of the tools I use on some of the servers at work, but things may be too old!

Here's `brew doctor` (running brew from git master):

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: An outdated version of Git was detected in your PATH.
Git 1.7.10 or newer is required to perform checkouts over HTTPS from GitHub.
Please upgrade: brew upgrade git

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/clamav.h
```

When I try to `brew upgrade git`, I get:

```
$ brew upgrade git
Error: no such file to load -- irb
Please report this bug:
    https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/user/jlong/.linuxbrew/Library/Homebrew/debrew/irb.rb:1:in `require'
/user/jlong/.linuxbrew/Library/Homebrew/debrew/irb.rb:1
/user/jlong/.linuxbrew/Library/Homebrew/debrew.rb:2:in `require'
/user/jlong/.linuxbrew/Library/Homebrew/debrew.rb:2
/user/jlong/.linuxbrew/Library/Homebrew/formula_installer.rb:14:in `require'
/user/jlong/.linuxbrew/Library/Homebrew/formula_installer.rb:14
/user/jlong/.linuxbrew/Library/Homebrew/cmd/install.rb:5:in `require'
/user/jlong/.linuxbrew/Library/Homebrew/cmd/install.rb:5
/user/jlong/.linuxbrew/Library/Homebrew/cmd/upgrade.rb:1:in `require'
/user/jlong/.linuxbrew/Library/Homebrew/cmd/upgrade.rb:1
/user/jlong/.linuxbrew/Library/brew.rb:58:in `require'
/user/jlong/.linuxbrew/Library/brew.rb:58:in `require?'
/user/jlong/.linuxbrew/Library/brew.rb:122
```

**Comment by sjackman** [comment]
Please report `which -a irb`. If that fails, please install whichever host package includes the `irb` executable. Alternatively, you can try installing `ruby` using Linuxbrew `brew install ruby`.

**Comment by josePhoenix** [comment]
Correct, no `irb` installed. I didn't think it was possible to install ruby without irb, but there you go.

Unfortunately, I can't install packages system-wide... this is what I was hoping to use linuxbrew to avoid. I can't `brew install ruby` because of of the same issue.

I'll try bugging our systems admins to get irb installed. What versions does linuxbrew support? Only the 1.8.x branch?

**Comment by sjackman** [comment]
Ruby 1.8.6 or newer. See http://brew.sh/linuxbrew/

It may be possible to work around this issue by creating an a executable file named `irb` in your `PATH`. e.g.
```sh
echo false >~/bin/irb
chmod +x ~/bin/irb
PATH=~/bin:$PATH
```

**Comment by josePhoenix** [comment]
Alas, that was not enough. I'll go back to bugging our IT people. Thanks for your help!

**Comment by outcoldman** [comment]
Btw, if you cannot install ruby with irb you can compile it on your own with, just install it from sources https://www.ruby-lang.org/en/documentation/installation/, see 

> By default, this will install Ruby into /usr/local. To change, pass the --prefix=DIR option to the ./configure script.

You can basically just do

```
./configure --prefix=/home/username/.linuxbrew
```

**Comment by zbeekman** [comment]
@outcoldman have you confirmed that this works? I just build ruby from source but didn't install it into a homebrew directory... I guess I'll try symlinking it in there...

**Comment by outcoldman** [comment]
@zbeekman I remember that it worked, have not used linuxbrew for a while

**Comment by zbeekman** [comment]
yes it seems to have worked fine! (Just FYI, I symlinked into `bin`... perhaps the cleverest way to do this would be to grab a version of ruby older than what's currently available in homebrew and install it in the Cellar, and then brew link it... that way you could upgrade ruby using linuxbrew and then unlink or remove the manual install...

**Comment by sjackman** [comment]
I haven't tried it, but there's also Traveling Ruby: http://phusion.github.io/traveling-ruby/

**Comment by sjackman** [comment]
I'd recommend install Ruby somewhere else other than `~/.linuxbrew` and then just symlink `ruby` into `~/.linuxbrew/bin/ruby`. I've done this myself to bootstrap systems without ruby.

**Comment by zbeekman** [comment]
Thanks, that's exactly what I ended up doing and it worked like a charm!

**Comment by sjackman** [comment]
Glad to hear it, Izaak!
