### ISSUE TITLE
All formulas require gcc now

### ISSUE THREAD

**Issue by nemith** [Homebrew/linuxbrew#415]
Before I was able to use the system GCC but now when i try to install a new formula it is saying:

```
$ brew reinstall weechat
==> Reinstalling weechat with --with-aspell, --with-python, --with-ruby, --with-curl, --with-perl
Error: weechat cannot be built with any available compilers.
To install this formula, you may need to:
  brew install gcc
```

**Comment by sjackman** [comment]
The system compiler must be named `gcc-4.x`. What version is your system compiler? Please report `gcc --version` and `ls /usr/bin/gcc-4.?`

**Comment by sjackman** [comment]
See also [Create symlinks for gcc](https://github.com/Homebrew/linuxbrew/wiki/Standalone-Installation#create-symlinks-for-gcc)

**Comment by Mikaela** [comment]
This is probably somewhat unrelated, but I have been wondering why does Linuxbrew always want to use GCC while OS X uses Clang which is also available on Linux and would be my preferred compiler in `$CC` and `$CXX`

Also what is wrong with `/usr/bin/gcc` and `/usr/bin/g++` ?

**Comment by nemith** [comment]
Looks like it should work for me....
```
$ gcc --version 
gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
  
$ ls /usr/bin/gcc-4.*                                                                                                                                                                                                                  
/usr/bin/gcc-4.8
```

**Comment by sjackman** [comment]
On Mac OS `/usr/bin/gcc` is actually clang emulating GCC 4.2.1. It's very weird. Disabling that logic in Homebrew has been more trouble than it's worth. Nice distributions like Ubuntu and Debian already contain files named appropriately, `gcc-4.9`.

**Comment by sjackman** [comment]
Have you been able to successfully compile and install clang using Linuxbrew? I haven't. Did you use `brew install llvm --with-clang`? See #382

**Comment by sjackman** [comment]
If you did have `/usr/bin/clang` installed, I *think* it would be the default compiler already, but I haven't tested that.

**Comment by Mikaela** [comment]
> On Mac OS /usr/bin/gcc is actually clang emulating GCC 4.2.1. It's very weird. Disabling that logic in Homebrew has been more trouble than it's worth. Nice distributions like Ubuntu and Debian already contain files named appropriately, gcc-4.9.

I see.

> Have you been able to successfully compile and install clang using Linuxbrew? I haven't. Did you use brew install llvm --with-clang? See #382

No, I haven't tried that and I am usaing system-wide installation which is from Debian Stable and very old so I should probably try that sometime.

> If you did have /usr/bin/clang installed, I think it would be the default compiler already, but I haven't tested that.

My `$CC` says `clang` and `$CXX` `clang++`, but they aren't used.

```zsh
% which clang && which clang++
/usr/bin/clang
/usr/bin/clang++
```

I know surely that they aren't used, because of Python which I have installed with Linuxbrew and it says to be compiled with GCC 4.7.2.


```py
% python3
Python 3.4.3 (default, May  9 2015, 06:38:10) 
[GCC 4.7.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.version
'3.4.3 (default, May  9 2015, 06:38:10) \n[GCC 4.7.2]'
>>> 
```

**Comment by nemith** [comment]
Creating the links worked.  Seems like something that linuxbrew could do, but not important.  I was just confused as it worked before I updated.  I'll leave this open in case you want to continue discussions but feel free to close.

**Comment by sjackman** [comment]
> My $CC says clang and $CXX clang++, but they aren't used.

`CC` and `CXX` are ignore by Homebrew. Use `HOMEBREW_CC=clang` instead. There is no `HOMEBREW_CXX`. The C++ compiler is inferred from the C compiler. The value of `/usr/bin/cc` is used as the default compiler (I believe).

**Comment by sjackman** [comment]
> Creating the links worked. Seems like something that linuxbrew could do

Yes, I agree. I just haven't got around to it. =/

**Comment by Mikaela** [comment]
> CC and CXX are ignore by Homebrew. Use HOMEBREW_CC=clang instead. There is no HOMEBREW_CXX. The C++ compiler is inferred from the C compiler. The value of /usr/bin/cc is used as the default compiler (I believe).

This appears to work as now my reinstalled Python 3 says `[GCC 4.2.1 Compatible Debian Clang 3.0 (tags/RELEASE_30/final)] on linux`.

**Comment by sjackman** [comment]
Great. Glad to hear it.
