### ISSUE TITLE
Help: deleted openssl now can't do anything

### ISSUE THREAD

**Issue by tseemann** [Homebrew/linuxbrew#419]
I was having trouble getting "brew install python3" linking against openssl, so i ended up doing "brew uninstall --force openssl"... now nothing works. 

I've tried a couple of things without luck. Any ideas to help this reborn n00b?

```
brew install openssl
==> Downloading https://www.openssl.org/source/openssl-1.0.2a.tar.gz
Already downloaded: /home/tseemann/.cache/Homebrew/openssl-1.0.2a-1.tar.gz
Error: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory - /bio/linuxbrew/Cellar/ruby/2.2.2/lib/ruby/2.2.0/x86_64-linux/digest/sha2.so
```

```
/usr/bin/ruby /bio/linuxbrew/Library/brew.rb install openssl
/bio/linuxbrew/Library/Homebrew/config.rb:36:in `initialize': no implicit conversion of nil into String (TypeError)
        from /bio/linuxbrew/Library/Homebrew/config.rb:36:in `new'
```

**Comment by tseemann** [comment]
I've just started from scratch again.

**Comment by sjackman** [comment]
My best suggestion would be to try `ln -sf /usr/bin/ruby /bio/linuxbrew/bin/ruby`. It may or may not have worked, but it was worth a shot. It would be really nice of Linuxbrew if it were to curate a list of packages that if removed would very likely break everything very nicely. I believe Debian does this. A good start would be the dependencies of ruby and gcc.

**Comment by tseemann** [comment]
I did try exactly that symlink trick but it failed with the old "minitest" bug that I encountered when I first got into Linuxbrew.
