### ISSUE TITLE
python - ImportError: No module named '_ssl'

### ISSUE THREAD

**Issue by tseemann** [Homebrew/linuxbrew#420]
Doing a fresh install of everything, getting critical errors trying to use python:
(openssl is installed - brew and system)

```
% brew install python3
% pip
Traceback (most recent call last):
  File "/bio/linuxbrew/bin/pip", line 9, in <module>
    load_entry_point('pip==6.1.1', 'console_scripts', 'pip')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 552, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2672, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2345, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2351, in resolve
  File "/bio/linuxbrew/Cellar/python/2.7.10/lib/python2.7/site-packages/pip-6.1.1-py2.7.egg/pip/__init__.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/bio/linuxbrew/Cellar/python/2.7.10/lib/python2.7/site-packages/pip-6.1.1-py2.7.egg/pip/vcs/mercurial.py", line 10, in <module>
    from pip.download import path_to_url
  File "/bio/linuxbrew/Cellar/python/2.7.10/lib/python2.7/site-packages/pip-6.1.1-py2.7.egg/pip/download.py", line 32, in <module>
    from pip._vendor import requests, six
  File "/bio/linuxbrew/Cellar/python/2.7.10/lib/python2.7/site-packages/pip-6.1.1-py2.7.egg/pip/_vendor/__init__.py", line 92, in load_module
    raise ImportError("No module named '%s'" % (name,))
ImportError: No module named 'pip._vendor.requests'
```

```
% brew install python3
% pip3

Traceback (most recent call last):
  File "/bio/linuxbrew/bin/pip3", line 9, in <module>
    load_entry_point('pip==6.1.1', 'console_scripts', 'pip3')()
  File "/bio/linuxbrew/opt/python3/lib/python3.4/site-packages/setuptools-15.2-py3.4.egg/pkg_resources/__init__.py", line 552, in load_entry_point
  File "/bio/linuxbrew/opt/python3/lib/python3.4/site-packages/setuptools-15.2-py3.4.egg/pkg_resources/__init__.py", line 2672, in load_entry_point
  File "/bio/linuxbrew/opt/python3/lib/python3.4/site-packages/setuptools-15.2-py3.4.egg/pkg_resources/__init__.py", line 2345, in load
  File "/bio/linuxbrew/opt/python3/lib/python3.4/site-packages/setuptools-15.2-py3.4.egg/pkg_resources/__init__.py", line 2351, in resolve
  File "/bio/linuxbrew/opt/python3/lib/python3.4/site-packages/pip-6.1.1-py3.4.egg/pip/__init__.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/bio/linuxbrew/opt/python3/lib/python3.4/site-packages/pip-6.1.1-py3.4.egg/pip/vcs/mercurial.py", line 10, in <module>
    from pip.download import path_to_url
  File "/bio/linuxbrew/opt/python3/lib/python3.4/site-packages/pip-6.1.1-py3.4.egg/pip/download.py", line 32, in <module>
    from pip._vendor import requests, six
  File "/bio/linuxbrew/opt/python3/lib/python3.4/site-packages/pip-6.1.1-py3.4.egg/pip/_vendor/requests/__init__.py", line 59, in <module>
    from .models import Request, Response, PreparedRequest
  File "/bio/linuxbrew/opt/python3/lib/python3.4/site-packages/pip-6.1.1-py3.4.egg/pip/_vendor/requests/models.py", line 19, in <module>
    from .packages.urllib3.fields import RequestField
  File "/bio/linuxbrew/opt/python3/lib/python3.4/site-packages/pip-6.1.1-py3.4.egg/pip/_vendor/requests/packages/urllib3/__init__.py", line 10, in <module>
    from .connectionpool import (
  File "/bio/linuxbrew/opt/python3/lib/python3.4/site-packages/pip-6.1.1-py3.4.egg/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 31, in <module>
    from .connection import (
  File "/bio/linuxbrew/opt/python3/lib/python3.4/site-packages/pip-6.1.1-py3.4.egg/pip/_vendor/requests/packages/urllib3/connection.py", line 45, in <module>
    from .util.ssl_ import (
  File "/bio/linuxbrew/opt/python3/lib/python3.4/site-packages/pip-6.1.1-py3.4.egg/pip/_vendor/requests/packages/urllib3/util/__init__.py", line 5, in <module>
    from .ssl_ import (
  File "/bio/linuxbrew/opt/python3/lib/python3.4/site-packages/pip-6.1.1-py3.4.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py", line 12, in <module>
    import ssl
  File "/bio/linuxbrew/opt/python3/lib/python3.4/ssl.py", line 97, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: No module named '_ssl'
```

**Comment by tseemann** [comment]
I found this "warning" error in 02.make - it seems to be using -L/usr/local/lib which is empty on Linux.

```
building '_ssl' extension
/bio/linuxbrew/bin/gcc-5 -pthread -fPIC -fno-strict-aliasing -Os -w -pipe -march=core2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes
 -I. -IInclude -I./Include -I/usr/local/include -I/tmp/python20150531-39238-z87k0v/Python-2.7.10/Include -I/tmp/python20150531-39238-z87
k0v/Python-2.7.10 -c /tmp/python20150531-39238-z87k0v/Python-2.7.10/Modules/_ssl.c -o build/temp.linux-x86_64-2.7/tmp/python20150531-392
38-z87k0v/Python-2.7.10/Modules/_ssl.o
/bio/linuxbrew/bin/gcc-5 -pthread -shared -L/bio/linuxbrew/lib -Wl,-rpath,/bio/linuxbrew/lib -L/bio/linuxbrew/lib -Wl,-rpath,/bio/linuxb
rew/lib -fno-strict-aliasing -Os -w -pipe -march=core2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I. -IInclude -I./Include -isys
tem/bio/linuxbrew/include build/temp.linux-x86_64-2.7/tmp/python20150531-39238-z87k0v/Python-2.7.10/Modules/_ssl.o -L/bio/linuxbrew/lib
-L/usr/local/lib -L. -lssl -lcrypto -lpython2.7 -o build/lib.linux-x86_64-2.7/_ssl.so
*** WARNING: renaming "_ssl" since importing it failed: build/lib.linux-x86_64-2.7/_ssl.so: undefined symbol: SSLv2_method
```

**Comment by tseemann** [comment]
Also found this:

```
running build_ext
ldd: /bio/linuxbrew/opt/readline/lib/libhistory.dylib: No such file or directory
```

**Comment by sjackman** [comment]
The readline error is caused by https://github.com/Homebrew/linuxbrew/blob/master/Library/Formula/python3.rb#L118-L120
That line is also in `python.rb`, so I'm guessing it's innocuous.

**Comment by sjackman** [comment]
It is looking is `/usr/local/lib`, but it's also looking in `-L/bio/linuxbrew/lib`.
> `/bio/linuxbrew/bin/gcc-5 -pthread -shared -L/bio/linuxbrew/lib -Wl,-rpath,/bio/linuxbrew/lib -L/bio/linuxbrew/lib -Wl,-rpath,/bio/linuxbrew/lib -fno-strict-aliasing -Os -w -pipe -march=core2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I. -IInclude -I./Include -isystem/bio/linuxbrew/include build/temp.linux-x86_64-2.7/tmp/python20150531-39238-z87k0v/Python-2.7.10/Modules/_ssl.o -L/bio/linuxbrew/lib -L/usr/local/lib -L. -lssl -lcrypto -lpython2.7 -o build/lib.linux-x86_64-2.7/_ssl.so`

**Comment by sjackman** [comment]
`build/lib.linux-x86_64-2.7/_ssl.so: undefined symbol: SSLv2_method`

Can you report the output of
`nm -D /bio/linuxbrew/lib/libopenssl.so |grep SSLv2_method`?

**Comment by tseemann** [comment]
```
brew list openssl
/bio/linuxbrew/Cellar/openssl/1.0.2a-1/bin/c_rehash
/bio/linuxbrew/Cellar/openssl/1.0.2a-1/bin/openssl
/bio/linuxbrew/Cellar/openssl/1.0.2a-1/include/openssl/ (75 files)
/bio/linuxbrew/Cellar/openssl/1.0.2a-1/lib/engines/ (12 files)
/bio/linuxbrew/Cellar/openssl/1.0.2a-1/lib/pkgconfig/ (3 files)
/bio/linuxbrew/Cellar/openssl/1.0.2a-1/lib/ (6 files)
/bio/linuxbrew/Cellar/openssl/1.0.2a-1/share/man/ (1537 files)
```

I think this one could be a problem:

```
nm -D /bio/linuxbrew/lib/libopenssl.so |grep SSLv2_method
nm: '/bio/linuxbrew/lib/libopenssl.so': No such file
```

Here is the openssl formula: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/openssl.rb

**Comment by sjackman** [comment]
My best guess is that Python is using the headers from your system's version of OpenSSL, but the libraries from the Linuxbrew version. It'll take some troubleshooting to sort out the mess. A work around is to remove either the system version of the Homebrew version of OpenSSL before compiling Python 3.

**Comment by tseemann** [comment]
All the later errors are for Python 2. You can't really remove openssl native (tools depend on it) or Linuxbrew (as you can never reinstall it). Catch-22 !

**Comment by sjackman** [comment]
Yep, it's a problem. The Python build scripts do really nasty things adding `/usr/lib` and `/usr/local/lib` explicitly to the search path, when it should leave it up to the user. I'm afraid I don't have an easy solution for you. I believe that this is primarily an upstream bug. Perhaps you open an issue with the Python development team.

superenv could be a potential fix, because it would allow us to remove the nasty `/usr/lib` and `/usr/local/lib` search from the `cc` command line. See #266

**Comment by cesarjorgemartinez** [comment]
Linux workaround:
brew install pyenv
pyenv install 2.7.10
Installed Python-2.7.10 to /home/user/.pyenv/versions/2.7.10
cp /home/user/.pyenv/versions/2.7.10/lib/python2.7/lib-dynload/_ssl.so /home/user/.linuxbrew/Cellar/python/2.7.10/lib/python2.7/lib-dynload

rm /home/user/.linuxbrew/Cellar/python/2.7.10/lib/python2.7/lib-dynload/_ssl_failed.so
chmod 444 /home/user/.linuxbrew/Cellar/python/2.7.10/lib/python2.7/lib-dynload/_ssl.so

**Comment by sjackman** [comment]
Thanks for the workaround, Cesar. That's a fine idea.

**Comment by tdsmith** [comment]
This is probably caused by the changes I made in Homebrew/homebrew to remove env=std support from the python formula. Modifying CFLAGS and LDFLAGS to pick up openssl, sqlite3, and readline is probably necessary.

**Comment by sjackman** [comment]
Ah, seems a good time to mention then that Dmitry @veprbl implemented superenv support for Linuxbrew in https://github.com/Homebrew/linuxbrew/pull/266 ages ago, but I haven't found the time to test it.

**Comment by razvanc87** [comment]
How is it possible that `pyenv` is able to build the executables without a problem and the modules, but `brew` can't? I have the same issue and even though I tried the workaround mentioned above, that is, to copy the _sso.so and _tkinter.so (I also have problem with this with `brew`) from `pyenv` but `brew` keeps telling me that python wasn't installed properly and do a `brew postinstall`, but when I do that I get some weird segmentation fault things (don't have the logs any more, I stopped to trying to fix this and am using the `pyenv` executables now). This happened to me for Python 2.7, didn't bother trying with for Python 3 with `brew`...

**Comment by vincentl** [comment]
openssl formula configures with 'no-ssl2' and so SSLv2_method is not available in the dynamic library.

Edit openssl formula ($ brew edit openssl) and delete the 'no-ssl2' line.

$ brew reinstall openssl
$ brew reinstall python

And now pip should work.

**Comment by tdsmith** [comment]
The problem is that you're building against the system openssl headers but linking to the Homebrew library, which is configured differently.

**Comment by vincentl** [comment]
In the 02.make log file, the link line for _ssl.so has

... -L/path/to/linuxbrew/lib -L/usr/local/lib -L. -lssl ...

so it is picking up the openssl linuxbrew library and not the system openssl. And it seems that pip requires SSL2, so if you brew openssl with no-ssl2, pip breaks.  

I tested pip with the modified openssl build, it it works.

Is there a way to turn off SSL2 during python configuration?

**Comment by tdsmith** [comment]
pip does not require ssl2.

> Is there a way to turn off SSL2 during python configuration?

Yes: ensure that python is built with openssl headers that reflect the configuration of the openssl library against which it will be linked. The changes that were made in Homebrew/homebrew were improper for Linuxbrew. The Linuxbrew python formula should be amended to add the brewed openssl include directory to CFLAGS.

**Comment by sjackman** [comment]
> The Linuxbrew python formula should be amended to add the brewed openssl include directory to CFLAGS.

:+1: Yes, please!

**Comment by tdsmith** [comment]
What distribution are people having trouble with? I'm having trouble reproducing on Debian and OpenSuSE.

**Comment by sjackman** [comment]
Good question. The Docker build on Ubuntu works fine for me. https://registry.hub.docker.com/u/sjackman/linuxbrew-standalone/

**Comment by tdsmith** [comment]
I just reproduced on CentOS 7, but it occurs to me that it's probably working on Ubuntu because Ubuntu's OpenSSL has SSLv2 disabled by default in Trusty.

**Comment by tseemann** [comment]
Yes I am on genuine RHEL 7 so similar to Centos.

**Comment by tdsmith** [comment]
You could try the fix in #460.

**Comment by yesimon** [comment]
Just randomly browsing this issue, I've always modified the `setup.py` to examine `CFLAGS/LDFLAGS` by extending the Mac detection logic in the python formula. See https://github.com/yesimon/linuxbrew/commit/476752c59d995ee26e402617cbeabcd95cd32c52

Also putting an `ENV['CFLAGS'] = '-g -O2 -I#{HOMEBREW_PREFIX}/include'` and possibly `ENV LDFLAGS` too.

**Comment by sjackman** [comment]
That seems like the right idea. Would you send that patch upstream to Python, Simon? I'd merge it in Linuxbrew as well if @tseemann or someone can confirm that it resolves this issue for them.

**Comment by yesimon** [comment]
I ran into this issue a while back and it looks like the bug has been around for a year or so. http://bugs.python.org/issue21571 The only thing that holding this back look like testing for regressions on many linux distros, which is probably time consuming and error prone :(

**Comment by tseemann** [comment]
A few weeks ago I managed to "brew install python" (2.7.10) on RHEL 7.  

I think a new version of brew "openssl" somehow allowed it to work but I am not sure.

**Comment by hkawaji** [comment]
I came across the exactly the same problem, even with python 2.7.10. In my case, the problem was mainly caused by python formula prerequisite: it requires SSLv2 method supported but the recent formula of openssl decided not to support it for security reason. Here is a dirty patch for the formula of python and openssl:

  https://gist.github.com/hkawaji/33746654ea2271573c97

which makes these changes:

- make openssl to support SSLv2_method (while this is not recommended for security reason; ideally python formula has to be updated not to require this change of openssl)
- enforce to build gdbm module
- change to use ".so" , instead of .dylib  for readline

**Comment by prologic** [comment]
Running into the same issue as well. CentOS 6.7

**Comment by armish** [comment]
had the same issue on a server running CentOS release 6.6. Removing the `no-ssl2`line from the openssl formulae and reinstalling both openssl and python did the trick for me.

**Comment by sjackman** [comment]
Thanks for the tip, Arman.

**Comment by beatorizu** [comment]
If you are using GAE, you need add ssl to app.yaml file:

libraries:
- name: ssl
  version: latest

I hope this help.

**Comment by sjackman** [comment]
This issue should hopefully be fixed now. I'd appreciate if anyone that was affected by this issue can confirm that it is in fact fixed.

**Comment by armish** [comment]
Confirming that this issue is now fixed for me with a fresh brew installation:

```
$ cat /etc/centos-release 
CentOS release 6.4 (Final)

$ brew --version
Homebrew 0.9.5 (no git repository)

$ brew list
gdbm  makedepend  ncurses  openssl  pkg-config	python	python3  readline  sqlite  unzip  xz  zlib

$ python2
Python 2.7.11 (default, Jan 19 2016, 12:32:08) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 

$ python3
Python 3.5.1 (default, Jan 19 2016, 12:56:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

**Comment by sjackman** [comment]
Yeah! Thanks should really go to @tdsmith, @tseemann and everyone else who helped troubleshoot this issue.
