### ISSUE TITLE
BOOST:  `dump': can't dump anonymous class #<Module:0x000000015912e8>::Boost (TypeError)

### ISSUE THREAD

**Issue by LeeBergstrand** [Homebrew/linuxbrew#422]
```shell
brew install boost
==> Downloading https://downloads.sourceforge.net/project/boost/boost/1.58.0/boost_1_58_0.tar.bz2
Already downloaded: /home/leebergstrand/.cache/Homebrew/boost-1.58.0.tar.bz2
==> ./bootstrap.sh --prefix=/home/leebergstrand/.linuxbrew/Cellar/boost/1.58.0 --libdir=/home/leebergstrand/.linuxbrew/Cellar/boost/1.58.0/lib --without-icu --without-libraries=python,mpi
==> ./b2 --prefix=/home/leebergstrand/.linuxbrew/Cellar/boost/1.58.0 --libdir=/home/leebergstrand/.linuxbrew/Cellar/boost/1.58.0/lib -d2 -j1 --layout=tagged --user-config=user-config.jam install thr
...skipped <pbin.v2/libs/wave/build/gcc-4.8/release/link-static>libboost_wave.a for lack of bin.v2/libs/wave/build/gcc-4.8/release/link-static...
...skipped <p/home/leebergstrand/.linuxbrew/Cellar/boost/1.58.0/lib>libboost_wave.a for lack of /home/leebergstrand/.linuxbrew/Cellar/boost/1.58.0/lib...
...failed updating 286 targets...
...skipped 9409 targets...
...updated 3641 targets...
/home/leebergstrand/.linuxbrew/Library/Homebrew/build.rb:181:in `dump': can't dump anonymous class #<Module:0x000000015912e8>::Boost (TypeError)
        from /home/leebergstrand/.linuxbrew/Library/Homebrew/build.rb:181:in `rescue in <main>'
        from /home/leebergstrand/.linuxbrew/Library/Homebrew/build.rb:167:in `<main>'
Error: Suspicious failure
```

**Comment by xu-cheng** [comment]
This has been fixed by upstream in https://github.com/Homebrew/homebrew/commit/2d1bc4df26f2d1abae81832c6decb5394b007f58. But it requires some time to let it sync to Linuxbrew.

**Comment by sjackman** [comment]
Thanks for the bug report, Lee, and thanks for the helpful comment, Xu.

**Comment by kilojoules** [comment]
@sjackman How can I use the 2d1bc4d formula in a brew install command? I am using osx homebrew and also encountered this error. 
The command which invoked this error was 
`$ brew install boost --with-mpi --without-single`
 Which resulted in:
`
==> Downloading https://downloads.sourceforge.net/project/boost/boost/1.58.0/boost_1_58_0.tar.bz2
Already downloaded: /Library/Caches/Homebrew/boost-1.58.0.tar.bz2
==> ./bootstrap.sh --prefix=/usr/local/Cellar/boost/1.58.0 --libdir=/usr/local/Cellar/boost/1.58.0/lib --without-icu --without-libraries=python
==> ./b2 --prefix=/usr/local/Cellar/boost/1.58.0 --libdir=/usr/local/Cellar/boost/1.58.0/lib -d2 -j4 --layout=tagged --user-config=user-config.jam install t
    cp "bin.v2/libs/wave/build/darwin-4.2.1/release/link-static/threading-multi/libboost_wave-mt.a"  "/usr/local/Cellar/boost/1.58.0/lib/libboost_wave-mt.a"

...failed updating 1 target...
...skipped 1 target...
...updated 12594 targets...
/usr/local/Library/Homebrew/build.rb:181:in `dump': can't dump anonymous class #<Module:0x007f9ba992c8f8>::Boost (TypeError)
	from /usr/local/Library/Homebrew/build.rb:181:in `rescue in <main>'
	from /usr/local/Library/Homebrew/build.rb:167:in `<main>'
Error: Suspicious failure
`

**Comment by xu-cheng** [comment]
You need to run `brew update` and try again. Then it should show the real error.

**Comment by kilojoules** [comment]
@xu-cheng Can you help me troubleshoot this error? Have I found a bug in the boost formula?

    $ $ brew install boost --with-mpi --without-single
    ==> Downloading https://downloads.sourceforge.net/project/boost/boost/1.58.0/boost_1_58_0.tar.bz2
    Already downloaded: /Library/Caches/Homebrew/boost-1.58.0.tar.bz2
    ==> ./bootstrap.sh --prefix=/usr/local/Cellar/boost/1.58.0 --libdir=/usr/local/Cellar/boost/1.58.0/lib --without-icu --without-libraries=python
    ==> ./b2 --prefix=/usr/local/Cellar/boost/1.58.0 --libdir=/usr/local/Cellar/boost/1.58.0/lib -d2 -j4 --layout=tagged --user-config=user-config.jam install t
    
        cp "bin.v2/libs/wave/build/darwin-4.2.1/release/link-static/threading-multi/libboost_wave-mt.a"  "/usr/local/Cellar/boost/1.58.0/lib/libboost_wave-mt.a"
    
    ...failed updating 1 target...
    ...skipped 1 target...
    ...updated 12594 targets...
    
    READ THIS: https://git.io/brew-troubleshooting
    

    $ brew update
    Already up-to-date.
    
    $ brew doctor
    Please note that these warnings are just used to help the Homebrew maintainers
    with debugging if you file an issue. If everything you use Homebrew for is
    working fine: please don't worry and just ignore them. Thanks!
    
    Warning: Setting DYLD_* vars can break dynamic linking.
    Set variables:
        DYLD_LIBRARY_PATH: :/usr/local/Dakota//bin:/usr/local/Dakota/lib
    
    Warning: Unbrewed dylibs were found in /usr/local/lib.
    If you didn't put them there on purpose they could cause problems when
    building Homebrew formulae, and may need to be deleted.
    
    Unexpected dylibs:
        /usr/local/lib/libcrypto.0.9.8.dylib
        /usr/local/lib/libcrypto.dylib
        /usr/local/lib/libklcskca.dylib
        /usr/local/lib/libklcsrt.dylib
        /usr/local/lib/libklcsstd.dylib
        /usr/local/lib/libklcstr.dylib
        /usr/local/lib/libklmspack.0.1.0.dylib
        /usr/local/lib/libklmspack.0.dylib
        /usr/local/lib/libklmspack.dylib
        /usr/local/lib/libssl.0.9.8.dylib
        /usr/local/lib/libssl.dylib
        /usr/local/lib/libz.1.2.5.dylib
        /usr/local/lib/libz.1.dylib
        /usr/local/lib/libz.dylib
    
    Warning: Some installed formula are missing dependencies.
    You should `brew install` the missing dependencies:
    
        brew install boost
    
    Run `brew missing` for more details.
    
    
    rking-2016

**Comment by xu-cheng** [comment]
Please report this issue to [Homebrew](https://github.com/Homebrew/homebrew/issues/new) with the output of `brew gist-logs boost`.

**Comment by kilojoules** [comment]
@xu-cheng Thanks for your help. I started a new issue [here](https://github.com/Homebrew/homebrew/issues/40494)
