### ISSUE TITLE
graphviz: Can't install using ipython

### ISSUE THREAD

**Issue by pujaarajan** [Homebrew/linuxbrew#424]
![screen shot 2015-06-04 at 9 27 45 am](https://cloud.githubusercontent.com/assets/10352446/7986257/170016d6-0a9c-11e5-9d52-9805b5ab1d64.png)

**Comment by sjackman** [comment]
I don't see any errors related to ipython, but it does look as though you're trying to install graphviz. Please report `brew gist-logs graphviz`

**Comment by pujaarajan** [comment]
![screen shot 2015-06-04 at 1 44 28 pm](https://cloud.githubusercontent.com/assets/10352446/7991707/d790c9cc-0abf-11e5-84cd-b01dca42328d.png)

**Comment by sjackman** [comment]
Please read the installation instructions at http://brew.sh/linuxbrew/

**Comment by iggyvolz** [comment]
It actually looks like pkg-config is the one causing the error:
>Installing graphviz dependency: pkg-config

**Comment by pujaarajan** [comment]
![screen shot 2015-06-05 at 2 43 10 pm](https://cloud.githubusercontent.com/assets/10352446/8013793/4ddd8f44-0b91-11e5-8418-ee878ad94632.png)

**Comment by pujaarajan** [comment]
How do I fix it? I am running Hadoop and Amazon Linux.

**Comment by pujaarajan** [comment]
![screen shot 2015-06-05 at 3 15 00 pm](https://cloud.githubusercontent.com/assets/10352446/8014468/a828a808-0b96-11e5-8ac5-646ee504e330.png)

**Comment by pujaarajan** [comment]
![screen shot 2015-06-05 at 3 21 19 pm](https://cloud.githubusercontent.com/assets/10352446/8014473/b11846e4-0b96-11e5-8dca-e524ef6822f0.png)

**Comment by pujaarajan** [comment]
![screen shot 2015-06-05 at 3 23 27 pm](https://cloud.githubusercontent.com/assets/10352446/8014485/d7778d04-0b96-11e5-8d5b-6f7df1a5ee87.png)

**Comment by iggyvolz** [comment]
Try ```chmod 755 $HOME```.  Linuxbrew is panicking because the home directory is world-writable.

**Comment by pujaarajan** [comment]
![screen shot 2015-06-05 at 3 52 04 pm](https://cloud.githubusercontent.com/assets/10352446/8015002/d8f14df6-0b9a-11e5-9fe6-2676f922e76d.png)

**Comment by saketkc** [comment]
`chmod -R 755 $HOME/`

**Comment by pujaarajan** [comment]
It says that operation is not permitted.

**Comment by saketkc** [comment]
I suspect  you made changes to your `$HOME` with `sudo`.

`sudo chown <username> $HOME`

**Comment by pujaarajan** [comment]
Operation is still not permitted

**Comment by pujaarajan** [comment]
Didn't get it to work; however I found another way to install graphviz. I appreciate your help!
