### ISSUE TITLE
Error: Invalid value for HOMEBREW_CC: gcc-5.1

### ISSUE THREAD

**Issue by sidaf** [Homebrew/linuxbrew#425]
Hi, I'm trying to get linuxbrew up and running on Fedora 22, but am hitting a few snags.

First error was:
```
$ brew install hello
Error: hello cannot be built with any available compilers.
To install this formula, you may need to:
  brew install gcc
```
From digging around in the issues list it appears that this may be due to not having correctly named gcc binary i.e `gcc-$version`.
```
$ ls /bin/gcc*
/bin/gcc  /bin/gcc-ar  /bin/gcc-nm  /bin/gcc-ranlib
```
So did the following as suggested elsewhere:
```
prefix=~/.linuxbrew
ln -s $(which gcc) $prefix/bin/gcc-$(gcc -dumpversion |cut -d. -f1,2)
ln -s $(which g++) $prefix/bin/g++-$(g++ -dumpversion |cut -d. -f1,2)
ln -s $(which gfortran) $prefix/bin/gfortran-$(gfortran -dumpversion |cut -d. -f1,2)
export HOMEBREW_CC=gcc-$(gcc -dumpversion |cut -d. -f1,2)
```
I know get the following error:
```
$ brew install hello
Error: Invalid value for HOMEBREW_CC: gcc-5.1
```
Anybody have any ideas?

**Comment by sjackman** [comment]
Ah, drat. Yes, those instructions will have to be updated. The symlink should be called `gcc-5` rather than `gcc-5.1`.

**Comment by sidaf** [comment]
That did the trick, thank you.
