### ISSUE TITLE
Unable install gcc with gcc version 5.1

### ISSUE THREAD

**Issue by coder5** [Homebrew/linuxbrew#428]
i'm trying install using
`brew install gcc`
error:
`To install this formula, you may need to:
  brew install gcc`

`gcc -dumpversion`
`5.1.0`

i'm using Arch Linux 4.0.4-2-ARCH

**Comment by sjackman** [comment]
Try
```sh
ln -s `which gcc` `brew --prefix`/bin/
```

**Comment by coder5** [comment]
thanks it's almost worked
now i got this error 
> configure: error: in `/home/haiarch/tmp/isl20150608-17992-9ml488/isl-0.14.1':
> configure: error: C++ preprocessor "/lib/cpp" fails sanity check
> See `config.log' for more details

**Comment by sjackman** [comment]
Please report `brew gist-logs isl`

**Comment by coder5** [comment]
ok i did 
https://gist.github.com/anonymous/7c4d9bc18fd70cdbbce4

**Comment by sjackman** [comment]
https://gist.github.com/anonymous/7c4d9bc18fd70cdbbce4#file-config-log-L584
```
./configure: line 1882: /home/haiarch/.linuxbrew/bin/g++-5: No such file or directory
```

**Comment by sjackman** [comment]
Try
```
ln -s `which g++` `brew --prefix`/bin/g++-5
```

**Comment by coder5** [comment]
now i got this
```^[[6;7~Makefile:20406: recipe for target 'stage1-bubble' failed
make[1]: *** [stage1-bubble] Error 2
make[1]: Leaving directory '/tmp/gcc20150609-24602-11484od/gcc-5.1.0/build'
Makefile:20726: recipe for target 'bootstrap' failed
make: *** [bootstrap] Error 2```

**Comment by sjackman** [comment]
Please report `brew gist-logs gcc`
