### ISSUE TITLE
php55: /usr/sbin/apxs: No such file or directory

### ISSUE THREAD

**Issue by fr4ngus** [Homebrew/linuxbrew#430]
Hi,

I try to install php55 with homebrew but I have the following problem:

3. Apache was not built using --enable-so (the apxs usage page is displayed)

The output of /usr/sbin/apxs follows:
```
./configure: line 8426: /usr/sbin/apxs: No such file or directory
configure: error: Aborting
```
Thank you for your help.

**Comment by sjackman** [comment]
I'm afraid that I don't have the time to troubleshoot individual formula. Please submit a pull request if you find a fix for this issue.

**Comment by iggyvolz** [comment]
How did you install apache?  If you did it via homebrew, it shouldn't be pointing to /usr/sbin at all.

**Comment by fr4ngus** [comment]
Yes, thank you !
