### ISSUE TITLE
mysql failed to build on Ubuntu 12.04 ( "Precise" )

### ISSUE THREAD

**Issue by mclo** [Homebrew/linuxbrew#431]
<pre>
<code>
==> Installing mysql
==> Downloading https://cdn.mysql.com/Downloads/MySQL-5.6/mysql-5.6.25.tar.gz
######################################################################## 100,0%
==> cmake . -DCMAKE_INSTALL_PREFIX=/home/mclo/.linuxbrew/Cellar/mysql/5.6.25 -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -DMYSQL

-- Configuring incomplete, errors occurred!
See also "/tmp/mysql20150610-5721-g9mylz/mysql-5.6.25/CMakeFiles/CMakeOutput.log".
See also "/tmp/mysql20150610-5721-g9mylz/mysql-5.6.25/CMakeFiles/CMakeError.log".

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

These open issues may also help:
mysql-connector-odbc doesn't depend on mysql (https://github.com/Homebrew/homebrew/issues/39126)
mysql failed to build on 10.10 (https://github.com/Homebrew/homebrew/issues/33448)
mysql-connector-c++ cannot build with mariadb  (https://github.com/Homebrew/homebrew/issues/34578)
Packages with --with-mysql option not satisfied by mariadb (https://github.com/Homebrew/homebrew/issues/32973)
</code>
</pre>
debugging information: https://gist.github.com/anonymous/2ddfa12aea552b6cd5fe

I've tried to see CMakeOutput.log and CMakeError.log but, the files don't exist.

**Comment by sjackman** [comment]
https://gist.github.com/anonymous/2ddfa12aea552b6cd5fe#file-01-cmake-L758-L760
```
-- EDITLINE_LIBRARY EDITLINE_LIBRARY-NOTFOUND
CMake Error at cmake/readline.cmake:206 (MESSAGE):
  Cannot find system editline libraries.
```

**Comment by sjackman** [comment]
Try `brew install homebrew/dupes/libedit mysql`

**Comment by sjackman** [comment]
See also #288

**Comment by mclo** [comment]
Great!, yes it's the same library that in https://github.com/Homebrew/linuxbrew/issues/288
<code>readline</code> is provided by <code>libedit</code>
<pre><code>brew install homebrew/dupes/libedit mysql</code></pre> Works !!!

**Comment by hughperkins** [comment]
But... I think the Formula for mysql should somehow contain the correct dependencies?

**Comment by sjackman** [comment]
It does. See d084460 and https://github.com/Homebrew/linuxbrew/blob/master/Library/Formula/mysql.rb#L33

**Comment by hughperkins** [comment]
Hmmm, on my browser, it shows 'libedit', not 'homebrew/dupes/libedit', see screenshot:

![screenshot-libedit](https://cloud.githubusercontent.com/assets/123560/12230800/c8e5387a-b84a-11e5-9332-15c5aed74eaf.png)

And, more concretely, installing mysql fails, with error about missing dependency libedit.  I have to `brew install homebrew/dupes/libedit` by hand, in order for mysql to install correctly.

**Comment by sjackman** [comment]
I've changed the dependency from `libedit` to `homebrew/dupes/libedit` in fffd8fb
Try `brew update` and `brew install mysql`
If that fails, please report
`brew gist-logs mysql`

**Comment by hughperkins** [comment]
Thanks! :-)
