### ISSUE TITLE
libevent: Can't install packages in CentOS 6.5

### ISSUE THREAD

**Issue by aftnix** [Homebrew/linuxbrew#432]
Homebrew installed as root(It's a remote VPS).

Installation stops with : 

    [root@srv6874 ~]# brew install libevent
    ==> Installing dependencies for libevent: pkg-config, makedepend, op
    ==> Installing libevent dependency: pkg-config
    Error: pkg-config cannot be built with any available compilers.
    To install this formula, you may need to:
    brew install gcc

But i do have gcc-4.4.7

**Comment by sjackman** [comment]
Follow these instructions: [To use GCC 4.4 on CentOS 5](https://github.com/Homebrew/linuxbrew/wiki/Standalone-Installation#to-use-gcc-44-on-centos-5)
