### ISSUE TITLE
openssl failed to install on Linux Ubuntu 15.04 (Vivid Vervet)

### ISSUE THREAD

**Issue by UnsungHero97** [Homebrew/linuxbrew#446]
I have a server on DigitalOcean running Ubuntu 15, and I'm trying to install OpenSSL, but it's failing:

    hristo@test:~$ brew install openssl
    ==> Downloading https://www.openssl.org/source/openssl-1.0.2c.tar.gz
    Already downloaded: /home/hristo/.cache/Homebrew/openssl-1.0.2c.tar.gz
    ==> perl ./Configure --prefix=/home/hristo/.linuxbrew/Cellar/openssl/1.0.2c --openssldir=/home/hristo/.linuxbrew/etc/openssl no-ssl2 zlib-dynamic shared enable-cms linux-x86_64
    ==> make depend
    ==> make
    Makefile:88: recipe for target 'subdirs' failed
    make[1]: *** [subdirs] Error 1
    make[1]: Leaving directory '/tmp/openssl20150620-4632-500bkz/openssl-1.0.2c/crypto'
    Makefile:282: recipe for target 'build_crypto' failed
    make: *** [build_crypto] Error 1

    READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

    These open issues may also help:
    openssl fails "make test" on 10.10.3 (https://github.com/Homebrew/homebrew/issues/40892)
    Installing Elixir fails due to OpenSSL errors. (https://github.com/Homebrew/homebrew/issues/33218)

One thing that is confusing is why the output shows "openssl fails "make test" on 10.10.3"... is the install thinking it's running on OS X and not Linux?

I've created a gist with all the output from running the install: 
https://gist.github.com/UnsungHero97/981e233b2278ba369bd1

What am I missing?

**Comment by iggyvolz** [comment]
Try running brew install zlib, if it's not already installed.

**Comment by UnsungHero97** [comment]
Here's what I got:

    hristo@test:~$ brew install zlib
    Error: No available formula for zlib 
    Searching formulae...
    lzlib
    Searching taps...
    homebrew/dupes/zlib

**Comment by DoomHammer** [comment]
homebrew/dupes/zlib should be the one you are looking for.

**Comment by iggyvolz** [comment]
brew install homebrew/dupes/zlib.  I always tap homebrew/dupes so I always
forget it's there.

**Comment by UnsungHero97** [comment]
nice! that worked. thanks!

**Comment by iggyvolz** [comment]
I'll have a PR up shortly so this doesn't happen again in the future.  Unfortunately, everything's copied straight from Homebrew for mac, where everything in dupes is already installed.

**Comment by sjackman** [comment]
Thanks, Iggy!
