### ISSUE TITLE
Error: binutils cannot be built with any available compilers.

### ISSUE THREAD

**Issue by gitfoxi** [Homebrew/linuxbrew#452]
Following the standalone instructions homebrew can't install anything because it wants a gcc that only it can provide.

```
$ brew install glibc
==> Installing dependencies for glibc: binutils, linux-headers
==> Installing glibc dependency: binutils
Error: binutils cannot be built with any available compilers.
To install this formula, you may need to:
  brew install gcc
```

I had installed linuxbrew on this sytem before but today I wanted to just start over.

Previously, I went through this process and it worked great so I guess this is a new bug.

**Comment by gitfoxi** [comment]
As a workaround I went back to this commit:

```
commit c569aa8d12cb6566b70968fb5f82b1c272edecf6
Author: Shaun Jackman <sjackman@gmail.com>
Date:   Wed May 6 10:36:31 2015 -0700
```

And all is well. So, I figure, sometime between then and now homebrew got real uptight about which compilers you can use and linuxbrew didn't notice.

**Comment by gitfoxi** [comment]
Tried using `git bisect` to find the exact commit where it went bad but the technique doesn't work with linuxbrew because you always get:

```
Warning: Xcode is not installed. Most formulae need Xcode to build.
It can be installed from
  https://developer.apple.com/downloads
Error: Permission denied @ dir_s_mkdir - /Library
```

I guess some intermediate commits miss some patches.

**Comment by sjackman** [comment]
The GCC compiler must be named `gcc-4.x` or `gcc-5`. You can create a symlink for gcc and g++. Please report the output of
```
which -a gcc g++
gcc --version
```

**Comment by gitfoxi** [comment]
```
cavtools@vm bzip2-1.0.6]$ which -a gcc g++
/usr/bin/gcc
/usr/bin/g++
[cavtools@vm bzip2-1.0.6]$ gcc --version
gcc (GCC) 4.1.2 20080704 (Red Hat 4.1.2-55)
Copyright (C) 2006 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[cavtools@vm bzip2-1.0.6]$ gcc
gcc         gcc-4.4     gcc34       gcc44       gccmakedep
[cavtools@vm bzip2-1.0.6]$ gcc
```

I have gcc-4.4 in my path. I was aware of that issue so it's just a link to gcc44. I think this is a different issue. As I said, going back just a few months everything is okay.

**Comment by sjackman** [comment]
It may be pickier about the location of the symlink now. It may have to be in `$(brew --prefix)/bin` Perhaps that's a bug. Try

```sh
ln -s /usr/bin/gcc44 `brew --prefix`/bin/gcc-4.4
ln -s /usr/bin/g++44 `brew --prefix`/bin/g++-4.4
which -a gcc-4.4 g++-4.4
```

**Comment by gitfoxi** [comment]
Thanks. That did the trick.
