### ISSUE TITLE
Linuxbrew: "Package bash-completion was not found..." at command prompt.

### ISSUE THREAD

**Issue by villimagg** [Homebrew/linuxbrew#46]
I'm prompted with this error message when I open terminal in Fedora 20:

```
"Package bash-completion was not found in the pkg-config search path.
Perhaps you should add the directory containing `bash-completion.pc'
to the PKG_CONFIG_PATH environment variable
No package 'bash-completion' found
bash: /yum: No such file or directory"
```

I have isolated the problem and it is most definitely connected to Linuxbrew.

Please tell me what ever information is required for solving this.

Thank you.

**Comment by gawbul** [comment]
I'm having the same issue. Needed to install `pkg-config`for another package (I forget which now) and been getting the same error:

`
Package bash-completion was not found in the pkg-config search path.
Perhaps you should add the directory containing `bash-completion.pc'
to the PKG_CONFIG_PATH environment variable
No package 'bash-completion' found
bash: /yum: No such file or directory
`

**Comment by gawbul** [comment]
Don't know if this helps at all? http://stackoverflow.com/questions/20506610/where-do-i-install-custom-completions-for-a-python-command-line-script-on-osx

Will see if setting PKG_CONFIG_PATH with that helps?

**Comment by sjackman** [comment]
@gawbul Do you have `bash-completion` installed? `brew list --versions bash-completion`

**Comment by gawbul** [comment]
@sjackman tried it both with and without `bash-completion` installed.

**Comment by gawbul** [comment]
Doing a `find ~/ -name "bash-completion.pc"` doesn't find the `bash-completion.pc` file?

**Comment by sjackman** [comment]
`bash-completion` doesn't appear to install `bash-completion.pc`.

```
❯❯❯ brew list bash-completion |grep -c 'pc$'
0
```

**Comment by sjackman** [comment]
I bet that your `.bashrc` or `.bash_profile` uses `pkg-config` to set up `bash-completion` and that fails if the `PKG_CONFIG_PATH` is changed to not include that search directory. Linuxbrew does change the `PKG_CONFIG_PATH` when it's building software. I would recommend hard-coding the path to `bash-completion.pc` in your BASH startup file.

**Comment by gawbul** [comment]
Hard coded into `.bashrc` and that worked, thanks :+1:

**Comment by sjackman** [comment]
Grand. Thanks for the feedback.

**Comment by blitzter** [comment]
Hi @gawbul ,
I'm getting the exact same issue in my Fedora 22 machine.
What exactly was added to .bashrc as bash-completion.pc is not really there.

Can you please provide the addition to .bashrc so I and possibly others can fix the issue?

**Comment by gawbul** [comment]
Hi @blitzter. I did the following:
```
[smoss@bioserva ~]$ locate bash-completion.pc
/usr/share/pkgconfig/bash-completion.pc
```
So I added `export PKG_CONFIG_PATH=/usr/share/pkgconfig:$PKG_CONFIG_PATH` to my `.bashrc`.

**Comment by blitzter** [comment]
Thanks @gawbul ,
The error message is gone if the line mentioned above is added on top of .bashrc (before /etc/bashrc processing).

**Comment by gawbul** [comment]
Sorry, @blitzter, yes, I added it to the top of my `.bashrc`!

**Comment by Osndok** [comment]
I've started getting this message too (in a VM that is also using Fedora 20).

I understand *where* the message is being generated, from a stock fedora package ("yum-utils"):
```
$ grep -n pkg-config /etc/bash_completion.d/yum-utils.bash 
2:type -t _yum >/dev/null || . $(pkg-config --variable=completionsdir bash-completion)/yum
```

As I understand it, this message is "switched on" when a linuxbrew "pkg-config" binary is preferentially used over (earlier in the PATH than) the stock one by the yum-utils package in fedora.

So, then... ignoring the workaround for a moment... isn't the root issue either:
1. that linuxbrew pkg-config should be bottled (if it does not work for in the more general system-wide use), or
2. that linuxbrew pkg-config should also loop-in system package definitions by default (or as a fallback? if it is intended to replace the stock pkg-config)

?

**Comment by sjackman** [comment]
> that linuxbrew pkg-config should be bottled

I think perhaps you mean `keg_only`. You can `brew unlink pkg-config` if you like.

> that linuxbrew pkg-config should also loop-in system package definitions by default

We explicitly do not include system `pkg-config` files to avoid using system host libraries unintended, which may conflict with Linuxbrew libraries. You can modify your `PKG_CONFIG_PATH` to use both.

Neither of these workarounds is a clear win as both of these solutions have their own downsides.
