### ISSUE TITLE
No available formula for zlib

### ISSUE THREAD

**Issue by albertz** [Homebrew/linuxbrew#466]
```
$ brew install tmux
Error: No available formula for zlib (dependency of tmux)
Searching formulae...
lzlib
Searching taps...
homebrew/dupes/zlib
```

I think there should be a formula for zlib. Somewhat confusing.

And I tried this:

```
$ brew tap homebrew/dupes/zlib
Error: Invalid tap name
```

**Comment by DomT4** [comment]
You want either `brew install homebrew/dupes/zlib` or `brew tap homebrew/dupes && brew install zlib`.

**Comment by sjackman** [comment]
`zlib` is a dependency of `openssl`, which is a dependency of `libevent`, which is a dependency of `tmux`.

`openssl` should depend on `homebrew/dupes/zlib` rather than `zlib` but doesn't due to issues with cyclic dependencies. See https://github.com/Homebrew/linuxbrew/pull/447
