### ISSUE TITLE
Can't install node

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/linuxbrew#467]
_From @rtuider on July 7, 2015 12:39_

Hi guys,

when trying to install node under Redhat7 I get this error:

```
[local]$ brew install node
==> Installing node dependency: pkg-config
Error: pkg-config cannot be built with any available compilers.
To install this formula, you may need to:
  brew install gcc
```

If I install gcc as mentioned I get this:
```
[etc]$ brew install gcc
==> Installing dependencies for gcc: gmp, xz, mpfr, libmpc, isl
==> Installing gcc dependency: gmp
Error: gmp cannot be built with any available compilers.
To install this formula, you may need to:
  brew install gcc
```

I have this compiler installed via yum (I followed the install instruction of brew):
`gcc-4.8.3-9.el7.x86_64`

What could I do?

KR
Ruben

_Copied from original issue: Homebrew/homebrew#41449_

**Comment by bfontaine** [comment]
Are you using [Linuxbrew](https://github.com/Homebrew/linuxbrew)?

**Comment by bfontaine** [comment]
_From @rtuider on July 7, 2015 13:7_

Yes.
I followed this instructions: https://github.com/Homebrew/linuxbrew/blob/master/README.md

**Comment by sjackman** [comment]
Try the following:
```sh
ln -s $(which gcc) $(brew --prefix)/bin/gcc-$(gcc -dumpversion |cut -d. -f1,2)
ln -s $(which g++) $(brew --prefix)/bin/g++-$(g++ -dumpversion |cut -d. -f1,2)
```

**Comment by rtuider** [comment]
Awesome... thanks. This works.
