### ISSUE TITLE
python3 incorrect permissions on pip

### ISSUE THREAD

**Issue by andrewjpage** [Homebrew/linuxbrew#469]
When installing python3 it fails at the end. Setting chmodding pip with +w fixes the issue.

```
Copying pip.egg-info to /home/vagrant/.linuxbrew/lib/python3.4/site-packages/pip-7.1.0-py3.4.egg-info
running install_scripts
Installing pip script to /home/vagrant/.linuxbrew/Cellar/python3/3.4.3_1/bin
Installing pip3.4 script to /home/vagrant/.linuxbrew/Cellar/python3/3.4.3_1/bin
error: [Errno 13] Permission denied: '/home/vagrant/.linuxbrew/Cellar/python3/3.4.3_1/bin/pip3.4'
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall python3`
```

To replicate the issue on a clean CentOS7 VM with vagrant & virutalbox:
```
vagrant init chef/centos-7.0
vagrant up --provider virtualbox
vagrant ssh -c "sudo yum install -y epel-release gcc gcc-c++ automake"
vagrant ssh -c "sudo yum groupinstall -y 'Development Tools' && sudo yum install -y curl git m4 ruby texinfo bzip2-devel curl-devel expat-devel ncurses-devel zlib-devel"
vagrant ssh -c "git clone https://github.com/Homebrew/linuxbrew.git ~/.linuxbrew"
vagrant ssh -c "echo 'export PATH=\"\$HOME/.linuxbrew/bin:\$PATH\"' >> .bashrc"
vagrant ssh -c "ln -s \$(which gcc) ~/.linuxbrew/bin/gcc-4.8"
vagrant ssh -c "ln -s \$(which g++) ~/.linuxbrew/bin/g++-4.8"
vagrant ssh -c "ln -s \$(which gfortran) ~/.linuxbrew/bin/gfortran-4.8"
vagrant ssh -c "brew install python3"
```

**Comment by sjackman** [comment]
That's awfully strange. Any idea why `pip` isn't being set executable? I haven't run into this issue yet myself.

**Comment by andrewjpage** [comment]
It appears to have been introduced 2 days ago by this commit (I did a checkout and install on a clean VM)  https://github.com/Homebrew/linuxbrew/commit/b83eb23d7f177a965a92632da41d699c2371edc9

I'm new to this codebase so not sure about the cleanest way to fix it.

**Comment by sjackman** [comment]
I'm not sure what's gone wrong. I'll leave this issue open in the hopes that someone is able to help troubleshoot.

**Comment by xu-cheng** [comment]
May need to ping @tdsmith who is our Python expert.

**Comment by tdsmith** [comment]
> When installing python3 it fails at the end. Setting chmodding pip with +w fixes the issue.

Can you elaborate wrt which file you modified and how you demonstrated that it helped?

**Comment by andrewjpage** [comment]
I just set everything to be writable (so not a proper solution at all), then reran the end of the install (which then worked):

```
chmod +w /home/vagrant/.linuxbrew/Cellar/python3/3.4.3_1/bin/*
brew postinstall python3
```

It occurs on a fresh install of CentOS 6.6 & 7.0, and Ubuntu Trusty.

**Comment by tdsmith** [comment]
The python3 build runs ensurepip by default. For Framework builds, the pip script ends up getting written somewhere in the Framework tree, so it doesn't cause a conflict. Linuxbrew does a non-framework build, which exposes the conflict.

Homebrew/homebrew#41544 disables running ensurepip and will resolve this issue the next time Shaun merges from Homebrew/homebrew.

**Comment by tdsmith** [comment]
Thanks for reporting & the detailed reproduction instructions, btw!

**Comment by sjackman** [comment]
Thanks for the fix, Tim.

**Comment by andrewjpage** [comment]
Thanks for getting to the bottom of it so quickly. Andrew
