### ISSUE TITLE
linuxbrew won't query bottle server

### ISSUE THREAD

**Issue by schmurfy** [Homebrew/linuxbrew#472]
Hi,
I am trying to setup a private bottle server but I can't figure out how to make linuxbrew check it :(

What I have done is I set the environment variable HOMEBREW_BOTTLE_DOMAIN to the right url, I built a bottle and uploaded it on it then tried to install my recipe with:
```
$ brew install --force-bottle <recipe>
```

But my problem is that from there it starts immediately downloading the sources and builds it, I was watching the webserver logs and no request was ever made to it. I also tried to run a tcpdump to watch for any connection attempts but there were none either...

is there something special required to make brew use a custom bottle server ?

PS: If I run `brew config` it shows the correct url for the bottle server.

**Comment by xu-cheng** [comment]
What does your formula looks like?

**Comment by xu-cheng** [comment]
In fact, `HOMEBREW_BOTTLE_DOMAIN` is used to create mirror for bottle downloading. Since most of Linuxbrew's formulae don't have bottle yet. You should just create your bottle with `brew bottle <formula> --root-url=<your server>`.

**Comment by schmurfy** [comment]
thanks it worked, for some reason though if I don't use --force-bottle it builds directly from source, is that the intended behavior ?

**Comment by schmurfy** [comment]
it looks like the environment variables also works, I was doing my tests on two machines and the one I was trying to install on had a recipe without the `bottle` block, my bad :x

the default behavior of not checking for a bottle stills holds though, on mac os x the client seems to check for a bottle before doing anything else and this does not appear to be how linuxbrew works.
This is not a big issue but I am curious :p

**Comment by xu-cheng** [comment]
> thanks it worked, for some reason though if I don't use --force-bottle it builds directly from source, is that the intended behavior ?

That would relate to whether your bottles are relocatable. If not, you need to install Linuxbrew in the same prefix to use the bottle. 

I am not fully familiar to how Linuxbrew relocate the bottle. Ping @sjackman here, how should know about your problem.

**Comment by sjackman** [comment]
Yes, I haven't yet figured out how to resolve the relocatable bottle issue, other than recommending that Linuxbrew uses `/usr/local` like Homebrew does.

You also need to install `glibc` and `patchelf` before Linuxbrew will use bottles. See the [Standalone installation instructions](https://github.com/Homebrew/linuxbrew/wiki/Standalone-Installation). You'll want to start with a clean Linuxbrew installation.

**Comment by schmurfy** [comment]
ah ok, so the default in linuxbrew is indeed to go with compilation since binaries may not work on every linux installations, is that it ?
This is indeed an annoying problem, for my use I can go with always adding --force-bottle so i should be fine.

I love this project, I always hated most if not all package managers of linux distributions which make hard if not impossible to work with recent software versions (ubuntu/debian package manager is probably the worst in my opinion), and since the packages are overly complex to build doing yours is also a pain xD
We ended up compiling everything from sources and linuxbrew is a painless way to have a really nice package manager (we already use homebrew on our macs) which also allow us to easily create binary package of the software we use.

The reason for my initial question is that standard package won't fit the way we setup/install things so I chose to basically remove all the recipes and start for scratch, by extension we also need our own bottle server and it is currently working great.
(compiling from source is nice with a small number of servers, not so great when the number grows)

**Comment by sjackman** [comment]
> ah ok, so the default in linuxbrew is indeed to go with compilation since binaries may not work on every linux installations, is that it ?

More or less correct, yes. If `glibc` and `patchelf` installed, the default behaviour is to use bottles. But pretty much only relocatable bottles.

> I love this project

I'm glad to hear that!

> The reason for my initial question is that standard package won't fit the way we setup/install things

Care to elaborate?

**Comment by schmurfy** [comment]
I want to migrate a "home brewed" deployment system to linuxbrew at least for the package management parts, currently the way it works is by running bash commands on the remote host and essentially compiling and installing software the basic way (./configure && make && make install) with a test before that to see if it is already installed and the version is the one we want.
While it works this is not ideal and does not allow easily for binary package creation/install.

These are not big diffrences but since linuxbrew/homebrew makes it really easy to use our own recipes I will just selectively add more as we need them and customize them if need be (using the "official" recipe as a start).

Here are some specific needs that I plan to address in our recipes:
- patches: a few application we use are patched, some patches are being integrated upstream but others very specific will never be and we need to support that.
- daemons runner: we use daemontools and if I find a clean way the recipes will install the daemons as services which I can probably do via symlinking.
- version control: i want complete control on which version of what is installed, that's actually one of the grief I have against other package managers, in a perfect world changing a minor revision should be ok but in reality I would never do that in production without making sure it works as expected on a test server.

I am sure I will find more as I start implementing recipes, I really like the fact that the framework does not make many assumptions and for examples can be installed in any prefix, there are other advantages to the way linuxbrew works for me:
- no scattered files all around the file system, if I want to uninstall a version a simple rm -rf will get rid of everything
- no database, they can get corrupted and might be slow to deal with where a simple ls -l on the Cellar folder will tell me what is installed with linuxbrew :p 
- no forest of tools: apt is a great example of this (apt, dpkg, apt-cache, ...), brew has a lot of commands but at least there is only one entry point (and I don't think I ever used more then 3/4 anyway)

And last but not least: no hard dependency on a specific OS (even if it targets OS X and linux primarly), I plan to give it a try on Illumos and OpenBSD see if it can works, having one package manager for all the systems we use would be pretty awesome and greatly simplify things :)
pkgsrc was the only other package management system that was a candidates for our needs but it is nowhere near as easy to use as linuxbrew, ruby really helps there.

different Oses have their pros and cons and I don't see myself using Linux for everything, if you need complex routing for example OpenBSD with packet filter is really good.

**Comment by sjackman** [comment]
Sounds like a few good reasons to maintain a fork of Linuxbrew. Is your fork public on GitHub?

**Comment by schmurfy** [comment]
For now I am just playing with it see if it fits our needs, while I don't think it makes sense to have the whole repo here I will surely create pull requests for features that may be used by someone else if I have to modify the core files, a good example would be other OS support, is it an area where pull requests would be accepted ? (it is called linuxbrew after all ;) )

Also how homebrew/linuxbrew works together, are the two codebase sharing anything ? is there any plan to replace homebrew with linuxbrew since as far a I can tell linuxbrew supports both OS X and Linux ?

**Comment by sjackman** [comment]
> is it an area where pull requests would be accepted ? (it is called linuxbrew after all ;) )

Let's take it on a case-by-case basis. But in principle, yes, if it makes the formula more portable to other Posix systems and isn't a hack that is specific to BSD.

> Also how homebrew/linuxbrew works together, are the two codebase sharing anything ?

Yes, Homebrew is merged into the Linuxbrew fork once per week. See https://github.com/Homebrew/linuxbrew/blob/master/CONTRIBUTING.md

> is there any plan to replace homebrew with linuxbrew since as far a I can tell linuxbrew supports both OS X and Linux ?

@mikemcquaid Any plan to deprecate Homebrew in favour of Linuxbrew? :stuck_out_tongue_winking_eye:

**Comment by schmurfy** [comment]
if a deprecation happens at some point I feel like Homebrew would be the name to keep, Linuxbrew might convey the wrong assumption than it only works for Linux :)

**Comment by sjackman** [comment]
The above comment was tongue-in-cheek. Linuxbrew is a long-term fork of Homebrew. The two projects work closely together, and there are no current plans to merge the two projects.

**Comment by mikemcquaid** [comment]
> @mikemcquaid Any plan to deprecate Homebrew in favour of Linuxbrew?

:wink: :trollface:

**Comment by schmurfy** [comment]
That's what I thought before asking but is a there a specific reason for this ?

**Comment by sjackman** [comment]
The Homebrew maintainers are allergic to code speckled with `unless OS.mac?` in a project that's intended primarily for Mac OS.

**Comment by schmurfy** [comment]
ah ok xD
