### ISSUE TITLE
Boost Build Failure

### ISSUE THREAD

**Issue by LeeBergstrand** [Homebrew/linuxbrew#473]
```
==> Installing homebrew/science/blast dependency: boost
==> Downloading https://downloads.sourceforge.net/project/boost/boost/1.58.0/boost_1_58_0.tar.bz2
==> Downloading from http://iweb.dl.sourceforge.net/project/boost/boost/1.58.0/boost_1_58_0.tar.bz2
######################################################################## 100.0%
==> ./bootstrap.sh --prefix=/home/lee2/.linuxbrew/Cellar/boost/1.58.0 --libdir=/home/lee2/.linuxbrew/Cellar/boost/1.58.0/lib --without-i
==> ./b2 --prefix=/home/lee2/.linuxbrew/Cellar/boost/1.58.0 --libdir=/home/lee2/.linuxbrew/Cellar/boost/1.58.0/lib -d2 -j32 --layout=tag
cp "bin.v2/libs/log/build/gcc-4.8/release/link-static/log-api-unix/libboost_log_setup.a" "/home/lee2/.linuxbrew/Cellar/boost/1.58.0/lib/libboost_log_setup.a"

...failed updating 126 targets...
...skipped 18 targets...
...updated 13192 targets...
```

**Comment by LeeBergstrand** [comment]
Sever info:

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"

**Comment by tdsmith** [comment]
Please paste the output of `brew gist-logs boost`.

**Comment by LeeBergstrand** [comment]
Interestingly that command is running very slowing on my machine.

It was taking 30 min + and still kept going.

**Comment by LeeBergstrand** [comment]
I manage to make a manual log using `brew install -v boost 2>&1 > log.txt`

Link on my gist here --> https://gist.github.com/LeeBergstrand/038f806c46c7eae20cd3#file-boostfailurelog-txt

**Comment by tdsmith** [comment]
That looks like a successful build.

**Comment by tdsmith** [comment]
... albeit a suspiciously fast one

**Comment by LeeBergstrand** [comment]
Ya just checked the log. And it built? It says its built.

Weird... 

Ya so I ran `brew install -v boost 2>&1` and it failed.

Was getting something like this:

common.copy /home/lee2/.linuxbrew/Cellar/boost/1.58.0/lib/libboost_log_setup-mt.so.1.58.0

    cp "bin.v2/libs/log/build/gcc-4.8/release/log-api-unix/threading-multi/libboost_log_setup-mt.so.1.58.0"  "/home/lee2/.linuxbrew/Cellar/boost/1.58.0/lib/libboost_log_setup-mt.so.1.58.0"

ln-UNIX /home/lee2/.linuxbrew/Cellar/boost/1.58.0/lib/libboost_log_setup-mt.so

    ln -f -s 'libboost_log_setup-mt.so.1.58.0' '/home/lee2/.linuxbrew/Cellar/boost/1.58.0/lib/libboost_log_setup-mt.so'

...failed updating 16 targets...
...skipped 6 targets...
...updated 13314 targets...
==> Formula
Path: /home/lee2/.linuxbrew/Library/Formula/boost.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/linuxbrew
HEAD: 56ad5ad48fece63991e514aa4e8de37fdc0aaa44
Last commit: 20 hours ago
HOMEBREW_PREFIX: /home/lee2/.linuxbrew
HOMEBREW_CELLAR: /home/lee2/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: 32-core 64-bit 6
OS X: 0-x86_64
Xcode: N/A
CLT: N/A
Clang: N/A
X11: N/A
System Ruby: 1.9.3-p484 => /usr/bin/ruby1.9.1
Perl: /usr/bin/perl
Python: /usr/bin/python => /usr/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby1.9.1
Java: 1.7.0_79
==> ENV
CC: /usr/bin/gcc-4.8
CXX: /usr/bin/g++-4.8
OBJC: /usr/bin/gcc-4.8
OBJCXX: /usr/bin/g++-4.8
CFLAGS: -Os -w -pipe -march=core2
CXXFLAGS: -Os -w -pipe -march=core2
CPPFLAGS: -isystem/home/lee2/.linuxbrew/include
LDFLAGS: -L/home/lee2/.linuxbrew/lib -Wl,-rpath,/home/lee2/.linuxbrew/lib
MAKEFLAGS: -j32
CMAKE_PREFIX_PATH: /home/lee2/.linuxbrew
PKG_CONFIG_LIBDIR: /home/lee2/.linuxbrew/lib/pkgconfig:/usr/lib/pkgconfig
PATH: /home/lee2/.linuxbrew/bin:/home/lee2/.linuxbrew/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/lee2/.linuxbrew/Library/ENV/scm

Error: boost 1.58.0 did not build
Logs:
     /home/lee2/.cache/Homebrew/Logs/boost/01.bootstrap.sh
     /home/lee2/.cache/Homebrew/Logs/boost/02.b2

These open issues may also help:
`brew install boost --with-mpi --without-single` fails (https://github.com/Homebrew/homebrew/issues/40494)

**Comment by LeeBergstrand** [comment]
so I ran brew install -v boost 2>&1 > log.txt and then it worked?

**Comment by sjackman** [comment]
Hi, Lee. Please put quoted text inside backticks. Please see https://help.github.com/articles/markdown-basics/

**Comment by sjackman** [comment]
I'm glad that you got boost to install. If your subsequent testing shows that it works, please close this issue.

**Comment by LeeBergstrand** [comment]
Thanks. Fixed, forgot its was ``` for code block quotes.

Quick question how long should `brew gist-logs boost` normally take? It seems really slow for me? Like 10min+ and its would be still running.

**Comment by sjackman** [comment]
`brew gist-logs boost` runs `brew install boost`, so a long time.

@tdsmith Is there a command that gists the logs from the most recent install? I'd find that very helpful.

**Comment by tdsmith** [comment]
gist-logs never runs install.

**Comment by tdsmith** [comment]
It does run `brew doctor`, which can be slow.

**Comment by xu-cheng** [comment]
If `brew gist-logs` runs extreme slow, it usually means the log file is too large for gist to handle. I noticed this a while time ago. In this case, it would be better to manually uploading the log files.

**Comment by sjackman** [comment]
> gist-logs never runs install.

What do you know. Thanks for clarifying my misunderstanding. I guess I just assumed that's why it was slow. It must be `brew doctor` then that is slow.

**Comment by LeeBergstrand** [comment]
"If brew gist-logs runs extreme slow, it usually means the log file is too large for gist to handle. I noticed this a while time ago. In this case, it would be better to manually uploading the log files."

I actually think that it is the above. The log file is 4.2mb.

Brew Doctor runs fairly fast.

```Shell
time brew doctor

.....

real	0m1.150s
user	0m0.304s
sys	0m0.076s
```

1.2 seconds.
