### ISSUE TITLE
brew command not found AWS amazon linux

### ISSUE THREAD

**Issue by cojok** [Homebrew/linuxbrew#478]
Hi there,

I have installed homebrewlinux on my aws amazon linux instance, but I get this wired error:
"-bash: brew: command not found".

I have followed all the steps from the installation guid. I also tied to install it by cloning the repo and also via ruby. 

Any suggestions?

Thanks a lot

**Comment by sjackman** [comment]
Try
```sh
export PATH="$HOME/.linuxbrew/bin:$PATH"
```

**Comment by cojok** [comment]
Nope I have the path in ~/.bashrc exactly as it is on the home page as you sad, but nothing changed... do you have any other suggestion?

**Comment by cojok** [comment]
Just reinstalled the linuxbrew and now it works with this path yougave me thnx a lot :)

**Comment by sjackman** [comment]
Glad to hear that you got it working, Cojok.
