### ISSUE TITLE
curl: fails when built with libressl

### ISSUE THREAD

**Issue by paulhybryant** [Homebrew/linuxbrew#481]
`brew install curl --with-libressl`

Error is the following

```
curl --version
curl: error while loading shared libraries: libssl.so.32: cannot open shared object file: No such file or directory
```

And the reason is libressl is keg_only.

According to the comments in libressl.rb, `LibreSSL is not linked to prevent conflict with the system OpenSSL.`

If system openssl is not available and libressl is not linked, curl would fail.

**Comment by sjackman** [comment]
Try `brew link --force libressl`

**Comment by sjackman** [comment]
An alternative solution would be to add `:provided_by_osx`:
```ruby
keg_only :provided_by_osx, "LibreSSL is not linked to prevent conflict with the system OpenSSL."
```
