### ISSUE TITLE
Unable to brew gwenhywfar

### ISSUE THREAD

**Issue by DomT4** [Homebrew/linuxbrew#488]
_From @amenk on July 18, 2015 18:34_

I can not brew gwenhywfar.

The troubleshooting page did not help me.

Can somebody fix this or help to pinpoint the problem?

Debug info:

https://gist.github.com/amenk/5734853a482c88bff792

_Copied from original issue: Homebrew/homebrew#41866_

**Comment by dunn** [comment]
Try `brew install gwenhywfar --without-cocoa`.

**Comment by amenk** [comment]
Thanks. I just found that myself :) And it worked.
What is the issue exactly?

Another one: --HEAD is not working. It can not find the SVN URL. Looks like the project switched to git:

http://www2.aquamaniac.de/sites/download/index.php

**Comment by dunn** [comment]
> What is the issue exactly?
The cocoa GUI is only for OS X, so it needs to be turned off when Linuxbrew users install gwenhywfar.

> Looks like the project switched to git
Feel like [opening a PR](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md) to update the `head` URL? 😃 We'd be very grateful!

**Comment by amenk** [comment]
Should I remove the cocoa from the linux brew formular as well?

**Comment by amenk** [comment]
It seems to have a problem with the git url:

$ brew install --HEAD gwenhywfar
==> Downloading http://git.aqbanking.de/git/gwenhywfar

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "gwenhywfar"
Download failed: http://git.aqbanking.de/git/gwenhywfar

**Comment by dunn** [comment]
That's up to @sjackman—I know he doesn't like too many differences between Linuxbrew and Homebrew, because it makes merges changes more difficult.

**Comment by amenk** [comment]
Okay, I used a conditional. I made a PR.
