### ISSUE TITLE
--force-bottle not propagated to dependencies

### ISSUE THREAD

**Issue by schmurfy** [Homebrew/linuxbrew#489]
When you force bottle usage the depencies will be installed from sources even if the package is available, it looks like the flag is now passed to "brew install" for such dependencies.
I am not familiar enough (yet) to fix that myself but maybe soon :)

**Comment by schmurfy** [comment]
is there a way to inverse the behavior so that by default it uses bottles if available and a flag would force to build from sources ?

**Comment by sjackman** [comment]
Reassigning to Homebrew/homebrew.

**Comment by sjackman** [comment]
This issue was moved to Homebrew/homebrew#41938

**Comment by schmurfy** [comment]
shall we reopen this one ?^^

**Comment by schmurfy** [comment]
what was changed in linuxbrew to make "build from source" as the default ?
Knowing that I might be able to reverse it.

**Comment by sjackman** [comment]
Linuxbrew has the additional requirement that `glibc` and `patchelf` be installed. See [Standalone Installation of Linuxbrew](https://github.com/Homebrew/linuxbrew/wiki/Standalone-Installation)

**Comment by schmurfy** [comment]
ok I found my issue, I was impressed that the path where homebrew is installed was not hardcoded which is really helpful in non standard case except that there is still at least one place where it is hardcoded: the default cellar for bottles.
My Homebrew is not using /usr/local (I wanted to keep what I install separated from the Ubuntu stuff) and when doing a `brew install xxx` homebrew checked if the cellar was the default one and stopped there triggering a build from source.

If I am the only who ever asked for --force-bottle to be passed to dependencies installs I think this issue can be closed as I no longer need it.

**Comment by sjackman** [comment]
Ah, yes. Some bottles don't care where they are installed (are relocatable). They are marked `cellar :any`. Other's that are not relocatable specify a particular cellar. If so, the `HOMEBREW_PREFIX` of the Homebrew installation and the `cellar` of the bottle must agree.
