### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by elgs** [Homebrew/linuxbrew#49]
I accidentally installed linuxbrew using root, now I want to uninstall it from root and install it from my regular user again.

Thanks,
Elgs

**Comment by andradei** [comment]
When running the uninstall script I get the following:

```
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
-e:89:in ``': No such file or directory - command (Errno::ENOENT)
	from -e:89:in `<main>'
```

**Comment by sjackman** [comment]
Try
```sh
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/uninstall)"
```
(note: untested)

**Comment by xu-cheng** [comment]
@andradei This should be fixed by https://github.com/Homebrew/install/commit/9d15de4353512bf80f720b034e73b2c6669c3542

**Comment by andradei** [comment]
worked for me, thank you.

**Comment by sjackman** [comment]
Thanks, Xu.

**Comment by guidstah** [comment]
Doesn't really work for me!

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/uninstall)"
-e:89:in ``': No such file or directory - command -v brew (Errno::ENOENT)
	from -e:89:in `<main>'

How do I run the uninstall script without any errors??

**Comment by pallawik** [comment]
hii there, how can i remove linuxbrew, i want to install cufflinks but somehow it return error like given below. so i'll first remove linuxbrew and reinstall it, i tried all possibilities wt i can do..... please help me

Last 15 lines from /home/mkumar/.cache/Homebrew/Logs/cufflinks/02.make:
libcufflinks.a(abundances.o): In function `void boost::archive::save_access::save_primitive<boost::archive::binary_oarchive, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(boost::archive::binary_oarchive&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/mkumar/.linuxbrew/include/boost/archive/detail/oserializer.hpp:90: undefined reference to `boost::archive::basic_binary_oprimitive<boost::archive::binary_oarchive, char, std::char_traits<char> >::save(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/mkumar/.linuxbrew/include/boost/archive/detail/oserializer.hpp:90: undefined reference to `boost::archive::basic_binary_oprimitive<boost::archive::binary_oarchive, char, std::char_traits<char> >::save(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libcufflinks.a(abundances.o): In function `void boost::archive::load_access::load_primitive<boost::archive::binary_iarchive, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(boost::archive::binary_iarchive&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
/home/mkumar/.linuxbrew/include/boost/archive/detail/iserializer.hpp:107: undefined reference to `boost::archive::basic_binary_iprimitive<boost::archive::binary_iarchive, char, std::char_traits<char> >::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
libcufflinks.a(abundances.o): In function `void boost::archive::save_access::save_primitive<boost::archive::binary_oarchive, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(boost::archive::binary_oarchive&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/mkumar/.linuxbrew/include/boost/archive/detail/oserializer.hpp:90: undefined reference to `boost::archive::basic_binary_oprimitive<boost::archive::binary_oarchive, char, std::char_traits<char> >::save(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libcufflinks.a(abundances.o): In function `void boost::archive::load_access::load_primitive<boost::archive::binary_iarchive, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(boost::archive::binary_iarchive&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
/home/mkumar/.linuxbrew/include/boost/archive/detail/iserializer.hpp:107: undefined reference to `boost::archive::basic_binary_iprimitive<boost::archive::binary_iarchive, char, std::char_traits<char> >::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
collect2: error: ld returned 1 exit status
make[2]: *** [cufflinks] Error 1
make[2]: Leaving directory `/tmp/cufflinks-20170517-29733-q22k12/cufflinks-2.2.1/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/cufflinks-20170517-29733-q22k12/cufflinks-2.2.1'
make: *** [all] Error 2

READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting

These open issues may also help:
Symbol not found while using Cufflinks https://github.com/Homebrew/homebrew-science/issues/5466

**Comment by sjackman** [comment]
To uninstall Linuxbrew, run…
```sh
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/uninstall)"
rm -rf ~/.linuxbrew
```
