### ISSUE TITLE
please remove unsafe symbol links

### ISSUE THREAD

**Issue by CDLuminate** [Homebrew/linuxbrew#495]
linuxbrew/Library/ENV/pkgconfig/fuse/
fuse.pc:    broken symbolic link to /usr/local/lib/pkgconfig/fuse.pc
osxfuse.pc: broken symbolic link to /usr/local/lib/pkgconfig/osxfuse.pc

**Comment by sjackman** [comment]
Why?

**Comment by CDLuminate** [comment]
I'm trying to make the linuxbrew Debian package.
lintian, the Debian package checker found this problem according to Debian policy:
```
E: linuxbrew source: source-contains-unsafe-symlink Library/ENV/pkgconfig/fuse/osxfuse.pc
N: 
N:    The source contains an unsafe symlink. If followed, the link will escape
N:    the source root. Note that all absolute symlinks are unconditionally
N:    considered "unsafe" in this case (unlike in binary packages).
N:    
N:    If it is a part of the package's testsuite, Lintian may have failed to
N:    recognise it as a test. In that case, please override the tag.
N:    
N:    Severity: serious, Certainty: possible
N:    
N:    Check: cruft, Type: source
```
and https://lists.debian.org/debian-mentors/2015/07/msg00335.html

**Comment by sjackman** [comment]
Whoah. A Linuxbrew package for Debian. I had considered the possibility. How do you plan to handle updating the formulas? Simply `sudo brew update` ? What `HOMEBREW_PREFIX` do you plan to use? `/usr/lib/linuxbrew`?

Linuxbrew intends to be compatible with Mac Homebrew (you can run Linuxbrew on a Linux or Mac box), so I don't plan to delete these symlinks. Although I also don't know why they exist. You could ask upstream at `Homebrew/homebrew` if you like. You could delete these files before packaging the source tarball for Debian.

**Comment by CDLuminate** [comment]
well, the current packaging work is available here
```
http://anonscm.debian.org/cgit/users/cdluminate-guest/linuxbrew.git
```

### The HOMEBREW_PREFIX planed to use  
No, not the `/usr/lib/linuxbrew`.  Without any change it's still `${HOME}/.linuxbrew`
Being able to Install softwares without root premission is an outstanding feature of linuxbrew and I'm not about to break it via changing `HOMEBREW_PREFIX` to `/usr/lib/linuxbrew`. Additinally, linuxbrew should
be set up for per user, rather than the system wide and common `/usr/lib/linuxbrew`.  

### Updating formulas  
Debian's update period is too long compared with linuxbrew/homebrew update period.  
And I found it uncomfortable to manage a linuxbrew.git subrepo in the Debian packaging repo,
especially when need to patch linuxbrew with quilt.  Maybe shipping a whole repo is bad idea.  
  
Since I found that `brew update` will setup a new git repo under `HOMEBREW_PREFIX` when there is no .git, I'm thinking, can I just scrach all the core components of linuxbrew into the Debian package, without formula.  I made another wrapper script of linuxbrew [1]  
  
The current wrapper does so:
* If `HOMEBREW_PREFIX/bin/brew`exists, simply invoke it
* if !exists:  
  - init a linuxbrew without git repo under `HOMEBREW_PREFIX`, with a tarball.  This provides only a basic set of, no-updated formulas. But it will be tricky if BUG emerges from formulas.  
  - init a linuxbrew under `HOMEBREW_PREFIX`, with linuxbrew's install script  
  
So the convention of linuxbrew won't be changed.
  
[1] http://anonscm.debian.org/cgit/users/cdluminate-guest/linuxbrew.git/tree/debian/bin/linuxbrew

**Comment by CDLuminate** [comment]
Anyway users can just setup a linuxbrew at home without apt/dpkg by themselves,
but it could be better if a wrapper is provided by debain, for better integration of
linuxbrew into distribution.  
This is my main idea.

**Comment by sjackman** [comment]
Interesting. So your `/usr/bin/brew` script will be a script that installs Linuxbrew in `~/.linxuxbrew` if it doesn't already exist, and after that initial installation, runs `~/.linxuxbrew/bin/brew`. Yes? Seems simple enough to me.

**Comment by CDLuminate** [comment]
Yes, so it is.  
Another reason not restoring many files at  /usr/lib/linuxbrew  is, they'll become useless once the
user invoked `brew update`, afterall a whole new copy of linuxbrew would be cloned into `.linuxbrew/` int that way.  
My current concern is, what component should I ship in the debian package? there are some ideas:  
* [most simple] only wrapper and the `install` script would be shipped.  
  This will not break any function of linuxbrew, the only problem is user need to wait for some time of git repo to be cloned.
* [not for sure] wrapper + install + ( linuxbrew - formulas).
* [issue] wrapper + install + ( linuxbrew (has formulas) - .git repo )
* [bad] wrapper + install + whole linuxbrew git repo, (so users can init a .linuxbrew directory with .git immediately)
  
---
Since I have trouble cloning the whole linuxbrew git repo ( costs so loooong time ),
may I suggest that add `--depth` option to install script [1] ?
  
Adding `--depth 1` to `git clone xxx` would significantly decrease the time cost when installing.
I don't know if other users need the whole git repo including 50K+ commits, but at least I don't need
the 50K+ commits, and just squashing 50K+ commits into 1 via `--depth 1` is fine to me.  

[1] https://raw.githubusercontent.com/Homebrew/linuxbrew/go/install

**Comment by sjackman** [comment]
> [most simple] only wrapper and the install script would be shipped.
This will not break any function of linuxbrew, the only problem is user need to wait for some time of git repo to be cloned.

:+1:

> Since I have trouble cloning the whole linuxbrew git repo ( costs so loooong time ),
may I suggest that add --depth option to install script [1] ?

Please ask upstream at `Homebrew/homebrew`.

**Comment by CDLuminate** [comment]
@sjackman 
Could you please add copyright declaration in the head of the installscript?  
https://github.com/Homebrew/linuxbrew/blob/go/install
  
Since the designed debian package ships only that install script from upstream,
it is better for it to have a integrated copyright declaration.  
See http://www.gnu.org/licenses/gpl-faq.html#NoticeInSourceFile  
  
I'm not the author hence I won't add that by myself even if you confirmed it is bsd-2-clause.  
:-)

**Comment by sjackman** [comment]
The entire Homebrew project is BSD 2 Clause (NetBSD) license. See https://github.com/Homebrew/linuxbrew#license
