### ISSUE TITLE
texlive broken (versions of the local installation and the repository being accessed are not compatible: 2014 vs 2015)

### ISSUE THREAD

**Issue by amenk** [Homebrew/linuxbrew#498]
I can't install texlive. Seems to me that the package has to be updated to a 2015 version, where can I get a new `texlive-XXXX.tar.gz` ?

	==> Downloading https://downloads.sourceforge.net/project/linuxbrew/mirror/texlive-20141204.tar.gz
	Already downloaded: /home/example/.cache/Homebrew/texlive-20141204.tar.gz
	==> Verifying texlive-20141204.tar.gz checksum
	tar xf /home/example/.cache/Homebrew/texlive-20141204.tar.gz
	==> Downloading and installing TeX Live. This will take a few minutes.
	==> ./install-tl -scheme medium -portable -profile /dev/null
	Automated TeX Live installation using profile: /dev/null
	Loading http://ctan.math.utah.edu/ctan/tex-archive/systems/texlive/tlnet/tlpkg/texlive.tlpdb
	=============================================================================
	./install-tl: The TeX Live versions of the local installation
	and the repository being accessed are not compatible:
	      local: 2014
	 repository: 2015
	Perhaps you need to use a different CTAN mirror?
	(For more, see the output of install-tl --help, especially the
	 -repository option.  Online via http://tug.org/texlive/doc.)

**Comment by sjackman** [comment]
Thanks for the bug report, Alexander.
