### ISSUE TITLE
suite-sparse: fails on ubuntu 14.04

### ISSUE THREAD

**Issue by ahundt** [Homebrew/linuxbrew#510]
I'm not sure if this is the right place to put this issue due to the particulars of linuxbrew since this is a `homebrew-science` package, but `brew install suite-sparse` failed on ubuntu 14.04 as follows:

https://gist.github.com/50ee22b1ca6d754caed9

**Comment by sjackman** [comment]
https://gist.github.com/anonymous/50ee22b1ca6d754caed9#file-01-make-L3820-L3823
```
/home/peter/.linuxbrew/bin/g++-5 -fPIC -O3 -fno-common -fexceptions -DNTIMER -fopenmp -DHAVE_TBB -DNPARTITION -I../../CHOLMOD/Include -I../../SuiteSparse_config -I../Include -c ../Source/spqr_parallel.cpp
../Source/spqr_parallel.cpp:10:37: fatal error: tbb/task_scheduler_init.h: No such file or directory
compilation terminated.
make[2]: *** [spqr_parallel.o] Error 1
```

**Comment by sjackman** [comment]
My guess is that it will fail on any system including Mac where `HOMEBREW_PREFIX` is not `/usr/local`. The formula does not add the TBB include directory to `CPPFLAGS`. See https://github.com/Homebrew/homebrew-science/blob/master/suite-sparse.rb#L49-L50

**Comment by sjackman** [comment]
This issue was moved to Homebrew/homebrew-science#2648
