### ISSUE TITLE
openssl install on lubuntu 14.04 LTC failed

### ISSUE THREAD

**Issue by stepun** [Homebrew/linuxbrew#514]
Linux ubuntu 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:31:42 UTC 2014 i686 i686 i686 GNU/Linux
brew -v:
Homebrew 0.9.5
openssl version:
OpenSSL 1.0.2d 9 Jul 2015

I had tried brew installation and source installation, all are failed.
brew installation:
```
user@ubuntu:~$ brew install openssl
==> Downloading https://www.openssl.org/source/openssl-1.0.2d.tar.gz
Already downloaded: /home/user/.cache/Homebrew/openssl-1.0.2d.tar.gz
tar: Нулевой блок в 52140
==> perl ./Configure --prefix=/home/user/.linuxbrew/Cellar/openssl/1.0.2d_1 --openssldir=/home/user/.linuxbrew/etc/op
==> make depend
==> make
                         ^
compilation terminated.
make[1]: *** [cryptlib.o] Error 1
make[1]: Выход из каталога `/tmp/openssl20150820-6329-1g0oaeg/openssl-1.0.2d/crypto'
make: *** [build_crypto] Error 1

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

user@ubuntu:~$ brew doctor
Your system is ready to brew.
```
brew gist-logs openssl
https://gist.github.com/anonymous/a99bcc7621d06ccc36bd

**Comment by sjackman** [comment]
Please report `brew gist-logs openssl`. I'm heading on vacation for two weeks, so I'm afraid I won't be able to look at the result until I return.

**Comment by iggyvolz** [comment]
Is there a reason the logs are in Russian?  If there's any way you could build it in English that would be much more helpful.

**Comment by stepun** [comment]
brew gist-logs openssl 
link: https://gist.github.com/anonymous/a99bcc7621d06ccc36bd

**Comment by stepun** [comment]
System Eanglish reinstall
```
user@ubuntu:~$ brew install openssl
==> Downloading https://www.openssl.org/source/openssl-1.0.2d.tar.gz
Already downloaded: /home/user/.cache/Homebrew/openssl-1.0.2d.tar.gz
tar: A lone zero block at 52140
==> perl ./Configure --prefix=/home/user/.linuxbrew/Cellar/openssl/1.0.2d_1 --op
==> make depend
==> make
                         ^
compilation terminated.
make[1]: *** [cryptlib.o] Error 1
make[1]: Leaving directory `/tmp/openssl20150820-12611-1akk4p0/openssl-1.0.2d/crypto'
make: *** [build_crypto] Error 1

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
```
```
user@ubuntu:~$ brew gist-logs openssl
https://gist.github.com/8a1260d0bcd11d9ae5ff
```

**Comment by iggyvolz** [comment]
Looks like the problem is related to the install not finding system libraries - which means they're either not installed or Linuxbrew isn't pointing to the proper place.

Make sure you have build libraries installed, specifically build-essential (run `sudo apt-get update && sudo apt-get install build-essential`).  It looks like it's not finding those and just failing all over the place.

**Comment by stepun** [comment]
I made a symlink (/usr/include/sys) necessary libraries. Everything is working

**Comment by tdsmith** [comment]
Great; let us know if we can help with anything else.
