### ISSUE TITLE
open-ssl post-install does not complete successfully on CentOS v6.4

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/linuxbrew#531]
_From @marcora on September 2, 2015 14:54_

https://gist.github.com/de244f3f2dda6e72afce

==> Downloading http://curl.haxx.se/ca/cacert.pem
Already downloaded: /hpc/users/marcoe02/.cache/Homebrew/openssl--cacert-1.0.2d.pem
Error: SHA256 mismatch
Expected: ccde89388cac12c5d3c8e68b9458add7e22b849371818dfdd240c994d6193641
Actual: ca4ebe0c2dc6f61faa037d4e71ae3ac0f9bde5b1da4fa2e4a6e50592a620bcd5
Archive: /hpc/users/marcoe02/.cache/Homebrew/openssl--cacert-1.0.2d.pem
To retry an incomplete download, remove the file above.

Removing the file as indicated does not solve the issue.

_Copied from original issue: Homebrew/homebrew#43511_

**Comment by tdsmith** [comment]
_From @tzudot on September 2, 2015 15:17_

Better report this issue at [Homebrew/linuxbrew](https://github.com/Homebrew/linuxbrew/issues).

**Comment by JorisM** [comment]
same here, fedora 22

**Comment by JorisM** [comment]
thanks!
