### ISSUE TITLE
Does  linuxbrew have other download methods such as wget

### ISSUE THREAD

**Issue by fanghuan** [Homebrew/linuxbrew#546]
I'm new to linuxbrew.  when useing linuxbrew to install tmux, I got this error

`/usr/local/bin/curl: error while loading shared libraries: libimf.so: cannot open shared object file: No such file or directory`

I knew the curl had some problem but wget was installed correctly. I'm not root user,so I was wondering whether linuxbrew has other download methods such as **wget**.

**Comment by dunn** [comment]
Not currently; allowing that to be configured increases the likelihood of user configuration errors.  Does curl work for you in other contexts?  If you reinstall it, does it work?

**Comment by iggyvolz** [comment]
If you need to, you can download files directly to <user's home dir>/.cache/Homebrew and they will be picked up as a cached download.  If you want, you could just brew install curl after using wget to download curl's binary to the cache directory, and after that you can just use homebrew's curl (which should work unless your system is really screwed up)

**Comment by fanghuan** [comment]
After checking the curl command,I found curl had some problems that were not related with linuxbrew. 
Here are my solution:
First, loate the **`bash libimf.so`**,I got this
***`/opt/intel/composer_xe_2011_sp1.9.293/compiler/lib/intel64/libimf.so`***
Second, Add the command below  to  your **`~/.bashrc`**
***``export LD_LIBRARY_PATH="/opt/intel/composer_xe_2011_sp1.9.293/compiler/lib/intel64:$LD_LIBRARY_PATH"``***
Third, source your **`.bashrc`**
it sloved my problem in curl.
Thaks for your advice @dunn  @iggyvolz ,it helped me rebuild my curl.
