### ISSUE TITLE
Invalid HOMEBREW_CC

### ISSUE THREAD

**Issue by Rombur** [Homebrew/linuxbrew#548]
I am trying to use linuxbrew on a cluster but it picks up the wrong compiler. Linuxbrew picks the compiler in /usr/bin even if I have another compiler in my path. I tried to set HOMEBREW_CC to the desired compiler but I get the following error:
```Error: Invalid value for HOMEBREW_CC: /apps/gcc/4.8.2/bin/gcc```
I think the error is thrown from Library/Homebrew/extend/ENV/shared.rb and I found a file Library/Homebrew/compilers.rb which is supposed to determine the compiler. I am new to linuxbrew and ruby, any indication what I need to change in compilers.rb so it recognizes my compiler?

**Comment by Mikaela** [comment]
I think you are supposed to just set `HOMEBREW_CC=gcc` and ensure that `/apps/gcc/4.8.2/bin/` is the first directory in your `PATH`.

**Comment by Rombur** [comment]
Thanks, I have tried that but if I set ```HOMEBREW_CC=gcc```, linuxbrew will always pick the compiler in ```/usr/bin``` which is strange because ```which gcc``` returns the right compiler.

**Comment by davydden** [comment]
just for ease of reference: 
that's where (it seems) `HOMEBREW_CC` is used https://github.com/Homebrew/linuxbrew/blob/master/Library/Homebrew/extend/ENV/shared.rb#L139 .
and then it goes to some checks of REGEX here https://github.com/Homebrew/linuxbrew/blob/master/Library/Homebrew/extend/ENV/shared.rb#L285

i don't know `ruby` and thus I don't see how actually `source` variable (`HOMEBREW_CC`) got passed anywhere, but i think one can make things work by modifying https://github.com/Homebrew/linuxbrew/blob/master/Library/Homebrew/compilers.rb#L3

to something like `GNU_GCC_REGEXP = ([^/]*)gcc-(4\.[3-9]|5)$`

**Comment by davydden** [comment]
see http://stackoverflow.com/questions/6494915/regex-pattern-to-match-the-end-of-a-string

**Comment by davydden** [comment]
p.s. you can check `/([^/]*)gcc-(4\.[3-9]|5)$/` here http://www.regexr.com

**Comment by davydden** [comment]
i think the correct regex is `/(?:[^/]*\/g|^g)cc-(4\.[3-9]|5)$/`

**Comment by Rombur** [comment]
This regex works ```/([^\/]*)gcc($|(-(4\.[3-9]|5)$))/``` but it only moves the problem because now when I try to install a package, I get ```cannot be built with any available compilers.```

**Comment by davydden** [comment]
Bruno, pls try the latest regex i posted which has the same number of groups (1) with the same value (version) as the original regex. This might be important in other places where the regex is used.

**Comment by davydden** [comment]
Ps. That's assuming u have '/path/to/gcc-4.x' that u can use.

To my understanding in other places the regex could be used to pickup the version and be able to process something like 'fails_with :gcc49' (and alike).

In the original regex the version us in the first and only group.

**Comment by davydden** [comment]
i tried this one `/(?:[^\/]*)gcc-(4\.[3-9]|5)$/` with `export HOMEBREW_CC=/usr/bin/gcc-4.8` (my locations are usual), but hit `Homebrew GCC requested, but formula gcc48 not found!`. 
Will see if there is a way to make it work with full paths...

**Comment by davydden** [comment]
i commented line 141 in shared.rb : `warn_about_non_apple_gcc($&) if cc =~ GNU_GCC_REGEXP` and and seems to be running with `/(?:[^\/]*)gcc-(4\.[3-9]|5)$/` and `brew tap homebrew/versions`. No GCC is installed from the tap.

Another possible workaround (adopted from https://github.com/Homebrew/linuxbrew/issues/137#issuecomment-56759177)  :
```
prefix=~/.linuxbrew
ln -s /apps/gcc/4.8.2/bin/gcc $prefix/bin/gcc-4.8
ln -s /apps/gcc/4.8.2/bin/g++ $prefix/bin/g++-4.8
ln -s /apps/gcc/4.8.2/bin/gfortran $prefix/bin/gfortran-4.8
export HOMEBREW_CC=gcc-4.8
brew tap homebrew/versions
brew install hello && brew test -v hello; brew remove hello
```

You can also automate this nicely (if it works) https://github.com/Homebrew/linuxbrew/issues/137#issuecomment-57353932

In general, i think `HOMEBREW_CC` needs some documentation w.r.t how is it used inside and what are the workarounds. Where could this be added @sjackman ?

**Comment by Rombur** [comment]
#137 worked. Thanks @davydden

**Comment by sjackman** [comment]
Thanks for your help troubleshooting, Denis. If the symlink for `gcc-4.x` or `gcc-5` exists in `$HOMEBREW_PREFIX/bin`, then you shouldn't need to set `HOMEBREW_CC`. It should find your compiler on its own.
