### ISSUE TITLE
Error when running 'brew install node' on Redhat 

### ISSUE THREAD

**Issue by xinmiao** [Homebrew/linuxbrew#561]
I ran into the following error while installing node with 'brew'. Brew is up-to-date on this Redhat server and 'brew doctor' reports no error.

Here are the logs from the terminal:

[mxin@androids1 ~]$ brew install node
Error: no such file to load -- irb
Please report this bug:
    https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/home/mxin/.linuxbrew/Library/Homebrew/debrew/irb.rb:1:in `require'
/home/mxin/.linuxbrew/Library/Homebrew/debrew/irb.rb:1
/home/mxin/.linuxbrew/Library/Homebrew/debrew.rb:2:in `require'
/home/mxin/.linuxbrew/Library/Homebrew/debrew.rb:2
/home/mxin/.linuxbrew/Library/Homebrew/formula_installer.rb:14:in `require'
/home/mxin/.linuxbrew/Library/Homebrew/formula_installer.rb:14
/home/mxin/.linuxbrew/Library/Homebrew/cmd/install.rb:5:in `require'
/home/mxin/.linuxbrew/Library/Homebrew/cmd/install.rb:5
/home/mxin/.linuxbrew/Library/brew.rb:60:in `require'
/home/mxin/.linuxbrew/Library/brew.rb:60:in `require?'
/home/mxin/.linuxbrew/Library/brew.rb:109
[mxin@androids1 ~]$ brew doctor
Your system is ready to brew.
[mxin@androids1 ~]$ which -a irb
/usr/bin/which: no irb in (/home/mxin/.linuxbrew/bin:/root/anaconda/bin:/home/mxin/aosp/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8/bin:/usr/local/bin:/home/mxin/bin:/root/anaconda/bin:/home/mxin/aosp/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8/bin:/usr/local/bin:/home/mxin/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/jdk1.7.0_79/bin:/opt/jdk1.7.0_79/jre/bin:/home/mxin/bin:/opt/jdk1.7.0_79/bin:/opt/jdk1.7.0_79/jre/bin)
[mxin@androids1 ~]$ brew install ruby
Error: no such file to load -- irb
Please report this bug:
    https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/home/mxin/.linuxbrew/Library/Homebrew/debrew/irb.rb:1:in `require'
/home/mxin/.linuxbrew/Library/Homebrew/debrew/irb.rb:1
/home/mxin/.linuxbrew/Library/Homebrew/debrew.rb:2:in `require'
/home/mxin/.linuxbrew/Library/Homebrew/debrew.rb:2
/home/mxin/.linuxbrew/Library/Homebrew/formula_installer.rb:14:in `require'
/home/mxin/.linuxbrew/Library/Homebrew/formula_installer.rb:14
/home/mxin/.linuxbrew/Library/Homebrew/cmd/install.rb:5:in `require'
/home/mxin/.linuxbrew/Library/Homebrew/cmd/install.rb:5
/home/mxin/.linuxbrew/Library/brew.rb:60:in `require'
/home/mxin/.linuxbrew/Library/brew.rb:60:in `require?'
/home/mxin/.linuxbrew/Library/brew.rb:109
[mxin@androids1 ~]$ brew install rubygem
Error: no such file to load -- irb
Please report this bug:
    https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/home/mxin/.linuxbrew/Library/Homebrew/debrew/irb.rb:1:in `require'
/home/mxin/.linuxbrew/Library/Homebrew/debrew/irb.rb:1
/home/mxin/.linuxbrew/Library/Homebrew/debrew.rb:2:in `require'
/home/mxin/.linuxbrew/Library/Homebrew/debrew.rb:2
/home/mxin/.linuxbrew/Library/Homebrew/formula_installer.rb:14:in `require'
/home/mxin/.linuxbrew/Library/Homebrew/formula_installer.rb:14
/home/mxin/.linuxbrew/Library/Homebrew/cmd/install.rb:5:in `require'
/home/mxin/.linuxbrew/Library/Homebrew/cmd/install.rb:5
/home/mxin/.linuxbrew/Library/brew.rb:60:in `require'
/home/mxin/.linuxbrew/Library/brew.rb:60:in `require?'
/home/mxin/.linuxbrew/Library/brew.rb:109

**Comment by danabrand** [comment]
Try `gem install irb` and report back.

**Comment by DomT4** [comment]
Let us know if you need further help here, thanks!
