### ISSUE TITLE
Brew dependency on git version not specified

### ISSUE THREAD

**Issue by brevilo** [Homebrew/linuxbrew#568]
`brew update` does require a certain git version as it at least fails with git 1.7.1:

```
% brew update                                                                                                                                                               
error: unknown option `short'
usage: git symbolic-ref [options] name [ref]
```

Obviously brew expects a certain git CLI which isn't yet available in 1.7.1. Please specify the minimum git version required in the README's list of dependencies.

Thanks

**Comment by Mikaela** [comment]
I think this is possibly upstream issue, https://github.com/Homebrew/homebrew/

**Comment by brevilo** [comment]
You're right: https://github.com/Homebrew/homebrew/issues/44350

**Comment by tdsmith** [comment]
This is a Linuxbrew documentation issue.

**Comment by sjackman** [comment]
Update the docs.
* **Git** 1.7.12.4 or newer
