### ISSUE TITLE
brew install ffmpeg, on raspberry pi 2    "Error: undefined method 'split' for nil:NilClass"

### ISSUE THREAD

**Issue by ronanc-raspberrypi** [Homebrew/linuxbrew#581]
brew install ffmpeg
seemed to run fine until
Error: undefined method 'split' for nil:NilClass

==> Downloading https://ffmpeg.org/releases/ffmpeg-2.8.tar.bz2
Already downloaded: /home/pi/.cache/Homebrew/ffmpeg-2.8.tar.bz2
Please report this bug:

(Ok i had to run brew install ffmpeg > bug.txt to capture the error, hence above message of Already downloaded)
    https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/home/pi/.linuxbrew/Library/Homebrew/os/linux/hardware.rb:53:in `flags'
/home/pi/.linuxbrew/Library/Homebrew/os/linux/hardware.rb:63:in `block (2 levels) in <module:LinuxCPUs>'
/home/pi/.linuxbrew/Library/Homebrew/compat/hardware.rb:6:in `is_32_bit?'
/home/pi/.linuxbrew/Library/Formula/ffmpeg.rb:147:in `install'
/home/pi/.linuxbrew/Library/Homebrew/build.rb:129:in `block in install'
/home/pi/.linuxbrew/Library/Homebrew/formula.rb:848:in `block in brew'
/home/pi/.linuxbrew/Library/Homebrew/formula.rb:1389:in `block in stage'
/home/pi/.linuxbrew/Library/Homebrew/resource.rb:91:in `block in unpack'
/home/pi/.linuxbrew/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/home/pi/.linuxbrew/Library/Homebrew/resource.rb:88:in `unpack'
/home/pi/.linuxbrew/Library/Homebrew/resource.rb:81:in `stage'
/home/pi/.linuxbrew/Library/Homebrew/formula.rb:1381:in `stage'
/home/pi/.linuxbrew/Library/Homebrew/formula.rb:844:in `brew'
/home/pi/.linuxbrew/Library/Homebrew/build.rb:107:in `install'
/home/pi/.linuxbrew/Library/Homebrew/build.rb:176:in `<main>'

Version of raspbian....from /proc/version
Linux version 4.1.7-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.8.3 20140303 (prerelease) (crosstool-NG linaro-1.13.1+bzr2650 - Linaro GCC 2014.03) ) #817 SMP PREEMPT Sat Sep 19 15:32:00 BST 2015

brand new install of os and linuxbrew
yes i did a brew update, doctor etc

**Comment by ronanc-raspberrypi** [comment]
ps here is the brew config from the above report

HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/linuxbrew
HEAD: 844ddc06f2b966d0a202f1f0ec7db35f9bc391e2
Last commit: 19 hours ago
HOMEBREW_PREFIX: /home/pi/.linuxbrew
HOMEBREW_REPOSITORY: /home/pi/.linuxbrew
HOMEBREW_CELLAR: /home/pi/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
Please report this bug:
    https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/home/pi/.linuxbrew/Library/Homebrew/os/linux/hardware.rb:53:in `flags'
/home/pi/.linuxbrew/Library/Homebrew/os/linux/hardware.rb:63:in `block (2 levels) in <module:LinuxCPUs>'
/home/pi/.linuxbrew/Library/Homebrew/os/linux/hardware.rb:68:in `bits'
/home/pi/.linuxbrew/Library/Homebrew/cmd/config.rb:101:in `hardware'
/home/pi/.linuxbrew/Library/Homebrew/cmd/config.rb:152:in `dump_verbose_config'
/home/pi/.linuxbrew/Library/Homebrew/cmd/config.rb:7:in `config'
/home/pi/.linuxbrew/Library/brew.rb:133:in `<main>'

**Comment by ronanc-raspberrypi** [comment]
I think i found the problem

https://github.com/Homebrew/linuxbrew#dependencies
clearly says 
Ruby 1.8.6 or newer
GCC 4.2 or newer
64-bit x86 platform

and the raspberry pi is arm 32 bit
hope there is a 32 bit version of linuxbrew, will looks around

**Comment by ronanc-raspberrypi** [comment]
this issue seems to be related to #563

**Comment by ronanc-raspberrypi** [comment]
I sorted this one out as follows:
modify the hardware.rb file as indicated on https://github

**Comment by ronanc-raspberrypi** [comment]
Sorted this one out as follows:
uninstall linuxbrew

then 
git clone https://github.com/Homebrew/linuxbrew.git ~/.linuxbrew
cd ~/.linuxbrew/Library/Homebrew/os/linux
edit the hardware.rb file at line 53 as follows 
 def flags
    #@flags ||= cpuinfo[/^flags.*/, 0].split
    @flags ||= cpuinfo[/^(flags|Features).*/, 0].split
  end
see https://github.com/Homebrew/linuxbrew/issues/563

the brew install ffmpeg
... and it works
    ... not bad for a newbie noob

**Comment by sjackman** [comment]
Duplicate of #518

**Comment by sjackman** [comment]
I'm glad to hear that you got it working!

**Comment by ronanc-raspberrypi** [comment]
re patch for ARM7 (sjackman patch to hardware.rb file)
i installed linuxbrew using the git clone https://github.com/Homebrew/linuxbrew.git ~/.linuxbrew
as opposed to the
ruby-e "$(curl -fsSL.........

just for divilment, i'll uninstall linuxbrew and then re-install with ruby, modify the hardware.rb and then see if i can brew doctor, brew update etc


i edited the hardware.rb file and halleuja it does build sucessfully,.... except i can no longer brew update.
I think this may be a git issue, because i cloned, modified (hardware.rb) and now it wants to upload my modifications

not sure, 'cos i don't know the ins and outs of GIT, but i know if i stash, save and clean it seems to revert my hardware.rb to the unmodified version
Below are the details

pi@novisad ~ $ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have uncommitted modifications to Homebrew
If this a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
    cd /home/pi/.linuxbrew/Library && git stash && git clean -d -f

Warning: Your Homebrew is outdated.
You haven't updated for at least 24 hours. This is a long time in brewland!
To update Homebrew, run `brew update`.

pi@novisad ~ $ brew update
Stashing your changes:
 M Library/Homebrew/os/linux/hardware.rb

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <pi@novisad.(none)>) not allowed
Cannot save the current index state
Error: Failure while executing: git stash save --include-untracked --quiet
pi@novisad ~ $
