### ISSUE TITLE
Can't install node, relating to ./configure

### ISSUE THREAD

**Issue by sato-sh** [Homebrew/linuxbrew#590]
Hi, 

I'm getting an error when attempting to install nodejs. From the build process node downloads fine but then throws an error when it gets to the ./configure stage.

 brew install node
==> Downloading https://nodejs.org/dist/v4.1.1/node-v4.1.1.tar.gz
Already downloaded: /home/wdev/.cache/Homebrew/node-4.1.1.tar.gz
==> Downloading https://ssl.icu-project.org/files/icu4c/55.1/icu4c-55_1-src.tgz
Already downloaded: /home/wdev/.cache/Homebrew/node--icu4c-55.1.tgz
==> ./configure --prefix=/home/wdev/.linuxbrew/Cellar/node/4.1.1 --without-npm --with-intl=small-icu
Last 15 lines from /home/wdev/.cache/Homebrew/Logs/node/01.configure:
Tue Oct 06 19:53:41 +0000 2015

./configure
--prefix=/home/wdev/.linuxbrew/Cellar/node/4.1.1
--without-npm
--with-intl=small-icu

Any help would be great, thanks

**Comment by sato-sh** [comment]
Any ideas why this might be happening?

**Comment by ahundt** [comment]
Can you post the full `brew gist-logs node`, please? Thanks!

**Comment by DomT4** [comment]
The formula should now complain if you try to build with an incompatible compiler, which was very likely the problem here.
