### ISSUE TITLE
Is there a dependency on bash in Linuxbrew?

### ISSUE THREAD

**Issue by DoomHammer** [Homebrew/linuxbrew#594]
The installer script runs `/bin/bash` in install script. Do we need any explicit bashism or will plain `/bin/sh` do?

**Comment by DoomHammer** [comment]
OK. Rereading the source I see that pipefail is used which is a bashism. But is it necessary?

**Comment by sjackman** [comment]
It could be rewritten not to use `pipefail`, but it does need to fail if `curl` fails.
```ruby
system "/bin/bash -o pipefail -c '/usr/bin/curl -#{curl_flags} #{HOMEBREW_REPO}/tarball/master | /usr/bin/tar xz -m --strip 1'"
```
https://github.com/Homebrew/install/blob/master/install#L227

**Comment by sjackman** [comment]
How is checking for a failed pipeline handled in standard `sh`? If you rewrite it portably, perhaps upstream Homebrew will accept it, if the rewrite is not too much uglier than the bashism.

**Comment by sjackman** [comment]
What system do you have that does not have `bash` installed?

**Comment by DoomHammer** [comment]
Testing it on Alpine to provide a more compact container.

**Comment by sjackman** [comment]
I'm going to close this issue.
Yes, there's a dependency on `bash`.
