### ISSUE TITLE
'brew install jdk' fails

### ISSUE THREAD

**Issue by prohde** [Homebrew/linuxbrew#595]
I want to use linuxbrew for building my project on Travis CI because they still run an old version of Java 8 and I need at least 8u40. But using:

>rm -rf ~/.linuxbrew
>yes | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/linuxbrew/go/install)"
>export PATH="$HOME/.linuxbrew/bin:$PATH"
>export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
>export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
>brew install jdk
>export JAVA_HOME=/home/travis/.linuxbrew/Cellar/jdk/1.8.0-60

in my .travis.yml fails. The important part of the log is:
>$ rm -rf ~/.linuxbrew
>$ yes | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/linuxbrew/go/install)"
>$ export PATH="$HOME/.linuxbrew/bin:$PATH"
>$ export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
>$ export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
>$ brew install jdk
>==> Downloading http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jdk-8u60-li
>==> Downloading from http://download.oracle.com/errors/download-fail-1505220.htm
>######################################################################## 100.0%
>Error: SHA256 mismatch
>Expected: ebe51554d2f6c617a4ae8fc9a8742276e65af01bd273e96848b262b3c05424e5
>Actual: 80212f7748c2671b89b6085000717c747851db004409dce3bb97f3a2aeb91cdd
>Archive: /home/travis/.cache/Homebrew/jdk-1.8.0-60.tar.gz
> 
>To retry an incomplete download, remove the file above.
> 
>The command "brew install jdk" failed and exited with 1 during .

**Comment by sjackman** [comment]
I can confirm that I see this build failure as well. A work around is to download the file `jdk-8u60-linux-x64.tar.gz` from http://www.oracle.com/technetwork/java/javase/downloads/index.html and move it to `~/.cache/Homebrew/jdk-1.8.0-60.tar.gz`.

The cookie accepting code is written by @jbaum98. Jake, can you fix it for us?
https://github.com/Homebrew/linuxbrew/blob/master/Library/Formula/jdk.rb#L5

**Comment by jbaum98** [comment]
It's not a problem with the cookies, I think it's the SHA hash. I'll double check that. I don't have `linuxbrew` available right now so I can't check it works myself.

**Comment by jbaum98** [comment]
Okay I think this fixes it, but I don't have `linuxbrew` on hand right now. Can someone else test this? @prohde

**Comment by prohde** [comment]
I'm sorry I can't test this at the moment. I would be happy if someone else could do.

**Comment by sjackman** [comment]
I tested it. It works. I've merged #596
