### ISSUE TITLE
Linuxbrew team

### ISSUE THREAD

**Issue by sjackman** [Homebrew/linuxbrew#600]
My new son, Jake, is two months old, and I'm on parental leave from work. I will be traveling with my family until Christmas. I'd love for some help with maintaining Linuxbrew in my absence.

Dana @danabrand, a system administrator at UBC, has kindly completed the last two merges of Homebrew into Linuxbrew. She's newish to Linuxbrew and doesn't have commit rights  to Homebrew/linuxbrew. When she's prepared a merge commit, I'd appreciate someone's help to take a look at it and push `danabrand/master` to `linuxbrew/master`. Less pressing, but it would be great to have a couple volunteers to review pull requests and comment on issues.

Xu @xu-cheng, Dominyk @DomT4, Tim @tdsmith, Homebrew-science friends @Homebrew/science, would you be interested in joining the Linuxbrew team? Please cc anyone that I've missed.

**Comment by dpo** [comment]
I'll gladly help as time allows.

**Comment by tseemann** [comment]
Happy to help where I can.  We look forward to your return in 21 years time ;-)

**Comment by DomT4** [comment]
Homebrew already chews up a more than reasonable amount of time that I have left after various chunks of life heh, but I might be able to stick my head in Linuxbrew and help with various simple issues. Dana is also welcome to ping my @ if there's something that needs merging quickly. Enjoy the time away Shaun :)

**Comment by xu-cheng** [comment]
I will help now and then whenever I'm available. But I cannot keep too many promise as Homebrew has already occupied most of my spare time, similar as DomT4.

BTW, congratulations.

**Comment by sjackman** [comment]
@DomT4 @xu-cheng Any effort that you can pitch in is appreciated.
Would you please add @dpo and @tseemann to the Homebrew/linux team?

**Comment by xu-cheng** [comment]
> Would you please add @dpo and @tseemann to the Homebrew/linux team?

Done. Also I think you have the access to change Linux team whatever you want.

**Comment by sjackman** [comment]
I tried, but I don't believe I do have the rights to change the `linux` team.

**Comment by sjackman** [comment]
@danabrand Would you be able to merge Homebrew into Linuxbrew again this week?
@dpo @tseemann @DomT4 @xu-cheng Could one of you take a look at Dana's merge and push the branch `danabrand/master` to `linuxbrew/master` and `danabrand/homebrew` to `linuxbrew/homebrew`?
After a few weeks of that arrangement, could you please add @danabrand to the Homebrew/linux team so that she can push herself?

**Comment by sjackman** [comment]
@xu-cheng Can you make the Homebrew/linux team public, and if you think it's a good idea, make all the Homebrew/* teams public?

**Comment by mikemcquaid** [comment]
@sjackman You now have rights to add/remove people from the @Homebrew/linux team.

**Comment by iml** [comment]
I should have some more free time starting next month, would be glad to help out then.

**Comment by sjackman** [comment]
Thanks, Mike.

**Comment by sjackman** [comment]
Great. I've added you to the team, Ian.

**Comment by danabrand** [comment]
Hi all, great to e-meet. And Shaun, yes, I can merge again into Linuxbrew this week.

**Comment by sjackman** [comment]
Dana has merged homebrew/master into linuxbrew/master. That commit is at danabrand/master. Could someone in the @homebrew/linux team please take a look at that commit and push it to linuxbrew/master? I've tested it, and it looks good, but I won't be doing any testing while I'm in Thailand. =)

**Comment by DomT4** [comment]
Nobody else has responded here so I took the nervous plunge and merged Dana's master branch into Linuxbrew/master, which brings Linuxbrew up to ~8 days ago in up-to-date-ness.

> Please also push the branch danabrand/homebrew to linuxbrew/homebrew. It's a branch at the point that homebrew/master was merged.

This does not want to work for me locally, but at least the master is done.

**Comment by danabrand** [comment]
Thank you! I was just wondering what's happening with that. Ok, I will get onto merging the latest and let you know when it's ready to be pushed again.

**Comment by DomT4** [comment]
Thanks Dana. Feel free to ping if you want to. I was trying to give it a bit to see if anyone who uses Linux on a more frequent basis wanted to handle this, but `¯\_(ツ)_/¯`.

I don't really have time to keep on top of Linuxbrew and I don't want to routinely become the person who gets pinged when something breaks, because most of the time my reaction is going to be a slightly confused look when it comes to Linux specific changes :smile:.

I can handle occasional merges of branches here though, so if things are ready and tested and such let me know and I'll bite the bullet. Thank you again for the willingness to help out with this sort of thing.

**Comment by DomT4** [comment]
How are things going @danabrand? No pressure intended - Know life gets busy and it's apparently just me and you doing Linuxbrew for a while.

**Comment by sjackman** [comment]
Shaun here checking in from Thailand. Thanks so much for feeding and watering Linuxbrew in my absence, Dana and Dominyk. I appreciate your help!

**Comment by danabrand** [comment]
Hi Dom, this has been on my mind for the last weeks, but the UBC job was indeed very busy. I want to do a commit this weekend, I will let you know as soon as I have it done, I suspect there are a bunch of conflicts to deal with.

**Comment by DomT4** [comment]
@sjackman Hope the time away so far has been pleasant! :smiley:. Know getting away from FOSS for a bit can be a weight off one's shoulders.

@danabrand No worries Dana. Whenever you have time. Things that pay the bills trump things which very much don't.

**Comment by danabrand** [comment]
Looks like I broke it – see issue 648. I am in transit right now, will get to this only in a few hrs, if anyone can fix it, please go ahead. Thank you!

**Comment by danabrand** [comment]
Hello, can someone either apply fix suggested in issue 648 or possibly repush my branch, whatever you think it's better. i don't have access to the main repo. thanks!

**Comment by DomT4** [comment]
Will merge your fork in again now. Apologies for the few hours delay.

**Comment by danabrand** [comment]
Hello all, worked on a massive merge today. I did what I could, but I need your help.

I went through all conflicts (100+) reported by the merge and for better or worse, resolved them. I pushed all these in my branch.

However, when testing, I noticed that all formulas using "unneeded" for a bottle, failed. At a closer look, the auto-merged formula.rb doesn't contain a   "def bottle_unneeded?" line. 

When merging, these were reported auto-merged by git:
Auto-merging Library/Homebrew/keg.rb
Auto-merging Library/Homebrew/formula_installer.rb
Auto-merging Library/Homebrew/formula.rb
Auto-merging Library/Homebrew/extend/pathname.rb
Auto-merging Library/Homebrew/extend/ENV/std.rb
Auto-merging Library/Homebrew/exceptions.rb
Auto-merging Library/Homebrew/dependency_collector.rb
Auto-merging Library/Homebrew/cmd/test-bot.rb
Auto-merging Library/Homebrew/cmd/pull.rb
Auto-merging Library/Homebrew/cmd/bottle.rb
Auto-merging Library/Homebrew/cmd/audit.rb

But whatever the auto-merging did, brew fails when trying to make sense of an unneeded bottle. This is the error reported when testing on zzz, tomcat, jenkins (all in that boat):
Error: block not supplied

Testing at random on other modified formulas worked fine. 

Any ideas appreciated. thank you.

**Comment by danabrand** [comment]
Hmm, just noticed issue 660 reports this as well, so the error is not necessarily related to this merge.

**Comment by DomT4** [comment]
> However, when testing, I noticed that all formulas using "unneeded" for a bottle, failed. At a closer look, the auto-merged formula.rb doesn't contain a "def bottle_unneeded?" line.

It sounds like the auto-merge dropped that line for some reason, maybe there's a conflict there or something. Can you `diff` between the merged `formula.rb` and the homebrew/homebrew `formula.rb` from the merge point?

**Comment by danabrand** [comment]
@DomT4 It's a bit more complex than that, the unneeded reference appears in a few more files in Homebrew, while not present in Linuxbrew. 
Alternatively, we could push all new formulas other than the few involving unneeded. It at least brings a bunch of them up to date, while we figure out (or Shaun does when he's back) the underlining mechanism that breaks. What do you guys think?

**Comment by DomT4** [comment]
@danabrand Depending how comfortable you are with it another potential rough hack is to use something like `awk` or `sed` to run through the formulae directory and remove any `bottle :unneeded` or `bottle :disable` lines temporarily.

**Comment by danabrand** [comment]
@DomT4 hmm, that's not a bad idea. I see 21 formulas using that, not that many. let me try a few. of course it's a hack and not pretty, but it does the job done for the moment.

**Comment by DomT4** [comment]
@danabrand What's the breakage process out of curiosity? Does the entirety of Linuxbrew break if there are `bottle :xyz` lines detected or only when those specific formulae are invoked in some manner?

**Comment by danabrand** [comment]
@DomT4 It seems that only brew installing/updating or otherwise parsing those formulas is affected.  I discovered the behavior in my testing when testing at random brew install on some of the modified formulas in this latest merge. But then I noticed report from issue 660 as well, so I believe this happened a few merges ago. When did you guys introduced `bottle unneeded/disable`?

**Comment by DomT4** [comment]
@danabrand Alright, that's manageable at least - I had in mind that `homebrew/versions` can be tapped by Linuxbrew users and there's a bunch of `bottle :xyz` in there these days, but as long as it's only going to die on certain formulae it's not too horrible a UX.

The new `bottle :xyz` DSL was added on October 19th in https://github.com/Homebrew/homebrew/pull/43935.

**Comment by DomT4** [comment]
CC @xu-cheng in case he has ideas on why it wouldn't function for Linuxbrew specifically.

**Comment by sjackman** [comment]
Thank you very much for tackling this merge even though you're busy, Dana, and thanks Dominyk for supporting her. If bottle :unneeded was broken before this merge, I suggest leaving it broken in this merge and fixing it with a separate commit after the merge. If this merge otherwise works, push! Thank you everyone.

**Comment by danabrand** [comment]
@DomT4 Ok. good news. Worked on an older branch of Linuxbrew pre Oct 19 and merged with Homebrew just to test the formula.rb and related formulae merging; this time the automerging worked just fine and voila, we have good Homebrew formulae. Tested installs for reported formula in issue 660, as well as a few other that have the `bottle:unneeded line`, they worked fine. Checked in these formulae into my latest danabrand repo. 

So theoretically this last commit in danabrand solves the `bottle:unneeded` line issue, as well as it has the 100+ updated formulae in Library/Formula. I did not test them all, I tested some at random and they worked for me. I really can't test that many, you guys did a lot of upgrades and I haven't kept up, so this is some all-in-one commit and I am sure I slipped somewhere.

Do you think you have time to test a bit this last commit? Last experience traumatized me:-) and I would want to be more cautious this time, especially with such a large merge.

**Comment by DomT4** [comment]
Yeah, I'll merge you into my VM later today and play with it a bit. May not be till mid-afternoon as have quite a busy day but will get around to it by the evening. Thank you Dana.

Don't worry about not testing everything; It isn't humanly possible to test everything Homebrew tweaks on a weekly basis, let alone longer, without mainlining caffeine and not moving from your computer for a few days :smile:.

**Comment by DomT4** [comment]
Seems to be okay. Merges cleanly, can run a `brew update` and `brew upgrade` on an outdated formula. Can run `brew cleanup` and `brew prune` to remove old versions without issue. Can execute commands on `bottle :unneeded` formulae. Can run `brew audit` and `brew audit --strict --online` fine. Can execute the `brew` command itself with no arguments with no errors. `brew doctor` runs without error. Same with `brew config`. `brew tap` works fine.

There's a slight merge conflict in `test-bot` on line 628 of your most recent commit, but I could fix that on pull.

Looks pretty good to me Dana :).

**Comment by danabrand** [comment]
@DomT4 Thank you Dominic. Please go ahead with the conflict resolve and if you feel we can bite the bullet, push the new commit. Fingers crossed.

**Comment by DomT4** [comment]
Merged. Did a bit more testing locally, everything seems to work as expected, which probably means there's some edge case breakage we'll suddenly get flooded with :smile_cat:, but fingers crossed all is alright. Thanks again Dana. We owe you a :beer: some day for all the help here.

**Comment by danabrand** [comment]
@DomT4  BTW, managed to injure myself this weekend on a first ski trip this winter, so one hand typing now and less computer glued, but will try to watch the issues.  @sjackman  Shaun, come back!!!!!!! :)

**Comment by DomT4** [comment]
@danabrand We just get pouring rain in the UK :wink:. Hope the injury isn't too painful and you recover soon!

**Comment by sjackman** [comment]
I hope that your ski injury has recovered, Dana. Thanks again both of you for your efforts! Liz and I have left Thailand and are now in Bali, Indonesia.

**Comment by danabrand** [comment]
Hi guys, apologies for dropping off the grid. Still recovering, boy I forget my age... I will try to poke at an up-to-date all-in-one merge this coming week, but most likely I will truly get onto it only on the 22nd. Hope to have it ready for all as Xmas present;)

**Comment by sjackman** [comment]
Hi, friends. I'm back from vacation and sleeping in my own bed again after three months away. Thanks for all your help in my absence. As much as you have time available, I encourage you all to continue contributing to Linuxbrew! I really need the help.

**Comment by sjackman** [comment]
Now on to some trickier technical stuff. I started a `git merge homebrew/master` today and got 200 merge conflicts! Whew! I believe that these merge conflicts are a results of the merges on 2015-11-10 and 2015-11-16 and the subsequent reverts on 2015-11-17. git now thinks that a bunch of files are modified on the linuxbrew branch, and these files create merge conflicts. Here's a good blog post on the issue: [Git: merging after a revert](https://metlos.wordpress.com/2012/01/13/git-merging-after-a-revert/). His suggestion is to revert the revert commits. In our case however there are three revert commits and there have been 8 commits since the revert commits, so I don't think that strategy is straight forward.

My plan is to checkout the merge of 2015-10-15 602d9b461deec71f1886ddfc2d8df932e702fc37 and merge homebrew/master into that commit. With that merge done, I'll then merge that commit into the current linuxbrew/master bb453ad33892df0d5560a177890a94810ecc71af, taking the tree exactly as it is from the previous merge commit. i.e. `git merge --strategy=ours`. This should, if it works as intended, produce a nice clean tree that reverts the most recent 14 commits:

```
bb453ad  2015-12-10  dunn.alex@gmail.com  travis: remove conflict marker
b82c4cf  2015-11-30  dominyktiller@gmail.com  mysql: de-dupe dependency block
0d0823e  2015-11-30  dominyktiller@gmail.com  profanity: needs libcurl on linux
bdcfe9b  2015-11-30  dominyktiller@gmail.com  test-bot: resolve merge conflict
c5ead6b  2015-11-26  dana.brand@ubc.ca  Update formula to use unneeded
d88a3b3  2015-11-25  dana.brand@ubc.ca  Fixed merge error
e2b369e  2015-11-25  dana.brand@ubc.ca  Merge branch homebrew/master into linuxbrew/master
da44282  2015-11-24  inferno1392@mail.ru  Update libpng.rb
092bbb6  2015-11-17  dominyktiller@gmail.com  Revert "Merge branch homebrew/master into linuxbrew/master"
787d7f9  2015-11-17  dominyktiller@gmail.com  Revert "Merge branch homebrew/master into linuxbrew/master"
c257139  2015-11-17  dominyktiller@gmail.com  Revert "OS_VERSION fixed"
3bd7bda  2015-11-16  dana.brand@ubc.ca  OS_VERSION fixed
85d75ac  2015-11-16  dana.brand@ubc.ca  Merge branch homebrew/master into linuxbrew/master
e9b2f2b  2015-11-10  dana.brand@ubc.ca  Merge branch homebrew/master into linuxbrew/master
```

I'll cherry-pick the following commit

```
0d0823e  2015-11-30  dominyktiller@gmail.com  profanity: needs libcurl on linux
```

I want to emphasize that I do really appreciate all the work that was done by everyone between 2015-11-10 and 2015-12-10, and I apologize for my plan to wipe these commits away. My git-fu is just not strong enough to continue with the repo in its current state, and the most efficient and likely-to-succeed strategy for me is to backtrack to the last known-good state. Thanks again for all your help!

**Comment by sjackman** [comment]
Here's what I plan to do:

```sh
git checkout master
git branch linuxbrew-old
git checkout 602d9b4
git branch --force master
git merge homebrew/master
git merge --strategy=mine linuxbrew-old
git push
```

**Comment by sjackman** [comment]
This strategy reduces the number of merge conflicts from 200 to 42, so I think that I'm on the right track. The real test will be in future merges.

**Comment by sjackman** [comment]
The merge is going well. I'm testing it now at https://github.com/sjackman/linuxbrew/
If all goes well, I'll push it to linuxbrew/master

**Comment by sjackman** [comment]
The merge went well and is now pushed to linuxbrew/master!

**Comment by sjackman** [comment]
I'm going to close this issue now. If anyone would like to contribute more work to Linuxbrew, I would very much appreciate your help.

**Comment by DomT4** [comment]
Welcome back @sjackman. No offence taken to doing it your way. Things got kind of complicated with merging and then having to revert the merge commits to avoid manually reverting 200+ commits. Linuxbrew has been a bit of a handful. I'm not really sure how you manage to keep on top of it to be honest, given you also contribute to at least the Science tap.

Dana was a complete godsend. Very little would have happened here without her doing the vast majority of the heavy lifting and I'm extraordinarily grateful to her for all the help. Dana, if you ever run into me somewhere, feel free to request a large drink of some description, I more than owe you one.
