### ISSUE TITLE
CMake failing to install with standalone linuxbrew on Ubuntu 14.04

### ISSUE THREAD

**Issue by arunnair411** [Homebrew/linuxbrew#616]
I'm trying to install CMake through linuxbrew for a project. I've set up standalone linuxbrew using [this setup script] (https://raw.githubusercontent.com/ahundt/homebrew-robotics/master/linuxbrew-standalone.sh), after which everything seems fine, until I ran:

```
brew install cmake-basis --devel -v
```

which fails, displaying:

```
Error when bootstrapping CMake:
Cannot find appropriate C++ compiler on this system.
Please specify one using environment variable CXX.
See cmake_bootstrap.log for compilers attempted.
---------------------------------------------
Log of errors: /tmp/cmake20151023-8618-1hx0h2u/cmake-3.3.2/Bootstrap.cmk/cmake_bootstrap.log
```

The created cmake_bootstrap.log file is empty. But g++ is installed fine, as when I ```run g++ --version```, I get

```
g++ (Homebrew gcc 5.2.0 --with-glibc) 5.2.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I tried setting CXX environment variable manually to the g++ path, exporting and then running it, but the error persists.

I've posted the gist logs [here] (https://gist.github.com/anonymous/316e4cfeef25f7242f50).

**Comment by saketkc** [comment]
You might want to symlink  `/home/arun/.linuxbrew/bin/g++-5` to `/home/arun/.linuxbrew/bin/g++` and see if `CMake` then picks it up.

**Comment by arunnair411** [comment]
I just tried doing that, but I received the message below saying that it already exists.

```
ln: failed to create symbolic link ‘/home/arun/.linuxbrew/bin/g++’: File exists

arun@arun-Lenovo-Y50-70:~/Desktop$ ls -alh /home/arun/.linuxbrew/bin/g++
lrwxrwxrwx 1 arun arun 27 Oct 23 09:42 /home/arun/.linuxbrew/bin/g++ -> ../Cellar/gcc/5.2.0/bin/g++
```

**Comment by arunnair411** [comment]
So I got what was wrong. A shared C++ library wasn't being linked correctly, so I ran:

```
brew unlink gcc && brew link gcc
```

and voila! CMake installed fine.

**Comment by sjackman** [comment]
Odd. Do you know which library wasn't linked correctly?
