### ISSUE TITLE
parent directory is world writable but not sticky

### ISSUE THREAD

**Issue by Wumingla** [Homebrew/linuxbrew#624]
Error: parent directory is world writable but not sticky
Please report this bug:
    https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tmpdir.rb:92:in `mktmpdir'
/home/ubuntu/.linuxbrew/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/home/ubuntu/.linuxbrew/Library/Homebrew/formula_installer.rb:553:in `build'
/home/ubuntu/.linuxbrew/Library/Homebrew/formula_installer.rb:219:in `install'
/home/ubuntu/.linuxbrew/Library/Homebrew/cmd/install.rb:189:in `install_formula'
/home/ubuntu/.linuxbrew/Library/Homebrew/cmd/install.rb:94:in `block in install'
/home/ubuntu/.linuxbrew/Library/Homebrew/cmd/install.rb:94:in `each'
/home/ubuntu/.linuxbrew/Library/Homebrew/cmd/install.rb:94:in `install'
/home/ubuntu/.linuxbrew/Library/brew.rb:145:in `<main>'

**Comment by DomT4** [comment]
`brew doctor` tells you how to fix this.

**Comment by ealgase** [comment]
I the same issue.  How do you run disk utility?

**Comment by dunn** [comment]
That `doctor` message might need to be updated for Linuxbrew.

**Comment by sjackman** [comment]
I've fixed the `doctor` message for Linuxbrew. It should now display
```
Please execute `sudo chmod +t /tmp` in your Terminal
```
