### ISSUE TITLE
Change "Mac"s from terminal output to either "Machine" or "PC" or whatever

### ISSUE THREAD

**Issue by jamesfjx** [Homebrew/linuxbrew#630]
if I type 
$brew install pip

the terminal will say
Error: No available formula for pip
Homebrew provides pip via: `brew install python`. However you will then
have two Pythons installed on your Mac, so alternatively you can:
    sudo easy_install pip

Since it's not homebrew anymore, we can safely switch the "Mac" with proper words. And I believe there should be tons of them hiding here and there inside linuxbrew.

**Comment by DoomHammer** [comment]
The idea is that Linuxbrew should be as close as possible to Homebrew and only add OS-specific things when needed and not alter the ones that do no harm.

It is true that such messages may exist, but simply replacing them is not a good option.
