### ISSUE TITLE
[ARCH] To install this formula you need to :

### ISSUE THREAD

**Issue by moh117** [Homebrew/linuxbrew#631]
Im trying to install rbenv on arch linux i have linuxbrew installed , but when i do:
 
       brew install rbenv

i get : 
      
      Error: xz cannot be built with any available compilers.
      To install this formula, you may need to:
       brew install gcc

and when i do

      brew install gcc

i get this :

     Error: zlib cannot be built with any available compilers.
     To install this formula, you may need to:
      brew install gcc

my local gcc version is (5.2.0)
 help me please !!

**Comment by moh117** [comment]
No response for two days , AUR is the solution :) !

**Comment by sjackman** [comment]
I'm on vacation in Thailand until the new year. Sorry that I wasn't able to help. This bug is on my radar.

**Comment by moh117** [comment]
NP Bro , it's not that urgent take your time .
But i find out that AUR is always updated so i think there is no need for me to use LinuxBrew.

**Comment by sjackman** [comment]
Apparently a workaround for your issue is `brew install --cc=gcc rbenv`
