### ISSUE TITLE
install git failed

### ISSUE THREAD

**Issue by JokerHYC** [Homebrew/linuxbrew#637]
==> Installing dependencies for git: homebrew/dupes/tcl-tk
==> Installing git dependency: homebrew/dupes/tcl-tk
==> Downloading https://downloads.sourceforge.net/project/tcl/Tcl/8.6.4/tcl8.6.4
Already downloaded: /home/joker/.cache/Homebrew/tcl-tk-8.6.4.tar.gz
==> Patching
patching file pkgs/sqlite3.8.8.3/generic/sqlite3.c
==> ./configure --prefix=/home/joker/.linuxbrew/Cellar/tcl-tk/8.6.4 --mandir=/ho
==> make
==> make install
==> make install-private-headers
==> Downloading https://downloads.sourceforge.net/project/tcl/Tcl/8.6.4/tk8.6.4-
Already downloaded: /home/joker/.cache/Homebrew/tcl-tk--tk-8.6.4.tar.gz
==> ./configure --prefix=/home/joker/.linuxbrew/Cellar/tcl-tk/8.6.4 --mandir=/ho
==> make TK_LIBRARY=/home/joker/.linuxbrew/Cellar/tcl-tk/8.6.4/lib
Last 15 lines from /home/joker/.cache/Homebrew/Logs/tcl-tk/06.make:
make: *** [tk3d.o] Error 1
In file included from /tmp/tcl-tk--tk20151111-22913-rp92s9/tk8.6.4/unix/../generic/tkPort.h:21:0,
                 from /tmp/tcl-tk--tk20151111-22913-rp92s9/tk8.6.4/unix/../generic/tkInt.h:19,
                 from /tmp/tcl-tk--tk20151111-22913-rp92s9/tk8.6.4/unix/../generic/tkBind.c:15:
/tmp/tcl-tk--tk20151111-22913-rp92s9/tk8.6.4/unix/../generic/tk.h:96:25: fatal error: X11/Xlib.h: 没有那个文件或目录
compilation terminated.
Makefile:948: recipe for target 'tkBind.o' failed
make: *** [tkBind.o] Error 1
In file included from /tmp/tcl-tk--tk20151111-22913-rp92s9/tk8.6.4/unix/../generic/tkPort.h:21:0,
                 from /tmp/tcl-tk--tk20151111-22913-rp92s9/tk8.6.4/unix/../generic/tkInt.h:19,
                 from /tmp/tcl-tk--tk20151111-22913-rp92s9/tk8.6.4/unix/../generic/tkBusy.c:15:
/tmp/tcl-tk--tk20151111-22913-rp92s9/tk8.6.4/unix/../generic/tk.h:96:25: fatal error: X11/Xlib.h: 没有那个文件或目录
compilation terminated.
Makefile:954: recipe for target 'tkBusy.o' failed
make: *** [tkBusy.o] Error 1

**Comment by sjackman** [comment]
Install tcl-tk without support for X11. See `brew options tcl-tk`
