### ISSUE TITLE
configure "--env=inherit" to be enabled by default?

### ISSUE THREAD

**Issue by ahundt** [Homebrew/linuxbrew#642]
Is there a way to configure linuxbrew so that `brew install blah` will run as if I specified `brew install blah --env=inherit`?

I guess I could alias brew to `brew --env=inherit` in my .bashrc, but that doesn't seem likely to be the best option.

**Comment by sjackman** [comment]
The alias is your best bet. What environment variable in particular do you need to pass through?

**Comment by ahundt** [comment]
I believe this was me installing with a dependent linuxbrew rather than an independent one, so I was trying to make sure the library configure paths were consistent.
