### ISSUE TITLE
profanity formula depends on 'libcurl'

### ISSUE THREAD

**Issue by benjaminfjones** [Homebrew/linuxbrew#646]
Installing 'profanity' fails because of a missing dependency on 'libcurl'.

```
$ brew info profanity
profanity: stable 0.4.7, HEAD
Console based XMPP client
http://www.profanity.im/
Not installed
From: https://github.com/Homebrew/linuxbrew/blob/master/Library/Formula/profanity.rb
==> Dependencies
Build: autoconf ✔, automake ✔, pkg-config ✔
Required: ossp-uuid ✔, libstrophe ✔, readline ✔, glib ✔, openssl ✔, gnutls ✔
Recommended: libotr ✔
Optional: terminal-notifier ✘
```

From a completely bare linuxbrew, running `brew install profanity` fails at the configuring profanity stage: https://gist.github.com/benjaminfjones/4c731692e0a01e6059d8#file-configure-log-L57

(actually, `brew install profanity` fails before this because of the libgcrypt issue #470 , but I worked around that)

**Comment by benjaminfjones** [comment]
*Update* - if I install curl manually, the profanity configure scripts gets further, but fails saying `configure: error: libuuid is required for profanity`. Now it seems that a dependency 'ossp-uuid' has already been installed and is incompatible with 'libuuid' which looks like it provides the right symbol.

**Comment by DomT4** [comment]
Resolved the `libcurl` issue. Can you open a new issue for the `libuuid` problem with some logs on that if still reproducing? Thanks.

**Comment by benjaminfjones** [comment]
Opened #674 for the `libuuid` problem.
