### ISSUE TITLE
uninitialized constant OS_VERSION

### ISSUE THREAD

**Issue by automaticgiant** [Homebrew/linuxbrew#649]
```
~/.linuxbrew/Library/Homebrew/global.rb:30:in `<top (required)>': uninitialized constant OS_VERSION (NameError)
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from ~/.linuxbrew/Library/brew.rb:15:in `<main>'
```
This happened after a brew update. I have tried removing ~/.linuxbrew and ~/.gem and reinstalling and any brew command I run after gives this result.

**Comment by naseer** [comment]
Same here

**Comment by naseer** [comment]
Dup of #648

**Comment by DomT4** [comment]
If `brew update` doesn't work you'll need to run:

```bash
git fetch && git reset --hard origin/master
```
Inside your Linuxbrew install to get `brew` functional again. Hopefully not many people updated over the last few hours. Sorry about this folks.

**Comment by sjackman** [comment]
@mikemcquaid Sorry, Mike. Slip of the finger.
