### ISSUE TITLE
brew failure after update

### ISSUE THREAD

**Issue by aviantask** [Homebrew/linuxbrew#651]
Hi,

I ran 'brew update' and immediately after the update, all brew commands are failing with following error ---

/Library/Homebrew/global.rb:30:in `<top (required)>': uninitialized constant OS_VERSION (NameError)
from home/software/brew/linuxbrew/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
from /home/software/brew/linuxbrew/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
from /home/software/brew/linuxbrew/Library/brew.rb:15:in `<main>'

How can I fix this? Thanks.

**Comment by naseer** [comment]
dup #648

**Comment by DomT4** [comment]
Working on it. Please track https://github.com/Homebrew/linuxbrew/issues/648, Thanks.

**Comment by DomT4** [comment]
If `brew update` doesn't work you'll need to run:

```bash
git fetch && git reset --hard origin/master
```
Inside your Linuxbrew install to get `brew` functional again. Hopefully not many people updated over the last few hours. Sorry about this folks.
