### ISSUE TITLE
alpaths-lg install failing

### ISSUE THREAD

**Issue by aviantask** [Homebrew/linuxbrew#654]
I have been getting the following error while installing Allpaths-lg : 

    In file included from ./math/Functions.h:13:0,
                 from ./feudal/MasterVec.h:28,
                 from ./VecString.h:14,
                 from ./CoreTools.h:22,
                 from paths/long/SupportedHyperBasevector4.cc:12:
     ./math/Arith.h:138:10: note: candidate: std::ostream& operator<<(std::ostream&, const Float&)
     ostream& operator<< ( ostream& out, const Float& aFloat ) {
          ^
    Makefile:3398: recipe for target 'SupportedHyperBasevector4.o' failed
    make[1]: *** [SupportedHyperBasevector4.o] Error 1
    make[1]: Leaving directory '/tmp/allpaths-lg20151117-57675-1c22fko/allpathslg-50378/src'
    Makefile:284: recipe for target 'install-recursive' failed
    make: *** [install-recursive] Error 1

I saw the same issue reported for OSX where this issue was closed putting a linux-requirement on it. Could this be an issue due to recent merge of homebrew master with linuxbrew master?

**Comment by sjackman** [comment]
This issue was moved to Homebrew/homebrew-science#3034
