### ISSUE TITLE
Ruby md5.so rb_Digest_MD5_Init error

### ISSUE THREAD

**Issue by jfreimer** [Homebrew/linuxbrew#656]
I just tried to install homebrew and got the following error:

Error: /N/soft/rhel6/ruby/1.9.3-p484/lib/ruby/1.9.1/x86_64-linux/digest/md5.so: undefined symbol: rb_Digest_MD5_Init - /N/soft/rhel6/ruby/1.9.3-p484/lib/ruby/1.9.1/x86_64-linux/digest/md5.so
Please report this bug:
    https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/N/soft/rhel6/ruby/1.9.3-p484/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/N/soft/rhel6/ruby/1.9.3-p484/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/N/home/j/f/jfreimer/Mason/.linuxbrew/Library/Homebrew/formulary.rb:1:in `<top (required)>'
/N/soft/rhel6/ruby/1.9.3-p484/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/N/soft/rhel6/ruby/1.9.3-p484/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/N/home/j/f/jfreimer/Mason/.linuxbrew/Library/Homebrew/formula.rb:8:in `<top (required)>'
/N/soft/rhel6/ruby/1.9.3-p484/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/N/soft/rhel6/ruby/1.9.3-p484/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/N/home/j/f/jfreimer/Mason/.linuxbrew/Library/Homebrew/descriptions.rb:1:in `<top (required)>'
/N/soft/rhel6/ruby/1.9.3-p484/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/N/soft/rhel6/ruby/1.9.3-p484/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/N/home/j/f/jfreimer/Mason/.linuxbrew/Library/Homebrew/cmd/tap.rb:2:in `<top (required)>'
/N/soft/rhel6/ruby/1.9.3-p484/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/N/soft/rhel6/ruby/1.9.3-p484/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/N/home/j/f/jfreimer/Mason/.linuxbrew/Library/Homebrew/cmd/update.rb:1:in `<top (required)>'
/N/soft/rhel6/ruby/1.9.3-p484/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/N/soft/rhel6/ruby/1.9.3-p484/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/N/home/j/f/jfreimer/Mason/.linuxbrew/Library/brew.rb:72:in `require?'
/N/home/j/f/jfreimer/Mason/.linuxbrew/Library/brew.rb:122:in `<main>'

**Comment by sjackman** [comment]
It looks to me like an error with your ruby interpreter. I'm afraid that I don't have time available to help troubleshoot this. Sorry I couldn't be of more help.
