### ISSUE TITLE
libpng needs to update

### ISSUE THREAD

**Issue by tibaes** [Homebrew/linuxbrew#658]
The current formula for libpng inside linux-brew differs from the main homebrew.
The linux brew have libpng-1.6.18 and the homebrew libpng-1.6.19.
Unfortunately, the .18 version is no longer available, so the linux-brew cannot install it.
I replaced the formula of the libpng in my machine and it worked.

**Comment by wengs** [comment]
I encountered this while installing libpng on my Linux server too. I tried the following instead

 ```brew install  https://dl.bintray.com/homebrew/mirror/libpng-1.6.19.tar.xz```.

But I got another error: 

```
Error: /home/tnf_app/.cache/Homebrew/Formula/libpng-1.6.19.tar.xz:1: invalid multibyte char (UTF-8)
Please report this bug:
    https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/home/tnf_app/.linuxbrew/Library/Homebrew/formulary.rb:21:in `module_eval'
/home/tnf_app/.linuxbrew/Library/Homebrew/formulary.rb:21:in `load_formula'
/home/tnf_app/.linuxbrew/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/home/tnf_app/.linuxbrew/Library/Homebrew/formulary.rb:83:in `load_file'
/home/tnf_app/.linuxbrew/Library/Homebrew/formulary.rb:138:in `load_file'
/home/tnf_app/.linuxbrew/Library/Homebrew/formulary.rb:74:in `klass'
/home/tnf_app/.linuxbrew/Library/Homebrew/formulary.rb:70:in `get_formula'
/home/tnf_app/.linuxbrew/Library/Homebrew/formulary.rb:205:in `factory'
/home/tnf_app/.linuxbrew/Library/Homebrew/extend/ARGV.rb:18:in `block in formulae'
/home/tnf_app/.linuxbrew/Library/Homebrew/extend/ARGV.rb:16:in `map'
/home/tnf_app/.linuxbrew/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/home/tnf_app/.linuxbrew/Library/Homebrew/cmd/install.rb:45:in `install'
/home/tnf_app/.linuxbrew/Library/brew.rb:145:in `<main>'
```

**Comment by dunn** [comment]
Linuxbrew usually merges the formula updates from Homebrew once a week, but the primary maintainer is on vacation and so the update cycle is a little slower than usual.  Apologies for the inconvenience!

**Comment by tibaes** [comment]
@wengs I replaced the libpng formula from the linuxbrew with the home-brew version and it worked just fine.

@dunn good to know! Do you prefer that I close the issue?

**Comment by DomT4** [comment]
We merged an update the other day containing this, but had to revert because it basically broke Linuxbrew for everyone. I believe Dana is investigating, but yeah, updates are slower than usual at the moment due to Shaun's absence.

**Comment by tseemann** [comment]
@DomT4 we need a new issue category called `Shaun_Vacation` :-) @sjackman

**Comment by DomT4** [comment]
Linuxbrew essentially needs another (even temporary) maintainer who both uses Linux regularly and is rich enough to spend hours debugging issues on a regular basis for no financial reward. The joys of FOSS :smile_cat:.

Considering we have 9 core maintainers to keep on top of everything, and Linuxbrew has Shaun, it's easy to see why things get stretched.

**Comment by tseemann** [comment]
Yes, Shaun has a large burden. I spend more time than I should on Homebrew, and it's mainly formulae for science. I am not a ruby native and I don't really understand the internals of Brew, and I struggle with the conflicts with the OS X maintainers who don't really want Linuxbrew co-existing. It's tempting to jump ship to something like https://bioconda.github.io/ but I just don't feel it is as mature.

**Comment by sjackman** [comment]
@danabrand Do you have the time for a merge with some help from the above commenters, whom I have just unilaterally volunteered? :smirk:

**Comment by danabrand** [comment]
I don't have time, but I will make it... Give me a couple of days. Sorry guys, it got very busy at work and that's why my previous merge was rushed and not fully tested either. Promise to get back in max 48 hrs with a merge.

**Comment by sjackman** [comment]
@DomT4 @tseemann Can you please give Dana a hand by answering her questions and testing the merge before pushing?

**Comment by tseemann** [comment]
There was another pull request for the update to libpng. I merged it and tested it and it seems fine. But i'm worried i was a bit premature and didn't notice this thread until now. How do I know if i've broken everything? @DomT4

**Comment by DomT4** [comment]
Thanks @danabrand, once again. Sorry so much of this has fallen on you exclusively, really do appreciate the amount of pressure that is. I have a Linuxbrew Debian VM set up, so if anyone needs access let me know.

@tseemann You won't have broken things for users, but if Dana may have to resolve a merge conflict on that since it's now a permanent part of the git history. Users will probably appreciate the update since `libpng` had a security vuln.

**Comment by danabrand** [comment]
just an update I am working on the merge, but I am looking at 108 conflicts at the moment, not sure what we reverted to or you guys been really active:-) so trolling through them... hope to push something by end of day, PST.

**Comment by tseemann** [comment]
@DomT4 Thanks for clarifying. I understand now that @danabrand is merging upstream brew. I don't envy that job - my recent `brew update -v` has scrolled pages up my terminal. Lots of stuff going on.

**Comment by DomT4** [comment]
Has been updated with @tseemann's commit.
