### ISSUE TITLE
imagemagick formula needs updating.

### ISSUE THREAD

**Issue by Slugger70** [Homebrew/linuxbrew#661]
In a similar fashion to libpng, the version of imagemagick that the formula attempts to download is no longer available. version 6.9.2-4 is referenced in the current formula but the version available for download is 6.9.2-6.

**Comment by tseemann** [comment]
There seems to be a problem with `harfbuzz` dependency when I try to update this....

**Comment by danabrand** [comment]
@tseemann Just tried the formula that I pushed yesterday in my danabrand repo and it seems to go through fine. This is on Centos 6.x. When installing `freetype` as a dependency, it used `configure  --without-harfbuzz` though.

**Comment by tseemann** [comment]
@danabrand I was compiling with `with-librsvg` as I need SVG support to convert SVG to PNG. But if it works in the regular case, I would push it urgently, as, like with `libpng`, they have removed the `.xz` file of the version currently in Brew (so annoying!).

**Comment by danabrand** [comment]
@tseemann I can't push myself to the master - if anyone can take it from my repo and push, that will do.

**Comment by aviantask** [comment]
The problem has reoccurred now with new version being 6.9.2-8

**Comment by kubapol** [comment]
+1 I've got the same problem
```sh
==> Downloading http://www.imagemagick.org/download/releases/ImageMagick-6.9.2-6.tar.xz

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading http://ftp.nluug.nl/ImageMagick/ImageMagick-6.9.2-6.tar.xz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "imagemagick"
Download failed: http://ftp.nluug.nl/ImageMagick/ImageMagick-6.9.2-6.tar.xz'

```

Can someone fix the links?

**Comment by sjackman** [comment]
Try `brew update`. The current version is 6.9.3-0
I'm on vacation until Tuesday. My replies may be delayed.

**Comment by michaeljohnsargent** [comment]
I'm having the same issue above - "404 Not Found"

 ```brew install imagemagick --with-jasper                                              08-30-16 10:34:49
==> Downloading https://dl.bintray.com/homebrew/mirror/imagemagick-6.9.5-7.tar.xz```

```curl: (28) Connection timed out after 5338 milliseconds
Trying a mirror...
==> Downloading https://www.imagemagick.org/download/ImageMagick-6.9.5-7.tar.xz```

```curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "imagemagick"
Download failed: https://www.imagemagick.org/download/ImageMagick-6.9.5-7.tar.xz```

Can someone assist?
