### ISSUE TITLE
git 2.6.3 wanted

### ISSUE THREAD

**Issue by netroby** [Homebrew/linuxbrew#664]
git 2.6.3 released. but the linuxbrew repository only have 2.6.1 , may you please match it to 2.6.3?

**Comment by Mikaela** [comment]
What is the git version at homebrew? Linuxbrew updates from there weekly or at least used to, I am not sure if it has changed.

**Comment by DomT4** [comment]
We're working on getting the repos synced up again. Shaun, who is Linuxbrew's maintainer, has been away so things have slowed a bit. We have a brilliant volunteer called Dana working on getting a merge done. Just bear with us a little bit longer and we'll have it synced.
