### ISSUE TITLE
Install hhvm failed

### ISSUE THREAD

**Issue by lima01** [Homebrew/linuxbrew#666]
I was able to install HHVM using homebrew on Mac. But got the following error when tried on CentOS6 with LinuxBrew:

 [lma@centos6 elfutils-0.161]$ brew install hhvm
 ==> Installing hhvm from hhvm/homebrew-hhvm
 ==> Installing dependencies for hhvm/hhvm/hhvm: dwarfutils, gawk, libtool, md5sha1sum, ocaml,  bzip2, boost, libpng, freetype
 ==> Installing hhvm/hhvm/hhvm dependency: dwarfutils
 ==> Downloading http://www.prevanders.net/libdwarf-20150507.tar.gz
 Already downloaded: /home/lma/.cache/Homebrew/dwarfutils-20150507.tar.gz
 ==> ./configure
 ==> make
 Last 15 lines from /home/lma/.cache/Homebrew/Logs/dwarfutils/02.make:
 ar: creating libdwarf.a
 make[1]: Leaving directory `/tmp/dwarfutils20151125-25747-1godp0j/dwarf-20150507/libdwarf'
 cd dwarfdump && make
 make[1]: Entering directory `/tmp/dwarfutils20151125-25747-1godp0j/dwarf-20150507/dwarfdump'
 make[1]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
 /home/lma/.linuxbrew/bin/gcc-5  -Os -w -pipe -march=core2 -I. -I. -I./../libdwarf -DCONFPREFIX=/ usr/local/lib  -c ./common.c
 /home/lma/.linuxbrew/bin/gcc-5  -Os -w -pipe -march=core2 -I. -I. -I./../libdwarf -DCONFPREFIX=/ usr/local/lib  -isystem/home/lma/.linuxbrew/include  -c -o tag_common.o tag_common.c
 /home/lma/.linuxbrew/bin/gcc-5  -Os -w -pipe -march=core2 -I. -I. -I./../libdwarf -DCONFPREFIX=/ usr/local/lib  -c ./makename.c
 /home/lma/.linuxbrew/bin/gcc-5  -Os -w -pipe -march=core2 -I. -I. -I./../libdwarf -DCONFPREFIX=/ usr/local/lib  -DTRIVIAL_NAMING  -c ./naming.c -o trivial_naming.o 
 In file included from ./naming.c:36:0:
 ./globals.h:92:27: fatal error: libelf/libelf.h: No such file or directory
 compilation terminated.
 make[1]: *** [trivial_naming.o] Error 1
 make[1]: Leaving directory `/tmp/dwarfutils20151125-25747-1godp0j/dwarf-20150507/dwarfdump'
 make: *** [basic] Error 2
 
 READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting. md#troubleshooting

Thanks in advanced for any help!

**Comment by sjackman** [comment]
Please report this issue upstream to the hhvm authors and ask them whether they would like to support Linuxbrew.
