### ISSUE TITLE
404 error on brew install openssl

### ISSUE THREAD

**Issue by davidyarham** [Homebrew/linuxbrew#688]
Only this afternoon (This morning seemed to be fine) I am getting.

==> Downloading https://www.openssl.org/source/openssl-1.0.2.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://raw.githubusercontent.com/DomT4/LibreMirror/master/OpenS

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "openssl"
Download failed: https://raw.githubusercontent.com/DomT4/LibreMirror/master/OpenSSL/openssl-1.0.2.tar.gz

**Comment by DomT4** [comment]
Your Linuxbrew seems to be quite out of date. Please try `brew update`.

**Comment by wittawasw** [comment]
`master` branch's out of date.
`openssl-1.0.2d.tar.gz` is not available anymore, they changed it to `openssl-1.0.2e.tar.gz` already

merging source from `homebrew/homebrew` will fix this.

**Comment by anirudh-ramesh** [comment]
I tried updating Linuxbrew earlier today, but I couldn't fix it. So I manually updated the file. Here's the fix to this issue:

Open ``~/.linuxbrew/Library/Formula/openssl.rb``

Replace ``url "https://www.openssl.org/source/openssl-1.0.2d.tar.gz"`` with ``url "https://www.openssl.org/source/openssl-1.0.2e.tar.gz"``

Replace ``sha256 "671c36487785628a703374c652ad2cebea45fa920ae5681515df25d9f2c9a8c8"``  with ``sha256 "e23ccafdb75cfcde782da0151731aa2185195ac745eea3846133f2e05c0e0bff"``

**Comment by sjackman** [comment]
Thanks for the workaround. This issue will be fixed in the new year.

**Comment by skylerzhang** [comment]
thanks DomT4

**Comment by skylerzhang** [comment]
thank DomT4
