### ISSUE TITLE
libevent source outdated

### ISSUE THREAD

**Issue by nachoaIvarez** [Homebrew/linuxbrew#691]
When installing formulas that have libevent as a dependency (tmux for example) you get a 404 since [this](https://sourceforge.net/projects/levent/files/libevent/libevent-2.0/libevent-2.0.22-stable.tar.gz) is outdated. The correct version can be found [here](https://github.com/libevent/libevent).

**Comment by sjackman** [comment]
This issue will be fixed in the new year when Homebrew is merged into Linuxbrew. Thanks for the bug report.
