### ISSUE TITLE
Unable to clone linuxbrew

### ISSUE THREAD

**Issue by tinyheero** [Homebrew/linuxbrew#70]
Hi,

When I am try to git clone the linuxbrew repository, I am getting this error:

> > git clone https://github.com/Homebrew/linuxbrew.git ~/.linuxbrew
> > Cloning into /home/fong/.linuxbrew...
> > error: error:0D0C50A1:asn1 encoding routines:ASN1_item_verify:unknown message digest algorithm while accessing https://github.com/Homebrew/linuxbrew.git/info/refs
> > fatal: HTTP request failed

Has anyone experienced this?

**Comment by chvcdeepak** [comment]
In my case for the above error below command worked

**git config --global http.sslVerify false**

**Comment by francicco** [comment]
Hi guys also for me it's not working, and I just installed the latest version of openSSL

```
$ openssl version -a
OpenSSL 1.0.1t  3 May 2016
built on: Fri Jun 10 17:45:19 2016
platform: linux-x86_64
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) idea(int) blowfish(idx) 
compiler: gcc -I. -I.. -I../include  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -m64 -DL_ENDIAN -O3 -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM
OPENSSLDIR: "/scratch/c770/c7701100/software/openssl_1.0.1t/ssl"
```

Any help?
thanks
F

**Comment by sjackman** [comment]
Hi, Francesco. This particular repository `Linuxbrew/linuxbrew` is no longer used. Please open a new ticket at `Linuxbrew/brew`. Thanks!
