### ISSUE TITLE
git: Unable to install `git` unless it already exists in the system

### ISSUE THREAD

**Issue by youtux** [Homebrew/linuxbrew#700]
Hello, I'm trying to make linuxbrew work on debian/ubuntu machines where I do not have root privileges. The only relevant package installed is `build-essential`. My goal is to have brew up and running in order to install all the packages I need in userspace.

I installed linuxbrew by downloading the install script and running it with:
```
$ wget "https://raw.githubusercontent.com/Homebrew/linuxbrew/go/install"
$ ruby -e "$(cat install)"
```
The installation succeded, but in order to install anything, I need `git` of course. The problem is that when I try to install it, brew will loop forever printing `==> Installing git`.

This is the output:
```
$ brew install git --verbose --debug 2>&1
/home/youtux/.linuxbrew/Library/brew.rb (Formulary::FormulaLoader): loading /home/youtux/.linuxbrew/Library/Formula/git.rb
/home/youtux/.linuxbrew/Library/brew.rb (Formulary::FormulaLoader): loading /home/youtux/.linuxbrew/Library/Formula/xz.rb
/home/youtux/.linuxbrew/Library/brew.rb (Formulary::FormulaLoader): loading /home/youtux/.linuxbrew/Library/Formula/expat.rb
/home/youtux/.linuxbrew/Library/brew.rb (Formulary::TapLoader): loading /home/youtux/.linuxbrew/Library/Taps/homebrew/homebrew-dupes/tcl-tk.rb
==> Installing git
/home/youtux/.linuxbrew/Library/brew.rb (Formulary::TapLoader): loading /home/youtux/.linuxbrew/Library/Taps/homebrew/homebrew-dupes/tcl-tk.rb
==> Installing git
/home/youtux/.linuxbrew/Library/brew.rb (Formulary::TapLoader): loading /home/youtux/.linuxbrew/Library/Taps/homebrew/homebrew-dupes/tcl-tk.rb
==> Installing git
/home/youtux/.linuxbrew/Library/brew.rb (Formulary::TapLoader): loading /home/youtux/.linuxbrew/Library/Taps/homebrew/homebrew-dupes/tcl-tk.rb
==> Installing git
[... to infinity]
```

Could it be the case that brew is trying to call the `git` executable to load the `homebrew-dupes` tap, but it keeps failing because there is no `git` installed?

**Comment by sjackman** [comment]
See https://github.com/sjackman/docker-linuxbrew/blob/91f509802167f10a1ba9394c3750197b9a6eb9b6/linuxbrew-standalone/Dockerfile#L6-L8

Try
```sh
# Install git without tcl-tk to prevent the error:
# Tapping homebrew/dupes. You must: brew install git
RUN brew install git --with-brewed-curl --with-brewed-openssl --without-tcl-tk
```

I think that perhaps `--without-tcl-tk` should be the default on Linux. The downside is that the GUI `gitk` won't be built. What do you think?

**Comment by youtux** [comment]
In that case you wouldn't benefit from the binary version already on Bintray, am I right? Or is that only an homebrew (for Mac OS) thing?

Maybe the `brewed-curl` and `brewed-openssl` options should be the default on Linux, too.

**Comment by sjackman** [comment]
> In that case you wouldn't benefit from the binary version already on Bintray, am I right? Or is that only an homebrew (for Mac OS) thing?

Bottles are only created automatically for Mac. Linux can use bottles, but they're not created automatically.

> Maybe the brewed-curl and brewed-openssl options should be the default on Linux, too.

Yes, I think that would be a good idea.

**Comment by cdonnellytx** [comment]
FWIW, I have git 1.7.1 on my system (RHEL 6.5 x64), but it is older than the minimum recommended version.  Attempting to update git with linuxbrew results in a compliation error with homebrew/dupes/tcl-tk, so it sounds like there are multiple issues with tcl-tk being pulled in by git.

**Comment by sjackman** [comment]
I've change the `tcl-tk` dependency of `git` from `recommended` to `optional`.
