### ISSUE TITLE
`brew doctor` warns about using Homebrew/linuxbrew as an origin

### ISSUE THREAD

**Issue by rwhogg** [Homebrew/linuxbrew#705]
`brew doctor` now gives the following message:
    Warning: Suspicious git origin remote found.

    With a non-standard origin, Homebrew won't pull updates from the main repository. The current git origin is:
      https://github.com/Homebrew/linuxbrew

    Unless you have compelling reasons, consider setting the origin remote to point at the main repository, located at:
      https://github.com/Homebrew/homebrew.git

I know you don't want to Linux-ize everything unnecessarily, but IMO having a clean `brew doctor` output is worth specifically changing.

**Comment by sjackman** [comment]
Yes. I agree. I'll fix this.

**Comment by sjackman** [comment]
Fixed. Thanks for the bug report, Bob.
