### ISSUE TITLE
snap installation fails

### ISSUE THREAD

**Issue by peterdfields** [Homebrew/linuxbrew#706]
Installation of snap fails with the following message:

==> Installing homebrew/science/maker dependency: snap
==> Downloading http://korflab.ucdavis.edu/Software/snap-.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "snap"
Download failed: http://korflab.ucdavis.edu/Software/snap-.tar.gz

Installation works fine if the brew script is edited with brew edit snap and inserting:

http://korflab.ucdavis.edu/Software/snap-2013-11-29.tar.gz

**Comment by sjackman** [comment]
This issue was moved to Homebrew/homebrew-science#3179
