### ISSUE TITLE
Upgrade of GMP Failing

### ISSUE THREAD

**Issue by jwhite007** [Homebrew/linuxbrew#707]
The logs are here... https://gist.github.com/5484cff5aa44fd12cc9b

Thanks in advance for any feedback.

**Comment by sjackman** [comment]
I don't have a proper fix for this issue just yet. The workaround is:
```sh
LD_LIBRARY_PATH=`brew --prefix gmp`/lib brew upgrade gmp
```

**Comment by sjackman** [comment]
https://gist.github.com/anonymous/5484cff5aa44fd12cc9b#file-config-log-L113
`/toolbox/NGS/.linuxbrew_amd/Cellar/gcc/5.2.0/libexec/gcc/x86_64-unknown-linux-gnu/5.2.0/cc1: error while loading shared libraries: libgmp.so.10: cannot open shared object file: No such file or directory`

**Comment by jwhite007** [comment]
Thank you, sir, for the quick reply. That worked.
