### ISSUE TITLE
sphinx-doc failed to build on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by retokromer** [Homebrew/linuxbrew#710]
Information: `sphinx-doc` is a dependency of `x265`.
`brew gist-logs sphinx-doc` output:
https://gist.github.com/294cd8ab5d71412481cc
Terminal output:
![screenshot from 2016-01-10 10 42 14](https://cloud.githubusercontent.com/assets/3246607/12220959/39621c90-b787-11e5-81d9-1caf257fd637.png)
I fear this may also be a regression.

**Comment by sjackman** [comment]
https://gist.github.com/anonymous/294cd8ab5d71412481cc#file-01-python-L17
`ImportError: No module named setuptools`

See https://github.com/Homebrew/linuxbrew/issues/562#issuecomment-141694092
Try `sudo apt-get install python-setuptools`
and possibly also `sudo apt-get install python-dev`

Are you on a Ubuntu/Debian system?

**Comment by retokromer** [comment]
After `sudo apt-get install python-setuptools` this works fine. Thank you!
Now I will test the also the installation of x265 (this was a dependency).

**Comment by sjackman** [comment]
Glad to hear that you got it working. I've added `python-setuptools` to the list of dependencies of Linuxbrew.
https://github.com/Homebrew/linuxbrew/blob/master/README.md#debian-or-ubuntu

**Comment by retokromer** [comment]
Now I have the cmake issue. I'll delve into the discussion about it.

**Comment by retokromer** [comment]
No, false alarm: cmake works well.

**Comment by retokromer** [comment]
And x265 as well (and also with ffmpeg, as expected). Thank you very much indeed!

**Comment by sjackman** [comment]
Great! I'm glad to hear that it's all working.
