### ISSUE TITLE
ImportError: No module name 'ah'

### ISSUE THREAD

**Issue by sheenawadhwa** [Homebrew/linuxbrew#711]
am using window 7 
when am trying to import dpkt it gives the following error
>>> import dpkt
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import dpkt
  File "C:\Python34\lib\site-packages\dpkt\__init__.py", line 13, in <module>
    import ah
ImportError: No module named 'ah'

can someone help me

**Comment by sjackman** [comment]
Your error is not related to this project, Linuxbrew.

**Comment by sheenawadhwa** [comment]
yes i know but there must be solution to solve this

**Comment by sjackman** [comment]
Linuxbrew does not run on Windows 7. I think that you have the wrong project. What are you trying to do, or what software are you trying to run?
