### ISSUE TITLE
Possible hacks to ensure gcc-4.8 used, instead of gcc-4.9?

### ISSUE THREAD

**Issue by hughperkins** [Homebrew/linuxbrew#712]
I have gcc-4.8 and g++-4.8 installed, on ubuntu 14.04.  But, gcc-4.9 also exists, which is part of gccgo-4.9 package:

```
$ dpkg -S /usr/bin/gcc-4.9
gccgo-4.9: /usr/bin/gcc-4.9
```
This means, when I install things, brew tries to use g++-4.9, instead of g++-4.9, and fails.  Currently, for each install, I have to do:
- `brew install --debug foo`
- when it crashes, choose option 'shell'
- CC=/usr/bin/gcc-4.8
- CXX=/usr/bin/g++-4.8
- (rerun the last command)
- exit
- choose option 'ignore'
- => build continues ok

If I untar the package, eg cmake-something.tar.gz, and run eg `./bootstrap` directly, it works just fine.  Just not from brew, at least, not without modifying the env vars as above.

What hack(s) can I do to my system so that brew works correctly?

**Comment by sjackman** [comment]
Set `export HOMEBREW_CC=gcc-4.8`
This configuration options appears to be undocumented.

**Comment by sjackman** [comment]
If you'd like to use a more recent GCC, `brew install gcc` will work as well.

**Comment by hughperkins** [comment]
Setting HOMEBREW_CC=gcc-4.8 didnt work for me.   Gave me things like 'Invalid value for HOMEBREW_CC: /usr/bin/gcc-4.8'

What I did in the end was insert into line 177 of Library/Homebrew/extend/ENV/shared.rb `return 'gcc-4.8'`. This works ok :-)

**Comment by sjackman** [comment]
`HOMEBREW_CC` must not include the absolute path, just `gcc-4.8`

**Comment by hughperkins** [comment]
```
$ brew install --cc=gcc-4.8 mysql
Error: Homebrew GCC requested, but formula gcc48 not found!
```

**Comment by hughperkins** [comment]
```
$ HOMEBREW_CC=gcc-4.8 brew install mysql
Error: Homebrew GCC requested, but formula gcc48 not found!
```

**Comment by sjackman** [comment]
Try `brew tap homebrew/versions` and `HOMEBREW_CC=gcc-4.8 brew install mysql`

**Comment by hughperkins** [comment]
Looks like that fixed it!  Thanks! :-)

**Comment by sjackman** [comment]
Glad to hear it!
