### ISSUE TITLE
'official' way to build single-threaded

### ISSUE THREAD

**Issue by hughperkins** [Homebrew/linuxbrew#714]
Building mysql on my box causes the box to crash, because it builds multithreaded, using up all available memory.

I am forcing it to single-threaded now by changing line 38 of Library/Homebrew/extend/ENV/std.rb , to remove the -j option, but just wondering what are the relatively standard ways to achieve this?

**Comment by dunn** [comment]
You can set the environment variable `HOMBREW_MAKE_JOBS=1`

**Comment by hughperkins** [comment]
cool. Thanks! :-)
