### ISSUE TITLE
Ugrade of GCC Fails

### ISSUE THREAD

**Issue by jwhite007** [Homebrew/linuxbrew#716]
Here are the gist logs... https://gist.github.com/anonymous/af3ca8ceaf17eaa72b8a

**Comment by jwhite007** [comment]
"brew upgrade gcc --cc=gcc-4.4" seems to have solved it.

**Comment by sjackman** [comment]
Glad to hear that you found a workaround.

**Comment by jwhite007** [comment]
An upgrade of GCC using "brew upgrade gcc --cc=gcc-4.4" is now failing on another server on which I've installed linuxbrew in the same manner (standalone). gcc-4.4 links to /usr/bin/gcc as it does on the server on which the upgrade worked. "LD_LIBRARY_PATH=$(brew --prefix gcc)/lib brew upgrade gcc --cc=gcc-4.4" works, but I'm not sure why. I'd like to know, though. I'm far from an expert in c-package builds.

**Comment by sjackman** [comment]
My guess is that executables critical to your build, like coreutils and autotools, depend on libraries installed by `gcc` such as `libstdc++` and `libgcc_s`. This upgrade issue is a big problem and needs to be resolved. Adding the previous version's lib to LD_LIBRARY_PATH and bin to PATH temporarily is one solution. It could potentially create problems, but would probably fix more problems than it creates.

**Comment by jwhite007** [comment]
Thanks for the response. I'd like to help out with the linuxbrew project; however, I'm a data scientist and my programming skills don't extend beyond Python, R, Javascript, and some Java. Please let me know if I can help out in any way.
