### ISSUE TITLE
How to handle ncurses upgrade in stand-alone version?

### ISSUE THREAD

**Issue by jwhite007** [Homebrew/linuxbrew#719]
When I first installed the stand-alone version, I linked the ncurses files, per the instructions, with "ln -s ncursesw/curses.h ncursesw/form.h ncursesw/ncurses.h ncursesw/term.h ncursesw/termcap.h $(brew --prefix)/include/"

Firstly, I'm a little confused by the syntax. How is it that I didn't have to give the full path to the ncurses files?

With a recent "brew upgrade" ncurses was upgraded from 6.0 to 6.0_1. If I link as I did during the install, I don't see the same pointer...

Before upgrade:
curses.h -> ../Cellar/ncurses/6.0/include/curses.h

After upgrade:
curses.h -> ncursesw/curses.h

Shall I even uses the upgraded ncurses? Shall I link to the files explicitly?

Thanks.

**Comment by sjackman** [comment]
> How is it that I didn't have to give the full path to the ncurses files?

The path of the source files is relative to the path of the destination directory.

Those symlinks are now installed by the ncurses formula itself.
https://github.com/Homebrew/homebrew-dupes/blob/master/ncurses.rb#L78-L80

If it's working for you, then there's nothing you need to do.

**Comment by jwhite007** [comment]
Thanks for the reply and information. I never knew that about ln. I always assumed it either had to be an absolute path or a path relative to the working directory. That's interesting about the changes to the ncruses formula. Thanks for the link.

**Comment by sjackman** [comment]
The destination file is relative to the current working directory, but the source file is relative to the destination file. It is a bit odd.
