### ISSUE TITLE
poretools failed to build on CentOS 6

### ISSUE THREAD

**Issue by dfornika** [Homebrew/linuxbrew#720]
https://gist.github.com/anonymous/5496690e63ee1b9ff4c4

**Comment by sjackman** [comment]
Hi, Dan. The relevant error is
```
/data/home/dfornika/.linuxbrew/Cellar/r/3.2.3/lib/R/bin/Rcmd: line 62: exec: config: not found
```
https://gist.github.com/anonymous/5496690e63ee1b9ff4c4#file-01-python-L15
It's cause by this bug in the R Linuxbrew formula: #614
The workaround is
```sh
chmod +x /data/home/dfornika/.linuxbrew/Cellar/r/3.2.3/lib/R/bin/*
```

**Comment by dfornika** [comment]
Ah, right under my nose. Thanks for the fix.
